### ISSUE TITLE
Curve25519: Please provide functionality to perform scalar multiplication

### ISSUE THREAD

**Issue by triska** [briansmith/ring#1002]
First of all, thank you so much for *ring*! I am using substantial parts of your crate to implement the cryptographic functionality of [Scryer&nbsp;Prolog](https://github.com/mthom/scryer-prolog), a modern Rust-based Prolog system written by Mark&nbsp;Thom. Specifically, I am using *ring* as the foundation of many predicates in Scryer&nbsp;Prolog's [`library(crypto)`](https://github.com/mthom/scryer-prolog/blob/master/src/lib/crypto.pl), which now provides cryptographically secure random numbers, HKDF, PBKDF2, Ed25519 and symmetric authenticated encryption via *ring*, and your crate is a real joy to use!

For Prolog-based client/server applications, I now would like to add a way to use Curve25519 to establish a **shared&nbsp;secret** via ephemeral&nbsp;ECDH. Almost all the building blocks for this are already available in `library(crypto)`: Both parties can create cryptographically secure random numbers with `crypto_n_random_bytes/2` and a few integer operations. Also, given a point on an elliptic&nbsp;curve, both parties can derive a key and IV with `crypto_data_hkdf/4`, which implements&nbsp;HKDF. In fact, `library(crypto)` also contains predicates for reasoning over elliptic curves, but not yet for Curve25519.

The most essential operation that is still missing for this use case is **scalar&nbsp;multiplication** of a point on Curve25519, obtaining a new point.

I have looked at the current API for X25519 provided by *ring*. It seems ideal and well-designed for self-contained use within Rust applications. However, the requirements for the mentioned Prolog library in which I now want to use Curve25519 are such that I cannot use the API that *ring* currently offers:

1. Prolog is a *declarative* language, and its pure core lacks destructive modifications. It is therefore not possible to "overwrite", "delete" or otherwise modify a private key or integer once it exists. In the concrete use case of ECDH, once a random number is generated, it always remains existant as long as any term refers to it. For this reason, an API that annihilates a private key is not usable for this purpose. 
2. `library(crypto)` already provides HKDF as one of its predicates, and I would like to enable application programmers to use the existing HKDF predicate to derive keys and IVs from a point on the curve.

On the Prolog level, an ideal solution to perform ECDH with X25519 are two predicates:

- `curve25519_generator(G)` yielding in `G` the *generator* point in some representation, for example as a list of bytes.
- `curve25519_scalar_mult(K, Q, R)` yielding in `R` the result of `K*Q`, where `Q` and `R` are points in the same representation as above, and `K` is an integer.

Using these two predicates, a shared secret can be easily established over an insecure channel.

Would you please consider providing functionality in *ring* so that these predicates can be implemented? It would be sufficient to provide *scalar&nbsp;multiplication*, because the generator is fixed and can be specified as a Prolog&nbsp;fact once the representation of points is settled.

Thank you a lot!

**Comment by briansmith** [comment]
> Prolog is a declarative language, and its pure core lacks destructive modifications. It is therefore not possible to "overwrite", "delete" or otherwise modify a private key or integer once it exists. In the concrete use case of ECDH, once a random number is generated, it always remains existant as long as any term refers to it. For this reason, an API that annihilates a private key is not usable for this purpose.

There is an existing issue about adding the ability to have static/non-ephemeral key agreement keys. I think resolving that issue would resolve your concern here.

> library(crypto) already provides HKDF as one of its predicates, and I would like to enable application programmers to use the existing HKDF predicate to derive keys and IVs from a point on the curve.

Do you need to be able to use HKDF to derive a key from an arbitrary point on the curve, a randomly-generated point on the curve, or the result of a key agreement? In most cases the thing that makes sense is using HKDF to derive a key from the result of a key agreement, which is already possible with *ring*'s existing API; Rustls does this, for example.

**Comment by triska** [comment]
> Do you need to be able to use HKDF to derive a key from an arbitrary point on the curve, a randomly generated point on the curve, or the result of a key agreement?

In `library(crypto)`, HKDF is already available as a Prolog predicate, and it can be applied to any Prolog term. So, what I need is rather a *decoupling* of the HKDF functionality from the actual Curve25519 operations, so that I can use Curve25519 operations in isolation.

Specifically, what I need is a way to obtain the curve's generator, and the result of a scalar multiplication operation, in some suitable format. As soon as this is available, I can use the existing HKDF functionality of `library(crypto)` to establish a shared secret, and to derive a shared secret&nbsp;key from the shared&nbsp;secret. The shared secret, and also the generator, is a point on the curve, or at least some representation that uniquely denotes a point on the curve.

The way I would use `library(crypto)` to establish a shared secret between two parties `A` and `B` with Curve25519 (where `Q` is its generator) is:

1.`A` generates a random integer `a` and sends `a×Q` to `B`
2. `B` generates a random integer `b` and sends `b×Q` to `A`
3. `A` computes `a×b×Q`
4. `B` computes `b×a×Q` = `a×b×Q`

Since both parties now know the point `a×b×Q` (the shared secret), they both can use the existing HKDF predicate of `library(crypto)` to derive the same common private key, usable for symmetric encryption.

In the steps above, the new predicate `curve25519_generator/1` would be used to obtain the generator&nbsp;`Q`, and  `curve25519_scalar_mult/3` is used to perform the scalar multiplications.

**Comment by triska** [comment]
> There is an existing issue about adding the ability to have static/non-ephemeral key agreement keys. I think resolving that issue would resolve your concern here.

One issue asking for this is #331. However, as far as I can tell, it would not solve this specific issue. In fact, the converse may be true: Solving this issue may also provide a way to solve #331. 

The most closely related PR I found to address this is #910. However, it also merges the actual multiplication (to obtain a common shared&nbsp;secret) with the KDF to derive a key from the shared&nbsp;secret. I would like to keep these operations separate, because there is already existing functionality for hash-based key derivation in `library(crypto)` that only needs to be applied to a negotiated shared&nbsp;secret point to derive a key from it.

**Comment by triska** [comment]
I have now solved this issue with the `sodiumoxide` crate, here is the pull request that shows how this functionality is used:

https://github.com/mthom/scryer-prolog/pull/645

Since I no longer need this functionality from `ring`, I am closing this issue. However, I am still interested in this feature, and if `ring` provides this in the future, I will definitely use it!
