### ISSUE TITLE
Ed25519: Please generalize exporting a key into PKCS#8 format

### ISSUE THREAD

**Issue by triska** [briansmith/ring#1003]
In [`library(crypto)`](https://github.com/mthom/scryer-prolog/blob/master/src/lib/crypto.pl), I would like to provide the new predicate `ed25519_seed_keypair(+Seed, -Pair)`, which takes `Seed` (a list of bytes) as input and relates it to a new key&nbsp;pair `Pair` that is generated from `Seed`.

In *ring*, `Ed25519KeyPair::from_seed_unchecked` seems ideally suited to implement this. However, once I have generated a key in this way, is there any way to make it available to the Prolog&nbsp;level in PKCS#8 format? I would like to use this format because this is also what the existing predicate `ed25519_new_keypair/1` uses. Internally, this predicate uses `Ed25519KeyPair::generate_pkcs8`.

Could you please consider generalizing exporting a key into PKCS#8 format to cases where the key was generated from a seed?

Thank you a lot!

**Comment by briansmith** [comment]
> However, once I have generated a key in this way, is there any way to make it available to the Prolog level in PKCS#8 format?

*ring* intentionally doesn't allow a `KeyPair` to be serialized and intentionally doesn't allow the private key of the keypair to be accessed using its API.

If I understand correctly, you are looking for an API that converts a "raw" seed to PKCS#8 format, right?

Check out this:

```
    pub fn generate_pkcs8(
        rng: &dyn rand::SecureRandom,
    ) -> Result<pkcs8::Document, error::Unspecified> {
        let seed: [u8; SEED_LEN] = rand::generate(rng)?.expose();
        let key_pair = Self::from_seed_(&seed);
        Ok(pkcs8::wrap_key(
            &PKCS8_TEMPLATE,
            &seed[..],
            key_pair.public_key().as_ref(),
        ))
    }
```

IIUC, What you need is a new API like this, right?:

```
    pub fn seed_to_pkcs8(
        seed: &Seed,
    ) -> Result<pkcs8::Document, error::KeyRejected> {
        let key_pair = Self::from_seed_(seed);
        Ok(pkcs8::wrap_key(
            &PKCS8_TEMPLATE,
            &seed[..],
            key_pair.public_key().as_ref(),
        ))
   }
```

If somebody makes a PR that adds this and adds test for it, I'm happy to add it.

**Comment by triska** [comment]
Thank you a lot, I have filed PR #1044 for this!

**Comment by justprosh** [comment]
> _ring_ intentionally doesn't allow a `KeyPair` to be serialized and intentionally doesn't allow the private key of the keypair to be accessed using its API.

@briansmith can you please explain why?
