### ISSUE TITLE
ring is affected by a nightly Cargo regression

### ISSUE THREAD

**Issue by oconnor663** [briansmith/ring#1009]
Ring seems to have [the same issue as e.g. the `remove_dir_all` crate had](https://github.com/XAMPPRocky/remove_dir_all/issues/19), with the most recently nightly toolchain:

```
error: failed to download `ring v0.16.14`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/jacko/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.14/Cargo.toml`

Caused by:
  readme file with name 'doc/link-to-readme.md' was not found
```

This is tracked at rust-lang/cargo#8351 and already fixed by rust-lang/cargo#8353. However, to unbreak callers until the next nightly goes out, it might be nice to fix the error downstream.

**Comment by briansmith** [comment]
Thanks. I think PR #1010 will fix this.
