### ISSUE TITLE
Help verifying a signature

### ISSUE THREAD

**Issue by willm** [briansmith/ring#1015]
I'm a bit new to crypto, so sorry if I'm doing something obviously wrong. I am trying to verify a signature that was generated using code equivalent to:

```bash
printf 'hello' | openssl dgst \
  -sha256 \
  -sign my/private/key.pem \
  -out - \
  - | base64
```

I tried converting my pem key to der as suggested in the [documentation](https://docs.rs/ring/0.16.9/ring/signature/index.html#signing-and-verifying-with-rsa-pkcs1-15-padding)

and verifying like so, but am struggling (I get a BadSignature error).

```rust
use base64;
use ring::{
  rand,
  signature::{self},
};

type RingResult<T> = Result<T, MyError>;

#[derive(Debug)]
enum MyError {
  IO(std::io::Error),
  BadPrivateKey,
  OOM,
  BadSignature,
}

fn verify(msg: &[u8], signature: &[u8]) -> RingResult<()> {
  let public_key_path = std::path::Path::new("my/private/key.pem"); // the output of the open ssl command above
  let public_key = signature::UnparsedPublicKey::new(
    &signature::RSA_PKCS1_2048_8192_SHA256,
    read_file(public_key_path)?,
  );
  public_key
    .verify(msg, &signature)
    .map_err(|_| MyError::BadSignature)
}

fn main() {
  let nonce: &[u8] = b"hello";
  let signature = "base64 encoded signature";
  let decoded_sig = base64::decode(signature).unwrap();
  let sliced_sig = decoded_sig.as_slice();

  verify(nonce, sliced_sig).unwrap();
}
```

The open ssl command I'm using to verify that works is:

```bash
printf 'hello' | openssl dgst \
  -sha256 \
  -verify path/to/public/key.pem \
  -signature signature.256 -
```

with `signature.256` being the base64 decoded output of the first command.

Any help would be appreciated!

**Comment by willm** [comment]
If it helps, the public/private keys were generated using this command 
`openssl genrsa -out my-key.pem 1024`

**Comment by willm** [comment]
I think If figured this out, the key needed to be generated with 2048 bits (mine only had 1024). Not sure if this is a bug, but it worked when I generated new keys using:

`openssl genrsa -out src/tests/acceptance/keys/2000key.pem 2048`

**Comment by briansmith** [comment]
> I think If figured this out, the key needed to be generated with 2048 bits (mine only had 1024). Not sure if this is a bug

You asked *ring* to require the key to be between 2048 and 8192 bits when you used `RSA_PKCS1_2048_8192_SHA256`.

I'm glad you figured this out!
