### ISSUE TITLE
RSASHA256 signature verifies with OpenSSL, but not with *ring*

### ISSUE THREAD

**Issue by bluejekyll** [briansmith/ring#1017]
I'm seeking advice on how to proceed debugging an issue.

In DNSSEC records are chained and signed with a private key, with the public key specified in a DNSKEY record. The signature is stored in an RRSIG record. These are chained from the root zone `.` to `www.example.com.` vis DS records. RRSIGs are used to sign both DS records as well as the standard records, like A or AAAA. In this manner `.` -> `com.` -> `example.com.` -> `www.example.com.`.

Right now, it appears that the chain is validating properly with the same algorithm `.` -> `com.` but fails on the validation of the RRSIG for the DS record that stores the `example.com.` DNSKEY. That is, it works for some of the chain, but one signature using the RSASHA256 algorithm.

OpenSSL currently doesn't have an issue with this same signature, but *ring* does. Any recommendations on how to proceed in debugging this issue? Associated issue: https://github.com/bluejekyll/trust-dns/pull/1145

**Comment by briansmith** [comment]
What is the public key, message, and signature?

**Comment by bluejekyll** [comment]
It's going to take me a little bit to get all of that collected. I need to build some tools to extract the bytes from the protocol. I've been planning to do this anyway, I'll try and grab all those details later today.

**Comment by Darkspirit** [comment]
Does it work if you change
`RSA_PKCS1_2048_8192_SHA256`
to `RSA_PKCS1_1024_8192_SHA256_FOR_LEGACY_USE_ONLY`?
https://github.com/bluejekyll/trust-dns/blob/16f4e862ef158972967ab738c86d567d2938d899/crates/proto/src/rr/dnssec/public_key.rs#L394
example.com uses RSA 1024 bit at some places: https://dnsviz.net/d/example.com/dnssec/

**Comment by bluejekyll** [comment]
Hm, do we have the logic incorrect in trust-dns then? I had thought that would be the RSASHA1 algorithm in DNSSEC.

**Comment by Darkspirit** [comment]
>  Algorithm::RSASHA1 => &signature::RSA_PKCS1_2048_8192_SHA1_FOR_LEGACY_USE_ONLY,

RSASHA1 currently requires 2048 bit RSA. Does it work if you change all of these to above 1024_8192?

**Comment by bluejekyll** [comment]
@Darkspirit you're 100% correct. I didn't realize that SHA256 was being used with 1024 bit keys...

Thanks for your help!
