### ISSUE TITLE
error: failed to run custom build command for ring v0.16.15

### ISSUE THREAD

**Issue by i-schuetz** [briansmith/ring#1023]
I'm trying to build Rust with an Android toolchain: 

```
...
   Compiling libsqlite3-sys v0.18.0
error: failed to run custom build command for `ring v0.16.15`
##[error]failed to run custom build command for `ring v0.16.15`
Caused by:
  process didn't exit successfully: `/Users/runner/work/app-backend-rust/app-backend-rust/target/debug/build/ring-bc978b739fd5fea5/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-linux-android")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-linux-android = Some("${ANDROID_NDK}/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android29-clang")
CFLAGS_x86_64-linux-android = None
CFLAGS_x86_64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
...
```

(Complete log [here](https://github.com/Co-Epi/app-backend-rust/runs/821546416), under the failed instrumentation tests).

I found [this](https://github.com/briansmith/ring/blob/2a3230cb6346a1249354a07395246a28b4904c5b/BUILDING.md#supported-toolchains)

> If you generate a standalone NDK toolchain in order to compile your project, the wrapper automatically passes flags to the actual compiler to define the __ANDROID_API__ macro. Otherwise, the macro __ANDROID_API__ must be defined with a value of at least 21 on 64-bit targets or 18 on 32-bit targets; e.g. export CFLAGS=-D__ANDROID_API__=21.

I think that I've to define the macro, but not sure where?

This is what I'm using to build: https://github.com/Co-Epi/app-backend-rust/blob/master/android/scripts/make_rust.sh#L19-L22

**Comment by pietro** [comment]
Your build errors are all similar to this:

> thread 'main' panicked at 'failed to execute ["${ANDROID_NDK}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android29-clang" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=aarch64-linux-android" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/Users/runner/work/app-backend-rust/app-backend-rust/target/aarch64-linux-android/debug/build/ring-a7801eac238c5d2f/out/aesv8-armx-linux64.o" "/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S"]: No such file or directory (os error 2)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:661:9

If I build an empty crate with ring 0.16.15 as the only dependency I get all the pregenerated files at: `~/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/`. Are you sure the cross-compilers got installed correctly and that their path is right? Does `"${ANDROID_NDK}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android29-clang"` and others exist?

**Comment by i-schuetz** [comment]
Indeed, this is not related with ring. Thanks!
