### ISSUE TITLE
Why P256 parameter different from recommended parameter

### ISSUE THREAD

**Issue by Pencil-Yao** [briansmith/ring#1029]
I found P256 curve's parameter a and b is different from the recommended [secp256r1 parameter](https://www.secg.org/SEC2-Ver-1.0.pdf), but ring's P256 could work well with standard P256 certificate.

I just wonder how can I compute the parameters when add other curve like sm2p256.

Appreciate any support.

**Comment by Pencil-Yao** [comment]
in ring P256:
```
a: fffffffc, 00000004, 00000000, 00000000, 00000003, ffffffff, ffffffff, fffffffc
b: dc30061d, 04874834, e5a220ab, f7212ed6, acf005cd, 78843090, d89cdf62, 29c4bddf
```
but recommend parameter:
```
a: ffffffff, 00000001, 00000000, 00000000, 00000000, ffffffff, ffffffff, fffffffc   // q - 3
b: 5ac635d8, aa3a93e7, b3ebbd55, 769886bc, 651d06b0, cc53b0f6, 3bce3c3e, 27d2604b
```

**Comment by briansmith** [comment]
The parameters are Montgomery-encoded.
