### ISSUE TITLE
ECDSA (x, y) to UnparsedPublicKey

### ISSUE THREAD

**Issue by pabloparada** [briansmith/ring#1030]
Hi, thank you for awesome work for Rust Community.

I have a public key `(x, y)` from ECDSA, both `x` and `y` are `Vec[u8]` how can I convert it into a `ring::signature::UnparsedPublicKey`?

Regards!

**Comment by briansmith** [comment]
The API documentation for `ring::signature` explains the serialization formats supported for the public keys, if you want to serialize them yourself. Otherwise, it sounds like this is a duplicate of #1601.
