### ISSUE TITLE
ld.lld: error: curve25519.c:(.debug_info+0x1B9F9): has non-ABS relocation R_386_GOTOFF against symbol 'd2' when cross compiling from x64 to i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by pluth** [briansmith/ring#1032]
I am cross compiling a binary that depends on ring from x86_64-unknown-linux-gnu to i686-unknown-linux-gnu with lld as the linker. The linking in release builds fails with the following message:

```
note: ld.lld: error: curve25519.c:(.debug_info+0x1B9F9): has non-ABS relocation R_386_GOTOFF against symbol 'd2'
          collect2: error: ld returned 1 exit status
```

How to reproduce:

1. Create a binary that depends on ring (and uses ed25519), for example:
```rust
use ring;

fn main() {
    let pkcs8 = vec![1, 2, 3];
    let key = ring::signature::Ed25519KeyPair::from_pkcs8(&pkcs8).unwrap();
}

```
2. Compile with `RUSTFLAGS="-Clink-arg=-fuse-ld=lld" cargo build --release --target i686-unknown-linux-gnu`. The failure does not happen in debug builds.

OS is Arch Linux, LLD is version 10.0.0, Rust toolchain is stable 1.44.1, (cc is gcc 10.1.0)
```
$ld.lld -v
LLD 10.0.0 (compatible with GNU linkers)
```

I don't really know what the error means, apologies, if this is an expected failure. Also, I don't depend on lld, just tried it out because it's supposed to be faster.

Thanks

**Comment by briansmith** [comment]
> cc is gcc 10.1.0

Is it the GCC you used an i686 (32-bit x86) cross-compiler or the x86_64-targetting compiler? When you use GCC, you have to use a version of GCC that targets the target platform.

**Comment by briansmith** [comment]
Closing due to lack of response. Will reopen if this is still reported to be an issue.
