### ISSUE TITLE
Error from computing public key

### ISSUE THREAD

**Issue by luben** [briansmith/ring#1035]
I recently started getting this type of panics:

```
panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified', <...> /registry/src/-c329f86fbe380342/rustls-0.16.0/src/suites.rs:73:22
```
That come from https://github.com/ctz/rustls/blob/main/rustls/src/suites.rs#L72-L76 (though previous version of it)

As we didn't update `rustls` so I reverted `ring` from v0.16.15 to 0.16.13 and it solved the problem for us.

Unfortunately the failure is too deep down the stack ( -> rusoto -> rustls -> ring) and it's not easy to reproduce, so I don't know what are the values for the group/algorithm. And due to the function pointer indirection I cannot pinpoint a change / exact code that returns `Err(Unspecified)`. Though I think this should not happen as the only external input is the algorithm itself.

**Comment by luben** [comment]
Hmm, actually this may not be caused by the `ring` update to v0.16.15 - it started showing errors also with 0.16.13 - I spoke too early.

What could be the reason for computing the public key to start failing?

**Comment by andrewtj** [comment]
Perhaps you could try using Cargo's patch functionality to add some logging to `rustls`.

**Comment by luben** [comment]
yes, that makes sense, at least we could get which is the algorithm used.

**Comment by briansmith** [comment]
@luben On which platform? Which C compiler version are you using? Are you using *ring* from crates.io or a vendored/patched version?

**Comment by luben** [comment]
Hi,

Here are the details:
Platform: Linux - 4.14 on Amazon Linux 2.
GCC-4.9, Rust-1.45.0,
For rustc it uses ` target-cpu=sandybridge` but I am not sure is it passed to GCC and what flags it results in.
ring/rustls are both without patches (from crates.io)

And here are some observations:
- the failures started after updating dependencies and also moving to rust-1.45. I could be some issue with it - I think they updated to LLVM-10 with it.
- It happens on multiple hosts (all of them r5.metal that use Xeon(R) Platinum 8259CL)
- it does not happen on similar instances with Xeon(R) Platinum 8275CL though the CPU is from the same generation: Cascade Lake.

Here are my plans:
- add more logging around the error (patch rustls). This will tell us at least the group/algorithm. I think also retrying to see if it fixes the issue.
- may be downgrade later to rust-1.44.1.

**Comment by luben** [comment]
I have been running for 4-5 days the last version of `ring` with patched `rustls` to just logs and retries failures to compute the public key from private key.  I have not seen any failure yet.

I am closing it as not-reproducible.

**Comment by luben** [comment]
Hmm spoke too early:

```
instance_id:i-0b403abfe170f2586 vm_id:61ce9e1a-c6d8-4fa5-8ab4-6bc6d8c3d898 2020-08-07T15:08:02.106Z WARN rustls::suites (/local/p4clients/pkgbuild-lHhUw/workspace/src/FluxPump/rustls/src/suites.rs:80) Failed to generate public key using se
cp256r1 (Algorithm { curve: P256 }) for private key EphemeralPrivateKey { algorithm: Algorithm { curve: P256 } } on attempt 0
instance_id:i-0b403abfe170f2586 vm_id:61ce9e1a-c6d8-4fa5-8ab4-6bc6d8c3d898 2020-08-07T15:08:02.106Z WARN rustls::suites (/local/p4clients/pkgbuild-lHhUw/workspace/src/FluxPump/rustls/src/suites.rs:80) Failed to generate public key using se
cp256r1 (Algorithm { curve: P256 }) for private key EphemeralPrivateKey { algorithm: Algorithm { curve: P256 } } on attempt 1
instance_id:i-0b403abfe170f2586 vm_id:61ce9e1a-c6d8-4fa5-8ab4-6bc6d8c3d898 2020-08-07T15:08:02.106Z WARN rustls::suites (/local/p4clients/pkgbuild-lHhUw/workspace/src/FluxPump/rustls/src/suites.rs:80) Failed to generate public key using se
cp256r1 (Algorithm { curve: P256 }) for private key EphemeralPrivateKey { algorithm: Algorithm { curve: P256 } } on attempt 2
```

the retry loop is quite simple:

```rust
    pub fn start_ecdhe(named_group: NamedGroup) -> Option<KeyExchange> {
        let alg = KeyExchange::named_group_to_ecdh_alg(named_group)?;
        let rng = ring::rand::SystemRandom::new();
        let ours = ring::agreement::EphemeralPrivateKey::generate(alg, &rng).unwrap();

        let pubkey = ours.compute_public_key().unwrap();
        let mut pubkey = None;
        let mut n = 0;
        let mut ours = ring::agreement::EphemeralPrivateKey::generate(alg, &rng).unwrap();
        while n < 3 {
            if let Ok(public) = ours.compute_public_key() {
                pubkey = Some(public);
                break;
            }
            log::warn!(
                "Failed to generate public key using {:?} ({:?}) for private key {:?} on attempt {}",
                named_group,
                alg,
                ours,
                n
            );
            ours = ring::agreement::EphemeralPrivateKey::generate(alg, &rng).unwrap();
            n += 1;
        }

        Some(KeyExchange {
            group: named_group,
            alg,
            privkey: ours,
            pubkey,
            pubkey: pubkey.unwrap(),
        })
    }
```

**Comment by briansmith** [comment]
@luben Which curve are you using when you experience the problem? X25519?

**Comment by luben** [comment]
@briansmith  curve: P256
