### ISSUE TITLE
Fails to compile on *BSD when irrelevant `dev_urandom_fallback` feature is not enabled, missing once_cell

### ISSUE THREAD

**Issue by Thomasdezeeuw** [briansmith/ring#1048]
I'm using ring with default-features disabled and the "std" feature enabled and get the following error on FreeBSD 12.1:

```log
error[E0433]: failed to resolve: use of undeclared type or module `once_cell`
   --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/src/rand.rs:366:13
    |
366 |         use once_cell::sync::Lazy;
    |             ^^^^^^^^^ use of undeclared type or module `once_cell`

error[E0412]: cannot find type `Lazy` in this scope
   --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/src/rand.rs:368:22
    |
368 |         static FILE: Lazy<Result<std::fs::File, std::io::Error>> =
    |                      ^^^^ not found in this scope
    |
help: consider importing this struct
    |
360 |     use core::lazy::Lazy;
    |

error[E0433]: failed to resolve: use of undeclared type or module `Lazy`
   --> /home/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/src/rand.rs:369:13
    |
369 |             Lazy::new(|| std::fs::File::open("/dev/urandom"));
    |             ^^^^ not found in this scope
    |
help: consider importing this struct
    |
360 |     use core::lazy::Lazy;
    |
```

Seems to be here: https://github.com/briansmith/ring/blob/0a5c2a78bedc851c9ec22555dae26c81da4032f3/src/rand.rs#L366-L369

Looking at the Cargo.toml: https://github.com/briansmith/ring/blob/0a5c2a78bedc851c9ec22555dae26c81da4032f3/Cargo.toml#L308

It seems that the "dev_urandom_fallback" feature is effectively required on FreeBSD as it fixes the issue. What would be the best way to fix it? Always make once_cell required on FreeBSD? Or perhaps (longer term) replace the module with the getrandom crate?

**Comment by briansmith** [comment]
Thanks for the bug report. Please test PR #1119 and let me know if it works for you.
