### ISSUE TITLE
Support AES encryption without a tag.

### ISSUE THREAD

**Issue by voidc** [briansmith/ring#1062]
I use ring for a project which uses layered encryption (similar to the onion protocol). Because each encryption layer requires its own tag, the total message size increases with each layer. This conflicts with the requirement of a fixed message size. I solved this problem by patching ring and adding a `open_within_no_tag` method which skips the verification of the tag. ([commit](https://github.com/voidc/ring/commit/2d0615c9830f8b32b82a1db382d7f4ed0deb37bc)) I am aware that this hack is far from ideal, and would appreciate suggestions on how to better solve this problem.

**Comment by briansmith** [comment]
No plans to expose an AES implementation without a specific mode.
