### ISSUE TITLE
In-browser `GFp_ChaCha20` and `GFp_poly1305`

### ISSUE THREAD

**Issue by crackcomm** [briansmith/ring#1064]
Hello, I'm trying to create a wasm package for [snow](https://github.com/mcginty/snow/), noise protocol implementation.

I stumbled upon a problem, it seems those functions are linked dynamically and are not compiled into wasm:

* `GFp_ChaCha20_ctr32`
* `GFp_poly1305_init_asm`
* `GFp_poly1305_blocks`
* `GFp_poly1305_emit`

Is there a (known) way to polyfill those functions in the browser?

**Comment by briansmith** [comment]
We'll add a Rust implementation of ChaCha20 and Poly1305 or as a last resort, fall back to the BoringSSL C implementations for wasm32.

**Comment by crackcomm** [comment]
It makes sense, thanks.
