### ISSUE TITLE
Different ring::hmac::sign results

### ISSUE THREAD

**Issue by glennpierce** [briansmith/ring#1078]
Hi
I am having trouble getting the same result for a oneshot hmac sign call against other code.

I have some simple python code like

```
import hashlib
import hmac
import base64
message = bytes('Client Key', 'utf-8')
secret = bytes('524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7', 'utf-8')

signature = hmac.new(secret, message, digestmod=hashlib.sha256).digest()
print(signature.hex())
```

This produces

6f68ff8007f4d55adb9bde002174df27a73c28c546ca17d0d7128612705e6ae4

I believe this is correct as I double checked it at
https://www.freeformatter.com/hmac-generator.html#ad-output

Now I am testing this same thing using ring like below

```
let expected_hex = "524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7";
let key_value: Vec<u8> = ring::test::from_hex(expected_hex).unwrap();

println!("salted_password hex: {:X?}", &key_value);

let key: ring::hmac::Key = ring::hmac::Key::new(ring::hmac::HMAC_SHA256, key_value.as_ref());
let signed_client_key = ring::hmac::sign(&key, "Client Key".as_bytes());

println!("signed_client_key: {:X?}", signed_client_key);
```

This produces
signed_client_key: Tag(SHA256:11b407ef4f01534a138a8599545dc3c943535dac95477d7f1334fec85408197c)

Any idea why the difference ?

Thanks

**Comment by ctz** [comment]
> secret = bytes('524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7', 'utf-8')

secret is "524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7"

> let expected_hex = "524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7";
> let key_value: Vec<u8> = ring::test::from_hex(expected_hex).unwrap();

key_value is b'RL\x82CV\x01\xf9\x97\x01\x93\x9a.\xd2\xe1\x87m\xdfhuin)\xcf\xc4 \x8f#\xa0\xd5!\xa0\xa7'

**Comment by glennpierce** [comment]
Yep that works. 
Make sense 
Thanks

**Comment by briansmith** [comment]
@glennpierce If I understand correctly, this was a bug in the python program, and not in *ring*, correct? I'm closing this under that understand. PLMK if I'm wrong.
