### ISSUE TITLE
semver incompatible change in 0.16.16

### ISSUE THREAD

**Issue by Xiphoseer** [briansmith/ring#1107]
Hey,

I'm trying to use `firestore-db-and-auth`, which uses `biscuit="0.4"` which fails to compile because the 0.4.x series uses
the removed public `KeyRejected::description_` method in `ring` for some reason. While it seems like that method was never intended to be used directly, (and `biscuit` 0.5 doesn't do that anymore), this is technically a semver-breaking change in `ring` because a public API was removed on a minor version without any kind of deprecation notice.

Would you be willing to release a 0.16.17 that just reverts f06811a150fcded1555911678bbca6dcb5440cda to fix these versions of biscuit and whatever else is using `description_` instead of `Display`? I can create a PR for that if you want.

Given that 0.16.16 was just released today and 0.17.x is in preparation, I'm guessing that this change was supposed to land in 0.17 and not affect the compilation of other projects.

(In case anyone need this, the simple workaround is to add `ring = "= 0.16.15"` somewhere in your dependencies)

**Comment by briansmith** [comment]
Yes, I will do so.

**Comment by briansmith** [comment]
This fix in PR #1108 landed. I'm going to keep this open until the release is published.

**Comment by fbucek** [comment]
I have problem with building `sqlx` for arm with `ring` dependency.
After updating to `version 0.16.16` it gives error when linking `ring` library. `unexpected reloc type 0x03`
More here: https://github.com/launchbadge/sqlx/issues/830

Could this be related? 

I have also solved issue reverting to `0.16.15`

**Comment by briansmith** [comment]
Fixed in 0.16.17, which I just published on crates.io

**Comment by Xiphoseer** [comment]
Can confirm, that solved the compilation error, thank you very much! :tada:
