### ISSUE TITLE
Avoid use of `#[should_panic]` tests

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1115]
In many situations `#[should_panic]` tests don't work:

* When abort-on-panic is used, which is required for some targets.
* When the runtime environment doesn't support panics correctly, e.g. ARMv7 target running under QEMU; see https://github.com/rust-lang/rust/issues/74820.

It would be better to get the test suite running successfully on these targets.

Suggestions:

* At least some of the tests can probably be rewritten to avoid `#[should_panic]`. For example, I think we can probably rewrite all `#[should_panic]` tests of `ring::test` could probably be changed to avoid `#[should_panic]` by having the `ring::test` infrastructure return an error instead of panicking/asserting.

* In cases where we can't avoid panicking, we should name the tests `<whatever>_should_panic()`. Then we can use `cargo test -- --skip _should_panic` to skip these tests they wouldn't work.

**Comment by sejr** [comment]
@briansmith I'm interested in working on this. Seems like a good way to learn how the project is organized, and the current testing landscape.

**Comment by real-or-random** [comment]
Just found this by accident and wanted to leave a hint that there's in fact a `--exclude-should-panic` command line option `cargo test -- --exclude-should-panic`.

**Comment by briansmith** [comment]
> When the runtime environment doesn't support panics correctly, e.g. ARMv7 target running under QEMU; see libtest panics when running should_panic tests under QEMU armv7  rust-lang/rust#74820.

This second part doesn't seem to be an issue anymore based on the fact we're using QEMU successfully to run these tests, and have been for a while now.
