### ISSUE TITLE
Remove all code that supports AES-192

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#112]
See https://github.com/briansmith/ring/blob/c882c2c3ec837f14267991122dc20e6aba5700bc/crypto/aes/aes.c#L549-L551

and

https://github.com/briansmith/ring/blob/c882c2c3ec837f14267991122dc20e6aba5700bc/crypto/aes/aes.c#L549-L551

Also, I guess the assembly language code must have some bits that support 192-bit AES.

We don't need any of this since we don't (and don't plan to) expose AES-192.

**Comment by briansmith** [comment]
Done in fc99d3070ecce98d6487410a74ed53e6b4d47ebf.

**Comment by lawliet89** [comment]
@briansmith May I know the reasons behind not supporting AES-192? Just curious to know because I am working on a library to implement JSON Web Encryption in Rust and AES-192 is one of the algorithms in the standard.

**Comment by briansmith** [comment]
@lawliet89 

Basically, it was removed:
1. Because of lack of tests and review.
2. Because nobody is using it in the real world.
3. To discourage people from implementing it in higher-level things, because of (1) and (2)

Note that Chrome's WebCrypto API implementation also skips AES-192; see https://diafygi.github.io/webcrypto-examples/.

Regarding JOSE, I recommend that you don't try to implement everything in the spec. Checkboxes are pretty but it's better to have solid implementations of fewer primitives than to check all the boxes.

**Comment by lawliet89** [comment]
Thanks for your detailed reply.
