### ISSUE TITLE
AES_set_encrypt_key and variants return error codes, but they are ignored

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#113]
Look at https://github.com/briansmith/ring/blob/80400f5fdfb3765acd490801c66ddf30d3dc6378/crypto/cipher/e_aes.c#L152 and other instances where those functions are called. The return value is ignored. It seems like the functions will never fail if given valid inputs, so they should have their return types changed to `void`. 

However, some variants aren't so clear as to whether they can fail on valid inputs or not. For example, `asm_AES_set_encrypt_key`/`_armv4_AES_set_encrypt_key` have code to jump to `.Labrt`. Is this just the "verify inputs are not null" check? If so, that code can be removed.

Note that in BoringSSL, but not OpenSSL, it is assumed that input parameters are not NULL unless the function's documentation specifically states they may be NULL, and NULL checks on parameters are not done.

**Comment by ecstatic-morse** [comment]
I'd like to look into this.

The error conditions in the assembly are as follows.
- x86_64:
  - [null pointer checks](https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/crypto/fipsmodule/aes/asm/aes-x86_64.pl#L753)
  - [Ensure `bits` is 128 or 256](https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/crypto/fipsmodule/aes/asm/aes-x86_64.pl#L775)
