### ISSUE TITLE
Disallow compiling with old Visual Studio versions

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1136]
I cannot even figure out how to download older versions of Visual Studio 2017. Issue #1031 hints that there are codegen bugs in 2017-vintage versions of Visual Studio that *ring*. Previously we had to block some older versions of Visual Studio 2015; see this code in limbs.inl:

```
/* MSVC 2015 RC, when compiling for x86 with /Ox (at least), miscompiles
 * _addcarry_u32(c, 0, prod_hi, &x) like so:
 *
 *     add eax,esi ; The previous add that might have set the carry flag.
 *     xor esi,esi ; OOPS! Carry flag is now reset!
 *     mov dword ptr [edi-4],eax
 *     adc esi,dword ptr [prod_hi]
 *
 * We test with MSVC 2015 update 2, so make sure we're using a version at least
 * as new as that. */
```

It's probably time to do the same again.

**Comment by Geobert** [comment]
We're still using this version:
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3

There is a plan to upgrade, but it will not happen before mid 2021, best case scenario, but more probably in 2022…
