### ISSUE TITLE
S/MIME with ring?

### ISSUE THREAD

**Issue by jocutajar** [briansmith/ring#1149]
Hi team,

I'm looking for guidance to create an S/MIME encrypted and/or signed message with ring. I figured this involves PKCS7 and in openssl is done through PKCS7_encrypt + PKCS7_sign + SMIME_write_PKCS7. I can imagine the crypto work could be done using ring and I suspect the S/MIME formatting does not fit into ring. I have an [SO question](https://stackoverflow.com/questions/65145345/how-to-compose-a-s-mime-encrypted-message-in-rust/65147462#65147462) open for this topic. and some [sketch on playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=330cb9939b990dceff941c2a4a27d899). 

Idealy, streaming/async or per-partes so that the whole message doesn't have to fit into memory.

Thank you

**Comment by briansmith** [comment]
I am open to implementing enough building blocks to getting this working but no plans to implement all of PKCS#7 or S/MIME.
