### ISSUE TITLE
QUERY: Support for random access decryption

### ISSUE THREAD

**Issue by nheitz** [briansmith/ring#1166]
Apologies for cross linking, but I was uncertain of the best forum for this query:
https://users.rust-lang.org/t/random-access-decryption-ring-openssl-aes-gcm/53697

In short, is it possible to use ring to perform random access decryption combined with AES-GCM?  I realise this compromises authentication, but it is a very interesting use case for me.  If not with AES-GCM, is there another choice supported by ring that does allow such decryption?  I'e spent a few hours with ring to master some of the concepts, but I can't see how to provide a computer IV + offset to the decrypter.

**Comment by nheitz** [comment]
Ok....I've had a bit of a breakthrough.  Turns out you can decrypt an AES-GCM encrypted block in random access mode using AES-CTR, provided you can work out the right IV.  Through some luck and experimentation, it seems like appending 4 bytes (0002) to the nonce is the correct IV for block 1, then increments by one from there.  Is there any reason the counter starts at 2?  Is that convention...can it be determined  programmatically?  I am curious as to how safe it is to assume that it starts at 2.

**Comment by briansmith** [comment]
The way the counter works is explained in the AES-GCM specification from NIST.

Are you wanting to do AES with GCM authentication, but do the decryption in a "random access" way? If so, do you want all the ciphertext to be authenticated first, but left encrypted?

Or, are you trying to do unauthenticated AES, and trying to use *ring*'s AES-GCM API because that's the closest to unauthenticated AES you can get?

**Comment by nheitz** [comment]
> The way the counter works is explained in the AES-GCM specification from NIST.
Thank you...I think this is probably the ultimate answer to my question!

> Are you wanting to do AES with GCM authentication, but do the decryption in a "random access" way? If so, do you want all the ciphertext to be authenticated first, but left encrypted?

I'm not particularly wed to AES-GCM, but the random access decryption is a very strong use case for me.  Ring seemed to be the best regarded of the crypto frameworks for Rust I discovered, but it seems to me that it primarily offers authenticated encryption, hence my selection of AES-GCM as being something I had some familiarity with (I've done simple work with AES-GCM encryption and decryption in java, but never random access.)

> Or, are you trying to do unauthenticated AES, and trying to use ring's AES-GCM API because that's the closest to unauthenticated AES you can get?

I don't feel I have anywhere near the expertise to make that judgment...the ring API appealed to me, so I wanted to push at the edges. I'm not sure under what scenarios I would pick an AEAD algorithm vs another, like CFB, perhaps, but I'm sure there are plenty of best practices and opinions out there.  My next requirement is for the ability to start streaming from a random access point with the most efficiency I can manage.

Thank you very much again for your input.
