### ISSUE TITLE
Incomplete sentence in ring::signature documentation

### ISSUE THREAD

**Issue by frewsxcv** [briansmith/ring#121]
> Algorithms like split into "signing" and "verification" algorithms.

-- https://briansmith.org/rustdoc/ring/signature/index.html

I would fix it myself but I wasn't immediately sure what the original intention of the sentence is.

**Comment by briansmith** [comment]
Fixed in 04dda97d28cee81bc5a3147b9e559613718005a9, which was updated in 21c90736de62422b744e7c67cfab03454e8c0f4a. Thanks for the bug report.
