### ISSUE TITLE
Expose der_writer publicly?

### ISSUE THREAD

**Issue by leplatrem** [briansmith/ring#1217]
In order to verify NIST P-384 (secp384r1) signatures, I need to transform my signature sequence of 96 bytes into a DER so that the signature validation works.

In Python I do it this way:
```py
import base64
import ecdsa

from cryptography.hazmat.primitives.asymmetric import ec 
from cryptography.hazmat.primitives.asymmetric.utils import encode_dss_signature
from cryptography.hazmat.primitives.hashes import SHA384

...

signature_bytes = base64.urlsafe_b64decode(signature)
r, s = ecdsa.util.sigdecode_string(
    signature_bytes, order=ecdsa.curves.NIST384p.order
)
signature_dss = encode_dss_signature(r, s)

cert.public_key().verify(signature_dss, msg, ec.ECDSA(SHA384()))
```

With `ring` I could do something like that, if the `der_writer` would be public:

```rust
let signature_bytes = base64::decode_config(&signature, base64::URL_SAFE)?;

let r = &signature_bytes[0..signature_bytes.len() / 2];
let s = &signature_bytes[signature_bytes.len() / 2..];

let signature_der = der_writer::write_all(der::Tag::Sequence, &|output| {
    der_writer::write_positive_integer(output, &r);
    der_writer::write_positive_integer(output, &s);
});

public_key.verify(&msg.as_bytes(), &signature_der)
```

Is that something you would consider? I'd happy to contribute the necessary changes :) 

Thanks for the hard work! :clap:

**Comment by briansmith** [comment]
> In order to verify NIST P-384 (secp384r1) signatures, I need to transform my signature sequence of 96 bytes into a DER so that the signature validation works.

Check out https://docs.rs/ring/0.16.20/ring/signature/static.ECDSA_P384_SHA384_FIXED.html. You don't need to convert your fixed-format signature into ASN.1 if you use that API.

**Comment by briansmith** [comment]
See also https://docs.rs/ring/0.16.20/ring/signature/index.html#ecdsa__fixed-details-fixed-length-pkcs11-style-ecdsa-signatures:

> A P-256 signature will be 64 bytes long (two 32-byte components) and a P-384 signature will be 96 bytes long (two 48-byte components). This is the form of ECDSA signature used PKCS#11 and DNSSEC.

**Comment by leplatrem** [comment]
Oh, thank you! That worked like a charm :) 

...I could have sworn I had tried it during my first explorations but then gave up :(

Thanks for your support!
 (*closing*)
