### ISSUE TITLE
Feature request: Add a few public functions to KeyPair

### ISSUE THREAD

**Issue by gjvnq** [briansmith/ring#1219]
It would be useful to have the following methods on the `KeyPair` trait:

  * `fn public_key(&self) -> &Self::PublicKey` (already exists but is is private for some reason)
  * `fn pkcs8_export(&self) -> Vec<u8>`

And on `PublicKey`:

  * `fn keyhash(&self) -> Vec<u8>`

These functions would make it easier to work with JWTs (JSON Web Tokens).

**Comment by briansmith** [comment]
> * `fn public_key(&self) -> &Self::PublicKey` (already exists but is is private for some reason)

SGTM.

> fn pkcs8_export(&self) -> Vec<u8>

One of the design ideas in *ring* is that keys are not exportable, at least by default. That means that we prevent the extraction of the key material from a key. To have such a feature, we'd need to design something new that allows us to control whether a given key is exportable or not.

> fn keyhash(&self) -> Vec<u8>

It isn't clear what you'd want this to do.

I am 100% happy to consider all of these, but it would be better to do them individually. So, I'm going to close this issue in favor of the individual issues for each one. If there's not already an issue for each feature you're requesting, please file a new one with more details of what you want. Or, maybe it's better to just make PRs.
