### ISSUE TITLE
Run the tests on M1s

### ISSUE THREAD

**Issue by sayrer** [briansmith/ring#1245]
https://twitter.com/MacStadium/status/1380173634795417607

**Comment by briansmith** [comment]
> https://twitter.com/MacStadium/status/1380173634795417607

I don't qualify for most of these "free" offers because I (and pretty much every contributor) gets paid to work on *ring* so I don't even get past the first step of the application.

We should figure out what the best host is, regardless of price, and then figure out how to pay for it.

**Comment by sayrer** [comment]
I see. Probably AWS, then. They have M1 Mac minis on their roadmap, and Intel ones available now.

https://developer.apple.com/news/?id=swfemvx0

**Comment by briansmith** [comment]
Fixed by PR #1843.
