### ISSUE TITLE
Expand crypto primitive tests to more diverse inputs

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#127]
1. Expand the `in_prefix_len` part of the AEAD tests to test a wide variety of prefixes, e.g. 0-4096 bytes.
2. Expand the tests of various primitives to test every input length 0-16K or so.

This might make the tests slower. We may need to add a “slow_tests” feature to enable these slow tests.

**Comment by pyfisch** [comment]
There is the [`#[ignore]`](https://doc.rust-lang.org/book/testing.html#the-ignore-attribute) attribute to disable slow tests by default. To run them one must call `cargo test -- --ignored`.

**Comment by pyfisch** [comment]
I am working on this. The `pkbdf2_tests` are also relatively slow. But since they are they only tests for this function they should probably not be made optional.

**Comment by briansmith** [comment]
> The pkbdf2_tests are also relatively slow. But since they are they only tests for this function they should probably not be made optional.

We should investigate if we (I) introduced a performance regression somewhere. At least in --release builds, they used to finish in a tolerable amount of time on non-Windows platforms, IIRC. (Windows is slow because it doesn't have the ASM optimizations enabled yet.) Once we've verified/fixed any perf regression, if the tests are still slow, then we should reduce the iteration count. In fact, we should probably reduce the iteration count anyway because more iterations isn't really testing more code paths.

The `i_u_f` tests are another candidate for splitting into `slow` and `fast` and/or refactoring so that we get approximately the same test coverage, but faster. These tests are quite similar to the prefix length tests that you added.

**Comment by pyfisch** [comment]
`pkbdf2_tests` are no longer slow in release mode (on my Linux computer at least). I only saw the `i_u_f`tests when I enabled release mode. I did not expect that some tests will only run in one mode.
