### ISSUE TITLE
ed25519_verify_tests.txt missing from crates.io release

### ISSUE THREAD

**Issue by jgalenson** [briansmith/ring#1301]
The newest crates.io releases (0.16.20 and 0.17.0-alpha.10) are missing the file tests/ed25519_verify_tests.txt, which is used in tests/ed25519_tests.rs.  That file presumably needs to be added to the include field in Cargo.toml/

**Comment by briansmith** [comment]
I would be happy to take a PR for this to fix it if anybody cares.
