### ISSUE TITLE
Cannot compile for target 'armv7s-apple-ios'

### ISSUE THREAD

**Issue by vladimir-ea** [briansmith/ring#1312]
Hello,

I am trying to cross compile _ring 0.16.20_ on mac OS for the target 'armv7s-apple-ios', but compilations fails with the following error:

`  running "clang" "-O0" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=armv7s-apple-ios" "-arch" "armv7s" "-miphoneos-version-min=7.0" "-isysroot" "/Applications/Xcode_12.5.0_fb.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk" "-fembed-bitcode" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-c" "-o/Users/dimir/repos/ring/target/armv7s-apple-ios/debug/build/ring-2849ba17b45b5c3a/out/armv4-mont-ios32.o" "/Users/dimir/repos/ring/target/armv7s-apple-ios/debug/build/ring-2849ba17b45b5c3a/out/armv4-mont-ios32.S"
  /Users/dimir/repos/ring/target/armv7s-apple-ios/debug/build/ring-2849ba17b45b5c3a/out/armv4-mont-ios32.S:41:1: error: symbol '_GFp_armcap_P' can not be undefined in a subtraction expression
  .word _GFp_armcap_P-Lbn_mul_mont
  ^
`
Is this a known issue? or am I doing something wrong?

I noted some comments in older issues about no longer supporting these older platforms and letting them use 'the C version'. I would be happy to use a C version since this is not a performance critical app, but I am not sure what the version referred to is.

Any help greatly appreciated!
Thanks, Vlad.

**Comment by briansmith** [comment]
At one point we did support this platform but I guess I removed the support at some point. I don't know what would be involved in resurrecting it. Presumably it would be pretty straightforward to do using the strategy you suggest: Just use the fallback Rust/C implementations of everything. If somebody makes a PR and it doesn't complicate things then I'd accept it.

**Comment by vladimir-ea** [comment]
Thanks for the speedy response - when you say "the fallback Rust/C implementations of everything" what do you mean exactly? are those implementations part of _ring_ ?

**Comment by briansmith** [comment]
> Thanks for the speedy response - when you say "the fallback Rust/C implementations of everything" what do you mean exactly? are those implementations part of _ring_ ?

Yes.

Basically, wherever you see `target_arch = "arm"`, you would need to change it to `all(target_arch = "arm", not(target_os = "ios"))` or similar. Then things should "just work" after parts of #986 are merged.

**Comment by Absolucy** [comment]
Not OP, but I'm interested in `armv7[s]-apple-ios` support.

**Comment by briansmith** [comment]
I'm pretty sure we had this working when 32-bit iOS mattered and it probably still works.
