### ISSUE TITLE
"include/GFp/check.h:27:11: fatal error: 'assert.h' file not found" on M1 apple silicon computers

### ISSUE THREAD

**Issue by brainstorm** [briansmith/ring#1332]
Hello @briansmith,

I'm trying to cross-compile `ring` on an Apple Silicon M1 to deploy an AWS lambda (target is a `provided.al2` Amazon linux container that should generate a `x86_64-unknown-linux-gnu`), but I'm facing the following issue:

```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/private/var/folders/s8/0tz3dy0d1sbg1_cv0ylkx_m80000gn/T/tmpukcl2wae/target/release/build/ring-0c3d64667514526d/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("aarch64-apple-darwin")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/private/var/folders/s8/0tz3dy0d1sbg1_cv0ylkx_m80000gn/T/tmpukcl2wae/target/x86_64-unknown-linux-gnu/release/build/ring-1b5ef9a99e86a98a/out/aesni-x86_64-elf.o" "/Users/rvalls/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"
  /Users/rvalls/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesni-x86_64-elf.S:1181:19: error: unexpected token in '.section' directive
  .section .note.GNU-stack,"",@progbits
                    ^
  thread 'main' panicked at 'execution failed', /Users/rvalls/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here's a quick reproducer:

```shell
brew tap aws/tap
brew install aws-sam-cli
git clone https://github.com/umccr/s3-rust-noodles-bam && cd s3-rust-noodles-bam
sam build
```

**Comment by briansmith** [comment]
Usually you must set TARGET_CC and TARGET_AR, or equivalent, when cross-compiling. PTAL at .github/workflows/ci.yml and mk/cargo.sh in this repo to see how.

**Comment by briansmith** [comment]
@brainstorm Did the advice I give you above resolve this for you?

**Comment by brainstorm** [comment]
Thanks for the followup @briansmith! It did not resolve it yet because my usecase depends heavily on the SAM cli but I bet I'd work with regular docker containers (without the SAM tool wrapping)... I've been hitting some limitations there as xref'd on this issue above :/

The env vars you mentioned and pointed to in the CI and .mk are all triplets, right? What would you put in `CROSS_COMPILE`, btw? A triplet as well or just `True`?

**Comment by briansmith** [comment]
There are hoops that have to be jumped through to get a working C toolchain that targets Linux from a Mac host, especially for a `-gnu` target. Basically you need to get a x86_64 Linux sysroot and a C compiler and linker targeting that target, and then point TARGET_CC and TARGET_AR to the C compiler (`clang` or `gcc`, probably) and archiver (the `ar` next to that `clang` or `gcc`). Then it should "just work."

I know that setting up the sysroot is annoying and I'm hoping we can provide better support for this scenerio soon. I hope others that are already doing this can help with hints and/or scripts to help set up the sysroot for now.

**Comment by horizon0514** [comment]
try
```
brew install llvm
```

**Comment by truptimemoryai** [comment]
When I set my environment variable `export CC=/usr/bin/cc` the errors were resolved
I am on Mac OS, Ventura

**Comment by nmboavida** [comment]
> When I set my environment variable export CC=/usr/bin/cc the errors were resolved
> I am on Mac OS, Ventura

Thanks! This worked for me as well.

**Comment by briansmith** [comment]
Closing since this seems like it was resolved for people and because I build on an M2 all the time.
