### ISSUE TITLE
ring::rand::generate is UB on macOS and iOS

### ISSUE THREAD

**Issue by dtolnay** [briansmith/ring#1333]
In the following code we're taking the `kSecRandomDefault` symbol from Security Framework and interpreting it as `&'static SecRandomRef`.

https://github.com/briansmith/ring/blob/1bf024dacfeb38eef7400b7880f46af5620cab42/src/rand.rs#L374

https://github.com/briansmith/ring/blob/1bf024dacfeb38eef7400b7880f46af5620cab42/src/rand.rs#L390

According to https://developer.apple.com/documentation/security/ksecrandomdefault:

> **This constant is a synonym for NULL.**

Null is not a legal value for a value of type `&'static SecRandomRef`.

https://doc.rust-lang.org/reference/behavior-considered-undefined.html:

> Producing an invalid value, even in private fields and locals. "Producing" a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation. The following values are invalid (at their respective type): 
>
> - A reference or Box<T> that is dangling, unaligned, or points to an invalid value.
>
> ...
>
> A reference/pointer is "dangling" if it is null or not all of the bytes it points to are part of the same allocation

**Comment by briansmith** [comment]
Thanks for pointing this out. Please review PR #1334 where I try to fix this.
