### ISSUE TITLE
aarch64-unknown-linux-musl build doesn't respect linker option

### ISSUE THREAD

**Issue by yoroma64** [briansmith/ring#1342]
When building for target 'aarch64-unknown-linux-musl' use of linker 'aarch64-linux-musl-gcc' is forced which causes build to fail.
When I create a link with that name to 'aarch64-linux-gnu-gcc' which is installed on my system the build finishes with no errors.
I have specified linker 'aarch64-linux-gnu-gcc' for the target but the build still calls 'aarch64-linux-musl-gcc'.

**Comment by briansmith** [comment]
Please show me your command line.

IIRC, cc-rs has default compiler names it uses when you don't set TARGET_CC. Make sure you set TARGET_CC when cross-compiling. Look at mk/config.sh.

**Comment by yoroma64** [comment]
Thank you! Setting TARGET_CC solves this issue.
