### ISSUE TITLE
much more: undefined reference

### ISSUE THREAD

**Issue by zhangqiang-hf** [briansmith/ring#1352]
Dear sirs,
  when I build ring, it can cargo build pass! (My platform: MIPS64)
But, when I cargo test, much more undefined reference occurred. How can I resolve this issue on MIPS64 platform?

          5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests25p256_point_sum_mixed_test17h62e735f535c1cfb4E+0x3c): undefined reference to `GFp_nistz256_point_add_affine'
          /usr/bin/ld: 5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests25p256_point_sum_mixed_test17h62e735f535c1cfb4E+0x3c): undefined reference to `GFp_nistz256_point_add_affine'
          /usr/bin/ld: 5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests25p256_point_sum_mixed_test17h62e735f535c1cfb4E+0x40): undefined reference to `GFp_nistz256_point_add_affine'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/deps/ring-c784656873de3763.5fj0ld7qbh6f3jfx.rcgu.o: in function `ring::ec::suite_b::ops::tests::p256_point_double_test':
          5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests22p256_point_double_test17h69562c69dece8c63E+0x38): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: 5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests22p256_point_double_test17h69562c69dece8c63E+0x38): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: 5fj0ld7qbh6f3jfx:(.text._ZN4ring2ec7suite_b3ops5tests22p256_point_double_test17h69562c69dece8c63E+0x3c): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/deps/ring-c784656873de3763.luci6fn41s1z4ju.rcgu.o: in function `.LBB0_25':
          luci6fn41s1z4ju:(.text._ZN4ring4aead3aes3Key3new17h06b3b2dc187a4e2fE+0x1f8): undefined reference to `GFp_aes_hw_set_encrypt_key'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/deps/ring-c784656873de3763.luci6fn41s1z4ju.rcgu.o: in function `.LBB0_37':
          luci6fn41s1z4ju:(.text._ZN4ring4aead3aes3Key3new17h06b3b2dc187a4e2fE+0x29c): undefined reference to `GFp_aes_nohw_set_encrypt_key'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/deps/ring-c784656873de3763.luci6fn41s1z4ju.rcgu.o: in function `没有符号':
          luci6fn41s1z4ju:(.text._ZN4ring4aead3aes3Key13encrypt_block17h2941219b51da32c5E+0x58): undefined reference to `GFp_aes_nohw_encrypt'
          /usr/bin/ld: luci6fn41s1z4ju:(.text._ZN4ring4aead3aes3Key13encrypt_block17h2941219b51da32c5E+0x6c): undefined reference to `GFp_aes_hw_encrypt'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/deps/ring-c784656873de3763.luci6fn41s1z4ju.rcgu.o: in function `.LBB3_27':
          luci6fn41s1z4ju:(.text._ZN4ring4aead3aes3Key20ctr32_encrypt_blocks17hc5e64c48d77ecaa8E+0x3c4): undefined reference to `GFp_aes_hw_ctr32_encrypt_blocks'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM105':
          (.text.elem_mul_mont+0x28): undefined reference to `GFp_nistz256_mul_mont'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM108':
          (.text.elem_sqr_mont+0x20): undefined reference to `GFp_nistz256_sqr_mont'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM142':
          (.text.GFp_nistz256_point_add+0x1cc): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM186':
          (.text.GFp_nistz256_point_mul+0xbc): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM192':
          (.text.GFp_nistz256_point_mul+0xf8): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM195':
          (.text.GFp_nistz256_point_mul+0x114): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM198':
          (.text.GFp_nistz256_point_mul+0x130): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o):(.text.GFp_nistz256_point_mul+0x14c): more undefined references to `GFp_nistz256_point_double' follow
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM259':
          (.text.GFp_nistz256_point_mul+0x3f4): undefined reference to `GFp_nistz256_neg'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM263':
          (.text.GFp_nistz256_point_mul+0x44c): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM264':
          (.text.GFp_nistz256_point_mul+0x458): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM265':
          (.text.GFp_nistz256_point_mul+0x464): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM266':
          (.text.GFp_nistz256_point_mul+0x470): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM267':
          (.text.GFp_nistz256_point_mul+0x47c): undefined reference to `GFp_nistz256_point_double'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM277':
          (.text.GFp_nistz256_point_mul+0x518): undefined reference to `GFp_nistz256_neg'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM286':
          (.text.select_precomputed+0x84): undefined reference to `GFp_nistz256_neg'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(ecp_nistz256.o): in function `.LM320':
          (.text.GFp_nistz256_point_mul_base+0x1c8): undefined reference to `GFp_nistz256_point_add_affine'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(gfp_p256.o): in function `.LM68':
          (.text.GFp_p256_scalar_mul_mont+0x3c): undefined reference to `GFp_bn_mul_mont'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(gfp_p384.o): in function `.LM168':
          (.text.elem_mul_mont+0x3c): undefined reference to `GFp_bn_mul_mont'
          /usr/bin/ld: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/target/debug/build/ring-12b266038c72c39e/out/libring-core.a(gfp_p384.o): in function `.LM206':
          (.text.GFp_p384_scalar_mul_mont+0x3c): undefined reference to `GFp_bn_mul_mont'
          collect2: error: ld returned 1 exit status

SO,how can I resolve this issue on MIPS64 platform? Can I disable this asm code?

**Comment by briansmith** [comment]
There is an existing issue tracking MIPS support. Please find it and subscribe to it.
