### ISSUE TITLE
Replace `ring::polyfill::fill_from_slice` with use of `<[T]>::clone_from_slice()`

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#136]
See http://blog.rust-lang.org/2016/03/02/Rust-1.7.html. `<[T]>::clone_from_slice()` was stabilized in Rust 1.7, which is now the minimum supported version in *ring*.

Note that `clone_from_slice` may not actually get optimized as well as `fill_from_slice` does. If that is found to be the case, then we'll have to wait for https://github.com/rust-lang/rust/issues/31755 to be resolved.

**Comment by briansmith** [comment]
Thanks! Landed in 7cdaeebfe1c35ada413c9a477d33c03d2109fd79.

**Comment by Ms2ger** [comment]
Actually landed in 43af354271857d9c034862de94e95a8b4f8f28df.

**Comment by briansmith** [comment]
I am going to revert this. Although it didn't seem to affect crypto_bench numbers, it did negatively affect the amount of time Travis CI debug builds take and now some of them are timing out:
https://travis-ci.org/briansmith/ring/builds/114456084.

Looks like we'll have to wait for `copy_from_slice` to become stable. The *ring* issue for switching to `copy_from_slice` is https://github.com/briansmith/ring/issues/141.

Thanks for the patch though! Sorry I didn't notice this before.
