### ISSUE TITLE
Cross Compiling from Linux to Windows Creates No such file or directory error

### ISSUE THREAD

**Issue by Microwave22** [briansmith/ring#1362]
When I try to compile a program that has the ring dependency on version 0.16.20, on target x86_64-pc-windows-msvc I end up with a build error that shows this 

running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Od" "/RTCsu" "-DNDEBUG" "-c" "/Fo/home/freedom/Projects/Project_name/target/x86_64-pc-windows-msvc/debug/build/ring-7be2588c2d2dbe98/out/aes_nohw.obj" "crypto/fipsmodule/aes/aes_nohw.c"
  cc: error: /GS: No such file or directory
  cc: error: /Gy: No such file or directory
  cc: error: /EHsc: No such file or directory
  cc: error: /GR-: No such file or directory
  cc: error: /Zc:wchar_t: No such file or directory
  cc: error: /Zc:forScope: No such file or directory
  cc: error: /Zc:inline: No such file or directory
  cc: error: /Zc:rvalueCast: No such file or directory
  cc: error: /sdl: No such file or directory
  cc: error: /Wall: No such file or directory
  cc: error: /wd4127: No such file or directory
  cc: error: /wd4464: No such file or directory
  cc: error: /wd4514: No such file or directory
  cc: error: /wd4710: No such file or directory
  cc: error: /wd4711: No such file or directory
  cc: error: /wd4820: No such file or directory
  cc: error: /wd5045: No such file or directory
  cc: error: /Od: No such file or directory
  cc: error: /RTCsu: No such file or directory
  cc: error: /Fo/home/freedom/Projects/Project_name/target/x86_64-pc-windows-msvc/debug/build/ring-7be2588c2d2dbe98/out/aes_nohw.obj: No such file or directory
  thread 'main' panicked at 'execution failed', /home/freedom/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9

**Comment by briansmith** [comment]
That's because it's passing MSVC-style command line arguments. In the latest unreleased change in the `main` branch, we have support for compilation with clang and clang-cl, at least. Hoping to do a release soon with those changes.
