### ISSUE TITLE
No check for DOCS_RS

### ISSUE THREAD

**Issue by MrElectrify** [briansmith/ring#1379]
Hello,
Cross-compiling on docs.rs for windows-gnu or windows-msvc fails, because the environment does not have those compilers and thus, invocation fails. Are there plans to check for `DOCS_RS` and avoid building C/assembly? Is there a reason this cannot be done? I cannot document my windows-specific crate that uses `rustls` because of this.
Thanks

**Comment by briansmith** [comment]
> Cross-compiling on docs.rs for windows-gnu or windows-msvc fails, because the environment does not have those compilers and thus, invocation fails.

AFAICT, *ring*'s documentation is the same regardless of the target. Can we just tell docs.rs this and then have it skip all the cross-compiling?

**Comment by MrElectrify** [comment]
> 
> 
> > Cross-compiling on docs.rs for windows-gnu or windows-msvc fails, because the environment does not have those compilers and thus, invocation fails.
> 
> AFAICT, _ring_'s documentation is the same regardless of the target. Can we just tell docs.rs this and then have it skip all the cross-compiling?

I do believe so. I was able to successfully produce documentation in an environment lacking a C compiler by defining `RING_CORE_PREFIX` in main, then checking for the `DOCS_RS` environment variable and returning if it exists. You may want to handle this differently than I have, however I created a PR [here](https://github.com/briansmith/ring/pull/1381) if you would like to take a look.

**Comment by briansmith** [comment]
> Cross-compiling on docs.rs for windows-gnu or windows-msvc fails, because the environment does not have those compilers and thus, invocation fails.

In the upcoming release, on the main branch, you will be able to use clang or clang-cl instead of MSVC, and so it should "just work", or pretty close, as long as you specify `TARGET_CC=clang` or similar. If that doesn't work, I'd consider it a bug.

**Comment by briansmith** [comment]
docs.rs seems to be working just fine.
