### ISSUE TITLE
Implemengt NoPanicSlice in terms of non-panicing slicing in when it is available in Rust's standard library

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#138]
See https://github.com/rust-lang/rfcs/pull/1325.

`no_panic::NoPanicSlice::subslice`, and maybe other things, should be rewritten when the new Rust functionality is available.

**Comment by briansmith** [comment]
It's now https://github.com/rust-lang/rfcs/pull/1679.

**Comment by briansmith** [comment]
Now https://github.com/rust-lang/rust/issues/35729

**Comment by sfackler** [comment]
Implementation: rust-lang/rust#36340

**Comment by briansmith** [comment]
It's not clear from reading #36340 whether it is possible to use the new feature on Stable rust without the `SliceIndex` trait being stable.

**Comment by briansmith** [comment]
This issue is moot now. First, the code was split out into the `untrusted` crate, and then we did do this in `untrusted`.
