### ISSUE TITLE
OPENSSL_cleanse should use memset_s

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#14]
WE should juse use `memset_s`. If necessary, we can supply a default implementation of `memset_s` for platforms that don't provide it, if any. Alternatively, we can drop support for older versions of compilers that don't supply it.

```
void OPENSSL_cleanse(void *ptr, size_t len) {
#if defined(OPENSSL_WINDOWS)
	SecureZeroMemory(ptr, len);
#else
	memset(ptr, 0, len);

#if !defined(OPENSSL_NO_ASM)
  /* As best as we can tell, this is sufficient to break any optimisations that
     might try to eliminate "superfluous" memsets. If there's an easy way to
     detect memset_s, it would be better to use that. */
  __asm__ __volatile__("" : : "r"(ptr) : "memory");
#endif
#endif  /* !OPENSSL_NO_ASM */
}
```

**Comment by briansmith** [comment]
See https://github.com/pyca/cryptography/issues/7 and http://www.daemonology.net/blog/2014-09-05-erratum.html (especially the comments).

**Comment by briansmith** [comment]
In particular, let's get rid of the nasty __asm__.

**Comment by briansmith** [comment]
OpenSSL has some assembly language implementations we might be able to use. Also, Apple Clang (and GCC?) has memset_s.

See https://mta.openssl.org/pipermail/openssl-dev/2015-October/003264.html and that whole thread.

**Comment by briansmith** [comment]
Closed in favor of https://github.com/briansmith/ring-ffi/issues/3. See b76f52c03a667c2ac6793ff566b55ad060421759. Basically, we'll move these kinds of defenses into ring-ffi as much as possible.

**Comment by noloader** [comment]
> ... WE should juse use memset_s....

Sorry to poke around when not asked for...

You probably can't use `memset_s` to achieve your goals. I'm guessing your goals include wiping sensitive material from memory, portability across platforms and surviving optimization.

You can't use it because the Glibc folks refuse to provide it. Also see [Issue 17879: Library is missing memset_s](http://sourceware.org/bugzilla/show_bug.cgi?id=17879).

**Comment by briansmith** [comment]
Thanks for the comment, @noloader. I am aware that glibc doesn't provide it, but it is easy enough to add a polyfill in assembly language. Anyway, that's better discussed in https://github.com/briansmith/ring-ffi/issues/3 now.
