### ISSUE TITLE
[Question] - New Release

### ISSUE THREAD

**Issue by tiagolobocastro** [briansmith/ring#1416]
Not sure if this is not the correct way of asking this question, couldn't find any other channel for questions, apologies if I missed it somewhere.

The main branch has a few fixes for cross compiling for windows with clang.
May I ask if a new stable release in the works?

Thanks!

**Comment by briansmith** [comment]
I am expecting to do a new release on or before 2021-12-14.

**Comment by briansmith** [comment]
*ring* 0.17.0 was (finally) released.
