### ISSUE TITLE
Remove last usage of <stdarg> and vararg stuff

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#143]
Right now, AFAICT, the only use of #include <stdarg.h> is in file_test.cc (testing code), and it looks like it would be easy to switch to a non-vararg function.

When we do that, we should add documentation to STYLE.md that the definition or use of vararg functions is disallowed.

Besides making static analysis easier, this would also make a good dent in the the minimum required C/C++ standard library subset.

**Comment by briansmith** [comment]
See http://blog.regehr.org/archives/1303.

**Comment by frewsxcv** [comment]
What do you propose we replace the [last vararg usage](https://github.com/briansmith/ring/blob/c5fc35ff04ca95fef064cbd615c4db95cb2b03b0/crypto/test/file_test.cc#L132) with?

**Comment by briansmith** [comment]
I don't really care. It's in test code. IIRC, there's never more than one extra arg passed to that function, so it can probably be changed to just take another arg as std::string& or const char* or something. And/or we can overload the function with a version that takes a number and a version that takes a string. Or, whatever.

**Comment by briansmith** [comment]
Fixed with #306.
