### ISSUE TITLE
Build fails for thumbv7em-none-eabihf target

### ISSUE THREAD

**Issue by rod-chapman** [briansmith/ring#1445]
I am trying to build ring for a Nordic DevBoard - specifically a Nordic NRF52840-DK board.

I have the "target" for Rust compilation set to "thumbv7em-none-eabihf", and this works fine.

I have declared a dependency on "ring" with default-features=false, since my target is a no_std application.

I have clang v13.0 installed for that target, and I have set TARGET_CC=clang and TARGET_AR=llvm-ar

But... build fails with:
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/rchapman/prog/S169RUST/sandpit/asn1/target/crgen/target/debug/build/ring-509e7e4d41c7469b/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("thumbv7em-none-eabihf")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_thumbv7em-none-eabihf = None
  CC_thumbv7em_none_eabihf = None
  TARGET_CC = Some("clang")
  CFLAGS_thumbv7em-none-eabihf = None
  CFLAGS_thumbv7em_none_eabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  OPT_LEVEL = Some("0")
  TARGET = Some("thumbv7em-none-eabihf")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_thumbv7em-none-eabihf = None
  CC_thumbv7em_none_eabihf = None
  TARGET_CC = Some("clang")
  CFLAGS_thumbv7em-none-eabihf = None
  CFLAGS_thumbv7em_none_eabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")

  --- stderr
  running "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "--target=thumbv7em-none-eabihf" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-o/home/rchapman/prog/S169RUST/sandpit/asn1/target/crgen/target/thumbv7em-none-eabihf/debug/build/ring-f42e7d2634b622a3/out/aesv8-armx-linux32.o" "/home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux32.S"
  running "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "--target=thumbv7em-none-eabihf" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-o/home/rchapman/prog/S169RUST/sandpit/asn1/target/crgen/target/thumbv7em-none-eabihf/debug/build/ring-f42e7d2634b622a3/out/ghashv8-armx-linux32.o" "/home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-linux32.S"
  /home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-linux32.S:17:1: error: target does not support ARM mode
  .code 32
  ^
  /home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-linux32.S:140:2: error: predicated instructions must be in IT block
   moveq r12,#0 @ is it time to zero r12?
   ^
  /home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-linux32.S:166:2: error: predicated instructions must be in IT block
   movlo r12,#0 @ is it time to zero r12?
   ^
  /home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/ghashv8-armx-linux32.S:176:2: error: predicated instructions must be in IT block
   moveq r12,#0 @ is it time to zero r12?
   ^
  thread 'main' panicked at 'execution failed', /home/rchapman/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

Can anyone help please?

**Comment by briansmith** [comment]
@rod-chapman Could you please try *ring* 0.17.3? And/or did you find a solution?

**Comment by rod-chapman** [comment]
That was a long time ago! I since joined AWS and (ironically) work for AWS Crypto team ... so I think we can close this issue as "overtaken by events..." :-)

**Comment by briansmith** [comment]
OK. I won't keep the issue open. It is possible that this is fixed with the new `arm_arch.h` changes in 0.17. If not, somebody please comment here.
