### ISSUE TITLE
Improve RSA prime generation

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#145]
- Why aim for a 2^-80 error rate and not a 2^-128 error rate?
- Should we make extra effort to generate primes of a particular form? The ECM method appears to make the use of “safe” primes obsolete for RSA, but are there other forms?
- Should we really be using Miller-Rabin, or something else, or a combination of two?

```
/* number of Miller-Rabin iterations for an error rate  of less than 2^-80
 * for random 'b'-bit input, b >= 100 (taken from table 4.4 in the Handbook
 * of Applied Cryptography [Menezes, van Oorschot, Vanstone; CRC Press 1996];
 * original paper: Damgaard, Landrock, Pomerance: Average case error estimates
 * for the strong probable prime test. -- Math. Comp. 61 (1993) 177-194) */
#define BN_prime_checks_for_size(b) ((b) >= 1300 ?  2 : \
                                (b) >=  850 ?  3 : \
                                (b) >=  650 ?  4 : \
                                (b) >=  550 ?  5 : \
                                (b) >=  450 ?  6 : \
                                (b) >=  400 ?  7 : \
                                (b) >=  350 ?  8 : \
                                (b) >=  300 ?  9 : \
                                (b) >=  250 ? 12 : \
                                (b) >=  200 ? 15 : \
                                (b) >=  150 ? 18 : \
                                /* b >= 100 */ 27)
```

See:
- http://security.stackexchange.com/questions/73505/use-of-safe-prime-in-rsa-digital-signature-scheme
- https://codereview.appspot.com/253041/
- http://stackoverflow.com/questions/6325576/how-many-iterations-of-rabin-miller-should-i-use-for-cryptographic-safe-primes, where the answer seems to be 40 or 64.

Also consider this from [“Factoring RSA Moduli. Part II”](http://windowsontheory.org/2012/05/17/factoring-rsa-moduli-part-ii/):

> Can the certificates from the Zoo be partitioned into some meaningful classes? There is some clustering in their validity dates but not enough to have any explanatory value… Let’s test whether their prime factors are safe, i.e., have form {2p+1}, where {p} is a prime. Some of them are safe, but most are not… Their distribution mod 4 is split uniformly between 1 and 3… Their distribution mod 3… Hold on a sec, almost all of them (98.5% to be exact) equal to 2 mod 3! Let’s look at their distribution mod 5. We see an almost equal split between 2, 3, and 4, with less than .5% equal to 1! Similarly for 7, 11, 13, etc.—virtually none of the number from the Zoo is equal to 1 modulo a small prime.
> 
> [...]
> 
> Notice that the second step is intact: it will filter out numbers that are not equal to 1 modulo {3,5,\dots,17863}, which explains the peculiar distribution of the prime factors from the Zoo.
> 
> We want to emphasize that the property of “OpenSSL” prime numbers, i.e., not being equal to 1 modulo the first 2048 prime numbers, is not a security vulnerability. It is a fingerprint.

It's worth thinking about whether we want to preserve this fingerprint of OpenSSL or whether we should skip that filtering of small prime factors. Skipping it would presumably make things faster, but maybe not enough to matter.

**Comment by burdges** [comment]
Also worth following.  :)

**Comment by briansmith** [comment]
See http://cs.stackexchange.com/questions/23260/when-is-the-aks-primality-test-actually-faster-than-other-tests/23263#23263, and the whole thread. See also http://stackoverflow.com/questions/6305126/what-is-the-fastest-deterministic-primality-test-for-numbers-in-the-range-21024

**Comment by briansmith** [comment]
See https://github.com/golang/go/issues/13229#issuecomment-197981831

**Comment by briansmith** [comment]
See https://github.com/zcdziura/pumpkin.

**Comment by briansmith** [comment]
I think we need to implement elliptic curve primality proving, or equivalent primality-proving, as the final step of the prime generation.

**Comment by briansmith** [comment]
Closing this in favor of #219, since we removed the original code completely.
