### ISSUE TITLE
Failed to compile ring under nightly Rust (1.61.0, 9f4dc0b4d 2022-03-23)

### ISSUE THREAD

**Issue by zjp-CN** [briansmith/ring#1469]
Hi, after I `rustup update` today and `cargo clean` my project, I get the following issue:

```RUST
    Checking ring v0.16.20
error: no rules expected the token `aarch64_apple`
   --> /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/ring-0.16.20/src/cpu.rs:257:13
    |
165 |     macro_rules! features {
    |     --------------------- when calling this macro
...
257 |             aarch64_apple: true,
    |             ^^^^^^^^^^^^^ no rules expected this token in macro call

error[E0425]: cannot find value `AES` in module `cpu::arm`
   --> /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/ring-0.16.20/src/aead/aes.rs:381:65
    |
381 |         if cpu::intel::AES.available(cpu_features) || cpu::arm::AES.available(cpu_features) {
    |                                                                 ^^^ not found in `cpu::arm`
    |
help: consider importing this constant
    |
15  | use crate::cpu::intel::AES;
    |

error[E0425]: cannot find value `PMULL` in module `cpu::arm`
   --> /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/ring-0.16.20/src/aead/gcm.rs:315:26
    |
315 |             || cpu::arm::PMULL.available(cpu_features)
    |                          ^^^^^ not found in `cpu::arm`

error[E0425]: cannot find value `ARMCAP_STATIC` in this scope
   --> /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/ring-0.16.20/src/cpu.rs:235:41
    |
235 |             if self.mask == self.mask & ARMCAP_STATIC {
    |                                         ^^^^^^^^^^^^^ not found in this scope
```

This happens under the latest nightly Rust (1.61.0, 9f4dc0b4d 2022-03-23), and I'm not sure if it's ok to report here.

I don't use ring crate as a direct dependency in my project, and I always use nightly Rust.

When I switch to stable Rust, everything goes pretty well just like before rustup updates.

Here is the rustup info:

```
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.59.0 (9d1b2106e 2022-02-23)
  nightly-x86_64-unknown-linux-gnu updated - rustc 1.61.0-nightly (9f4dc0b4d 2022-03-23) (from rustc 1.61.0-nightly (6a7055661 2022-02-27))
```

Thank you.

**Comment by NateLing** [comment]
+1

**Comment by EGORAGANIN** [comment]
Actually for me

**Comment by Mr-Leshiy** [comment]
Also actual for me https://github.com/input-output-hk/jormungandr/pull/3712

**Comment by soulmachine** [comment]
Also happening to me https://github.com/crypto-crawler/crypto-crawler-rs/runs/5685232312?check_suite_focus=true

**Comment by bstrie** [comment]
Rust developers are aware of the regression and anticipate a fix will land soon: https://github.com/rust-lang/rust/issues/95267#issuecomment-1078979952

**Comment by briansmith** [comment]
Thanks for the bug report, and thanks for linking to the rust-lang/rust issue.

(https://github.com/rust-lang/rust/commit/996759434610a151c71476ab85305bfcf2d6d5e7) was committed, which should fix this in the next Rust Nigthly or the Nightly after that. I will leave this open until we've verified that.

**Comment by zjp-CN** [comment]
This issue is solved by https://github.com/rust-lang/rust/pull/95390, and ring works fine with the newest nightly Rust.
