### ISSUE TITLE
Eliminate the need for a C compiler when targeting wasm32-*

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1473]
The most common cross-compilation target seems to be wasm32-unknown-unknown and wasm32-wasi. Users have found needing to install a LLVM/clang toolchain that can target wasm32 to be too much of a burden. We should get rid of the requirement to have a C compiler when targeting wasm32-* targets. (Orthogonally, we're working on expanding the functionality that is available for wasm32-* targets, which means that eventually we should have all functionality available without needing a C compiler.)

**Comment by briansmith** [comment]
In particular, on macOS hosts, a year or two ago, we have found that Apple Clang wasn't able to target wasm32-* targets, so people had to install LLVM Clang instead. Then, people had trouble dealing with both Apple Clang and LLVM Clang being installed at the same time.

**Comment by chertov** [comment]
> we have found that Apple Clang wasn't able to target wasm32-* targets, so people had to install LLVM Clang instead.

Yes, but ```brew install llvm``` llvm works well! I don't have issues to use both original Apple and custom brew LLVM
https://github.com/briansmith/ring/issues/1483#issuecomment-1145159978

**Comment by briansmith** [comment]
Closing this since in general we're trying to get rid of C and not particularly just for wasm32.
