### ISSUE TITLE
Use the `getrandom` system call on Linux when it is available in CRYPTO_sysrand

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#148]
This should be faster than using /dev/urandom. Also, it would be better for sandboxed applications that want to block `open` and `read` syscalls completely.

This may obviate the need for the `hwrand`+ChaCha20 optimization and/or the /dev/urandom buffering. We should benchmark `getrandom` vs. the current `CRYPTO_sysrand` implementation vs. the `hwrand`+ChaCha20 optimization.

**Comment by drbo** [comment]
I doubt it will solve the speed issue unless the kernel algorithms have changed.  See my comment on #58 (tl;dr the kernel uses very slow algorithms).

**Comment by briansmith** [comment]
This is now https://github.com/briansmith/ring/pull/176. One issue is that Travis CI only natively supports Ubuntu 12.04 and Ubuntu 14.04, and the first Ubuntu with `getrandom` is Ubuntu 16.04. Apparently we could in theory use the Travis CI Docker support (see https://docs.travis-ci.com/user/docker/), but that seems way too complicated. For now I'm just going to punt on the Travis CI testing and do the testing locally instead.

**Comment by briansmith** [comment]
This was done a while back. See https://briansmith.org/rustdoc/ring/rand/struct.SystemRandom.html for the documentation.
