### ISSUE TITLE
tests fail with --no-default-features

### ISSUE THREAD

**Issue by plugwash** [briansmith/ring#1490]
While working on updating the ring package in Debian to 0.16.20 I discovered that the tests failed with --no-default-features, so I went through the code and fixed things (mostly making stuff conditional on the "alloc" feature) until they worked.

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/ring/debian/patches/fix-tests-no-default-features.patch

I also discovered that  test_signature_ed25519_verify failed due to a lack of test data, I had already disabled this test at the time I wrote the patch for --no-default-features, but looking at the code I suspect it also needs to be gated behind #[cfg(feature = "alloc")]

P.S. I couldn't seem to find any branch or tag in the git repository corresponding to the latest stable release on crates.io

**Comment by briansmith** [comment]
I think this is resolved in main now.
