### ISSUE TITLE
[feature request]Do you have plan to support "s390x-linux" target?

### ISSUE THREAD

**Issue by egg1234** [briansmith/ring#1494]
Hi,

Do you have plan to support "s390x-linux" target?

Because some downstream rust project like TUIC"https://github.com/EAimTY/tuic" depends on [rustls](https://github.com/rustls/rustls), which uses [ring](https://github.com/briansmith/ring) for implementing the cryptography in TLS.
So ring project's target would limit some rust project's target.

Thank you!

**Comment by uweigand** [comment]
I've submitted PR https://github.com/briansmith/ring/pull/1297, but that has been pending review for quite a while ...

**Comment by briansmith** [comment]
I'm closing this as a duplicate of #1555 since completing that generalized work should get all s390x targets working.
