### ISSUE TITLE
ring build script is not compatible with solana/cargo-build-bpf

### ISSUE THREAD

**Issue by monkeytomp** [briansmith/ring#1505]
it seems `ring-v16.20` is not compatible with cargo-build-bpf (which is used to compile solana programs)

it fails on build script as the solana os/arch passed is not in `ASM_TARGETS`.

my mac host/arch:
```
Darwin 
Darwin Kernel Version 21.5.0
arm64
```
BPF SDK data
```
BPF SDK: ~/.local/share/solana/install/releases/beta-447c9d4025294937ae125f609c5d8046f7371e92/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
```

**Comment by briansmith** [comment]
Hi, this might work now with *ring* 0.17. I don't think we need an issue to track it since really we need a PR.
