### ISSUE TITLE
EcdsaKeyPair::sign is deprecated without explicit replacement

### ISSUE THREAD

**Issue by boxdot** [briansmith/ring#1510]
The method [EcdsaKeyPair::sign](https://docs.rs/ring/0.16.20/ring/signature/struct.EcdsaKeyPair.html#method.sign) https://github.com/briansmith/ring/blob/7a443f9bb2fb5afabe175bcb89c520ba96558242/src/ec/suite_b/ecdsa/signing.rs#L171 is marked as deprecated. What should be used instead?

**Comment by briansmith** [comment]
Thanks for the bug report. PR #1510 fixes this by removing the "Deprecated." from the documentation.
