### ISSUE TITLE
No s390 support ?

### ISSUE THREAD

**Issue by eaibmz** [briansmith/ring#1511]
Hi,

s390 architecture is not supported yet, right ?

Regards
Alex

**Comment by ecnelises** [comment]
If you mean s390 on Linux, there's https://github.com/briansmith/ring/pull/1297 in review (but seems no recent response).

**Comment by eaibmz** [comment]
> If you mean s390 on Linux, there's #1297 in review (but seems no recent response).

Thank you, i missed that.

**Comment by briansmith** [comment]
I'm going to close this as a duplicate of #1555, which is about making a generalized effort to support all big-endian architectures with a single codepath.
