### ISSUE TITLE
Is this project actively maintained at the moment?

### ISSUE THREAD

**Issue by Antiarchitect** [briansmith/ring#1516]
I see no even a patch releases in about 9 months. Many dependenceis (e.g. `spin`) are very old. Is the project maintained well?

**Comment by AidanConnelly** [comment]
Adding to this, [there's PRs](https://github.com/briansmith/ring/issues/1494) that are stuck in limbo as it stands:

**Comment by djc** [comment]
The maintainer hasn't had any GitHub activity in 5 months. https://www.crowdsupply.com/sutajio-kosagi/precursor/updates/bringing-up-tls-on-precursor talks about a fork they did to get some functionality they wanted. Apparently 1Password also maintains forks for both ring 0.16 and 0.17.

**Comment by briansmith** [comment]
> Is this project actively maintained at the moment?

Yes. I took a break but I'm back as of yesterday.
