### ISSUE TITLE
0.16.21 release

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1551]
We should do a 0.16.21 release that enables aarch64-pc-windows-msvc to work. I created a "b/0.16" branch to accept PRs for this.

Unfortunately there were a lot of changes between 0.16.20 and the main branch before the aarch64-pc-windows-msvc support was added, and also there were multiple PRs involved in adding the aarch64-pc-windows-msvc support. @svenpaulsen  @awakecoding seem to know exactly what needs to be done already so maybe they can tell us, or perhaps submit a PR against the new b/0.16 branch? If we can get such a PR then I will do the release soon.

I do have an aarch64-pc-windows-msvc target (Surface Pro X) to test this on.

/cc @svenpaulsen  @awakecoding @Alovchin91

**Comment by briansmith** [comment]
Of course, CI also needs several changes to pass on this branch. I will work on those.

**Comment by svenpaulsen** [comment]
PR opened here #1554. Happy to help!

**Comment by ArchangelX360** [comment]
Hello 👋🏼! Any ETA on that front?

**Comment by Alovchin91** [comment]
Just a heads up: support for Windows 11 on Parallels on Apple Silicon Macs is now official:

* https://www.theverge.com/2023/2/16/23602718/microsoft-windows-11-apple-mac-m1-m2-support-parallels-virtual-machines

* https://support.microsoft.com/en-us/windows/options-for-using-windows-11-with-mac-computers-with-apple-m1-and-m2-chips-cd15fd62-9b34-4b78-b0bc-121baa3c568c

**Comment by carlocorradini** [comment]
Any update? 😰

**Comment by zh-jq-b** [comment]
Could this https://github.com/briansmith/ring/pull/1531 and https://github.com/briansmith/ring/pull/1595 be backported to 0.16 branch?  So we can remove the dependency on winapi.

**Comment by ifsheldon** [comment]
since RISC-V support was merged recently, I guess a new release is needed for that?

**Comment by briansmith** [comment]
0.17.0 was released. It seems like most projects are going to be able to update to 0.17.0 without any significant effort, so I'm not intending to do this.
