### ISSUE TITLE
unable to cross-compile with ring v0.16.20 on x86_64 Linux host machine

### ISSUE THREAD

**Issue by zhangbtciab** [briansmith/ring#1559]
cargo +nightly build -Z build-std -Z build-std-features=llvm-libunwind --target=aarch64-unknown-linux-musl
   Compiling rustc-std-workspace-alloc v1.99.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)
   Compiling panic_abort v0.0.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort)
   Compiling hashbrown v0.12.3
   Compiling std_detect v0.1.5 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/stdarch/crates/std_detect)
   Compiling panic_unwind v0.0.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_unwind)
   Compiling ring v0.16.20 (/root/test/ring-b-0.16)
error: failed to run custom build command for `ring v0.16.20 (/root/test/ring-b-0.16)`

Caused by:
  process didn't exit successfully: `/root/test/ring-b-0.16/target/debug/build/ring-2ba8584cd8320845/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"/root/test/ring-b-0.16/pregenerated/aesv8-armx-linux64.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:769:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tpetazzoni** [comment]
I confirm we have the same issue here: http://autobuild.buildroot.net/results/90c3523fae07907889dde3750d6b853b6c8ae7c4/build-end.log

**Comment by zhangbtciab** [comment]
> I confirm we have the same issue here: http://autobuild.buildroot.net/results/90c3523fae07907889dde3750d6b853b6c8ae7c4/build-end.log

I have solve my problem . You can download a complier for target .  this is url  https://musl.cc/

**Comment by tpetazzoni** [comment]
Could you clarify? In the context of Buildroot, we already have a cross-compiler in place.

**Comment by adamdama** [comment]
@tpetazzoni I also faced this issue but have resolved it by setting the following env variables:
```
TARGET=aarch64-unknown-linux-musl
export TARGET_CC=${TARGET}-gcc
export TARGET_AR=${TARGET}-ar 
```

I am compiling from Mac to Linux using the toolchains provided here: https://github.com/messense/homebrew-macos-cross-toolchains

My builds failed with the exact same error you had but disappeared once I set the env vars above. I got the idea from the instructions found here: https://github.com/briansmith/ring/blob/main/BUILDING.md. 

Not sure if it will, but I hope this helps.

**Comment by Saruniks** [comment]
Can't compile `0.16.20` on target `x86_64-unknown-linux-musl` (for aws lambda use)

**Comment by Dalot** [comment]
I also can't compile `0.16.20` from linux to `x86_64-apple-darwin`

**Comment by jarvjani** [comment]
> @tpetazzoni I also faced this issue but have resolved it by setting the following env variables:
> 
> ```
> TARGET=aarch64-unknown-linux-musl
> export TARGET_CC=${TARGET}-gcc
> export TARGET_AR=${TARGET}-ar 
> ```
> 
> I am compiling from Mac to Linux using the toolchains provided here: https://github.com/messense/homebrew-macos-cross-toolchains
> 
> My builds failed with the exact same error you had but disappeared once I set the env vars above. I got the idea from the instructions found here: https://github.com/briansmith/ring/blob/main/BUILDING.md.
> 
> Not sure if it will, but I hope this helps.

This one worked for me!
Compiling for ARM Cortex A9  from Windows Subsystem for Linux using external toolchain.
My setup.sh that i source when terminal opens: 
```
PATH=$PATH:$PWD/arm-cortex_a9-linux-gnueabi/bin  

# added these
export TARGET_CC=arm-cortex_a9-linux-gnueabi-gcc  
export TARGET_AR=arm-cortex_a9-linux-gnueabi-ar 
```

~/.cargo/config
```
[target.arm-unknown-linux-gnueabi]
linker = "arm-cortex_a9-linux-gnueabi-gcc"
```

Build command:     
```
cargo build --target=arm-unknown-linux-gnueabi
```

**Comment by briansmith** [comment]
Please see *ring*'s GitHub Actions CI configuration and the shell scripts it uses for examples of working cross-compilation. I hope to make it easier (automatic) in the future.
