### ISSUE TITLE
Out-of-place encryption

### ISSUE THREAD

**Issue by goffrie** [briansmith/ring#1563]
Currently all open/seal methods operate in-place on a single contiguous buffer, but the underlying primitives support input and output in different buffers. Would a PR adding out-of-place open/seal methods be considered?

I believe this would be useful for e.g. speeding up `rustls` which currently has to do an extra memcpy, as it isn't able to reuse the original buffers.

**Comment by gustav3d** [comment]
Getting rid of extra memcpy sounds like low hanging fruit for performance improvements :)

**Comment by briansmith** [comment]
Closing as a duplicate of #436. I agree we should have this.
