### ISSUE TITLE
Should `UnboundKey` impl `Clone`?

### ISSUE THREAD

**Issue by Austaras** [briansmith/ring#1566]
I know `BoundKey` shouldn't be `Clone` because of nonce, but it seems harmless to clone `UnboundKey`

**Comment by briansmith** [comment]
> I know BoundKey shouldn't be Clone because of nonce, but it seems harmless to clone UnboundKey

To construct a `BoundKey`, one first starts with an `UnboundKey`. Thus, for the same reason `BoundKey` cannot be cloned (to prevent nonce duplication), we cannot clone `UnboundKey`.

If you want to have two `BoundKey`s that use the same AES key but which have different (disjoint) nonce sequences (e.g. one key uses odd nonces, the other uses even nonces, and/or they have different prefixes/suffixes) then we should provide a new API for constructing a pair/set of `BoundKey`s from a single `UnboundKey`. If you don't want to use *ring*'s nonce sequence feature, then you can use `LessSafeKey` instead.
