### ISSUE TITLE
Confusion regarding UnparsedPublicKey.

### ISSUE THREAD

**Issue by cheako** [briansmith/ring#1577]
For `ring::agreement::UnparsedPublicKey` I had assumed poorly that I wanted to convert that into a `PublicKey` to "parse" it.  The example didn't have a locale and remote section so I didn't think it applied to my use case.

To make sure, the `PublicKey` type is exclusively for local keys.  This is wonderful, but it's confusing.  In my application locale is called node and remote is peer, so there are a lot of variations.

I suggest calling these `RemotePublicKey` and `LocalPublicKey`.

**Comment by briansmith** [comment]
I agree. That API should be greatly improved and I look forward to such improvements being made. I don't think that having this issue open is going to advance progress so I'm going to close it. Thanks for the feedback.
