### ISSUE TITLE
Comments on ring::agreement example.

### ISSUE THREAD

**Issue by cheako** [briansmith/ring#1578]
The example at first glance looks like it's only suitable for test infrastructure and not usable in real life, as I see now.  Either add some comments or refactoring things into functions, so it's clear the code is meant to be run across some divide.

Sorry for opening a bunch of issues, there is one more.

**Comment by briansmith** [comment]
Thanks for reporting this. Creating examples is a tough trade-off between conciseness, completeness. and effort. Maybe there is a better trade-off to be made. Considering the big backlog if stuff, I'm going to close this as "it's good enough."
