### ISSUE TITLE
Clarity on what functions are slow.

### ISSUE THREAD

**Issue by cheako** [briansmith/ring#1579]
I'm told elsewhere that these functions should be fast enough not to worry, but I still feel like getting clarity.

Is it true that agreement has some paths that are CPU bound?  I'm wondering to what degree `EphemeralPrivateKey::generate` and `EphemeralPrivateKey::compute_public_key` are slow paths.  `agreement::agree_ephemeral` seems like it might be quick?

What is the expected performance of these functions?

**Comment by briansmith** [comment]
That's a valid question. 

As things stand now, I'm going to oversimplify a bit and say "everything should be fast enough to not worry about it" and close this issue.

Obviously whether things are "fast enough" depends on the target environment and performance needs. I am super interested in supporting environments where things like key agreement are not "fast enough" to be done in a single function call but so far there's been very little interest from others in that area. I would love to have a chat with people who are interested in that space; reach out via email.
