### ISSUE TITLE
ECDSA Signature ASN.1 encoding integer length oddity

### ISSUE THREAD

**Issue by Roolli** [briansmith/ring#1584]
Hello,

I am generating ECDSA signature with the p256 curve with SHA256 and ASN.1 encoding. When looking at the encoded signature I noticed in some cases one of the generated numbers' length is not the expected 32 or 33 bytes if a null byte is needed, but it's 31 instead. The signature that is generated is still valid, but this needs to be addressed when extracting the values from the encoded signature.

Is this expected behaviour (due to encoding, etc...)? I have not seen this documented anywhere.

**Comment by briansmith** [comment]
> Is this expected behaviour 

Yes.
