### ISSUE TITLE
Tag lacking for `0.16.20` release.

### ISSUE THREAD

**Issue by johnoneil** [briansmith/ring#1593]
Could a tag be introduced on the correct commit corresponding to the current Crates.io release `0.16.20` ?

Note that the git history message for commit `9cc0d45f` describes it as release `0.16.20` but this may not be correct as I see warnings building on that hash that I don't see when building with the Crates.io release.

**Comment by MichaIng** [comment]
I had the same trouble assuring to use the exact matching commit. Release tags are highly welcome 🙂.

**Comment by briansmith** [comment]
Planning to do this as part of the next release, but not for old releases.
