### ISSUE TITLE
Cannot find function `fill_impl`

### ISSUE THREAD

**Issue by fengerhu1** [briansmith/ring#1597]
Hi,
I want to cross-compile the ring using --target=aarch64-unknown-none-softfloat in the cargo command.
However, I meet the following error during the cargo build,

error[E0425]: cannot find function `fill_impl` in this scope
   --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/ring-0.16.20/src/rand.rs:160:9
    |
160 |         fill_impl(dest)
    |         ^^^^^^^^^ help: you might have meant to call the method: `self.fill_impl`

I want to run Ring in bare metal with a lightweight OS, no Linux/POSIX supported.

How can I solve this problem?

**Comment by briansmith** [comment]
You must create a patch and/or post a PR to *ring* that adds support to `ring::rand` for your operating system.
