### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET ignored

### ISSUE THREAD

**Issue by andreyrd** [briansmith/ring#1600]
Setting the `MACOSX_DEPLOYMENT_TARGET` when building a rust library will make sure that the library has a minimum supported OS of that version. https://github.com/rust-lang/cargo/issues/4667

Ring seems to just default to the current system version in it's build script, meaning my compiled library now can't link against anything built for an older version.

(Same problem for iOS too, btw)

**Comment by francesca64** [comment]
Proposed solution: When building for macOS/iOS, _ring_'s `build.rs` should read the `MACOSX_DEPLOYMENT_TARGET`/`IPHONEOS_DEPLOYMENT_TARGET` env vars, and default to the same minimums Rust specifies if they're not set. After that, the minimum version would be passed to clang using `-mmacosx-version-min`/`-mios-version-min`.

The current minimums chosen by Rust (and their potential future change) are listed here: rust-lang/rust#104385

I'll create a PR.

**Comment by francesca64** [comment]
It looks like this is actually an upstream issue: rust-lang/cc-rs#708

However, the existing code suggests that this should already work for iOS: https://github.com/rust-lang/cc-rs/blob/57853c4bf8a89a0f4c9137eb367ac580305c6919/src/lib.rs#L2294-L2328

@andreyrd can you confirm that you're experiencing this issue on iOS?

**Comment by briansmith** [comment]
> @briansmith this is an upstream issue and can be closed.

Thanks for following up! Closing this as you suggest.
