### ISSUE TITLE
Linking issues on WSL

### ISSUE THREAD

**Issue by ereOn** [briansmith/ring#1603]
I am using `ring = "0.16.20"` in my project.

My project compiles fine on OSX but when compiling on WSL, I get link errors that I can't really make sense of:

```
 note: /usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::cpu::intel::Feature::available':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/cpu.rs:320: undefined reference to `GFp_ia32cap_P'
/usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::aead::poly1305::Context::update':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/poly1305.rs:103: undefined reference to `GFp_poly1305_update'
/usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::aead::chacha20_poly1305::chacha20_poly1305_seal':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/chacha20_poly1305.rs:100: undefined reference to `GFp_chacha20_poly1305_seal'
/usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::cpu::intel::Feature::available':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/cpu.rs:320: undefined reference to `GFp_ia32cap_P'
/usr/bin/ld: /root/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::aead::poly1305::Context::update':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/poly1305.rs:103: undefined reference to `GFp_poly1305_update'
/usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::aead::chacha20_poly1305::chacha20_poly1305_open':
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/src/aead/chacha20_poly1305.rs:169: undefined reference to `GFp_chacha20_poly1305_open'
/usr/bin/ld: /root/dev/x/target/debug/deps/libring-fa35e7be8c5102ac.rlib(ring-fa35e7be8c5102ac.ring.2c39d1b7-cgu.11.rcgu.o): in function `ring::aead::poly1305::Context::update':
```

I am not sure how to debug this and how to make sense of it. Could anyone give me some pointers on how to move forward and solve this?

Thank you.

**Comment by ereOn** [comment]
Interestingly, this error seems to only happen when building in `debug` and disappears completely - even in `debug` - if I add to my workspace:

```
[profile.dev.package.ring]
opt-level = 1
```

While I am not comfortable changing things I don't fully understand, this has the merit to be a viable workaround I guess.

I'll leave this PR open in case this problem is not expected to begin with and people have something to comment on it.

**Comment by briansmith** [comment]
Usually such issues are due to not having the toolchain set up completely. I build *ring* in WSL (previously WSL 1, lately WSL 2) all the time and it works fine if the toolchain is set up correctly. I hope to make the toolchain difficulties go away. Closing this as inactionable but please let me know if I am overlooking anything. Sorry for the long delay.

**Comment by ndellosa95** [comment]
> Usually such issues are due to not having the toolchain set up completely. I build _ring_ in WSL (previously WSL 1, lately WSL 2) all the time and it works fine if the toolchain is set up correctly. I hope to make the toolchain difficulties go away. Closing this as inactionable but please let me know if I am overlooking anything. Sorry for the long delay.

Any idea what could be missing? I'm hitting a similar issue with a completely fresh install of Ubuntu WSL. This crate is a dependency of a dependency of the one I'm actually trying to work on. I've gone through the install scripts but nothing there is standing out as the thing I'm missing.
