### ISSUE TITLE
aead link is dead

### ISSUE THREAD

**Issue by xobs** [briansmith/ring#1611]
On https://docs.rs/ring/latest/ring/aead/index.html there is a link to https://cseweb.ucsd.edu//~mihir/papers/oem.html

This link does not appear to exist anymore.

**Comment by naterarmstrong** [comment]
This was fixed in #1423, and will propagate to the hosted rust docs once the version is updated.

**Comment by xobs** [comment]
Thanks! I'll close this issue then. It's good that there's a record of it.
