### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by ifsheldon** [briansmith/ring#1620]
I've been following the progress of RISC-V support in `ring` for months but nothing happened(I mean merged). It seems the author has been in a long vacation? Or, is the repo abandoned? 

I opened this because the recent announcement that Debian has officially support RISC-V. And many (virtually) infrastructure crates or Rust libraries and binaries depend on `ring`. Leaving such a crate un-maintained can be a real risk. If it's confirmed abandoned or archived, then well-maintained forks can then take the place.

**Comment by briansmith** [comment]
Hi, no it isn't abandoned. I was on a long break. I have a huge pile of GitHub notifications to triage. If there's something that is urgent I recommend reaching out via email: brian@briansmith.org. Thanks!
