### ISSUE TITLE
Error Reporting in Building Projects under Windows 10

### ISSUE THREAD

**Issue by Dreamer-07** [briansmith/ring#1622]
##cagro.toml：
  toml = "0.5.8"
  sqlx = { version = "0.6.2", features = [
      "runtime-tokio-rustls",
      "mysql",
      "chrono",
  ] }
  once_cell = "1.17.1"
  tokio = { version = "1.25.0", features = ["full"] }
  #时间
  chrono = { version = "0.4.19", features = ["serde"] }
  #序列化
  serde = { version = "1.0.140", features = ["derive"] }
  serde_json = "1.0.82"

##error log: 
     Compiling ring v0.16.20
     Compiling digest v0.10.7
  error: failed to run custom build command for `ring v0.16.20`
  
  Caused by:
    process didn't exit successfully: `D:\StudyCode\Rust\log_handle\target\debug\build\ring-8bed2d135bb4e567\build-script-build` (exit code: 101)
    --- stdout
    OPT_LEVEL = Some("0")
    TARGET = Some("x86_64-pc-windows-gnu")
    HOST = Some("x86_64-pc-windows-gnu")
    cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
    CC_x86_64-pc-windows-gnu = None
    cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
    CC_x86_64_pc_windows_gnu = None
    cargo:rerun-if-env-changed=HOST_CC
    HOST_CC = None
    cargo:rerun-if-env-changed=CC
    CC = None
    cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
    CFLAGS_x86_64-pc-windows-gnu = None
    cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
    CFLAGS_x86_64_pc_windows_gnu = None
    cargo:rerun-if-env-changed=HOST_CFLAGS
    HOST_CFLAGS = None
    cargo:rerun-if-env-changed=CFLAGS
    CFLAGS = None
    cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("true")
    CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  
    --- stderr
    running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oD:\\StudyCode\\Rust\\log_handle\\target\\debug\\build\\ring-8366218e24d7ec19\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
    thread 'main' panicked at 'failed to execute ["gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oD:\\StudyCode\\Rust\\log_handle\\target\\debug\\build\\ring-8366218e24d7ec19\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"]: program not found', E:\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\ring-0.16.20\build.rs:653:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...

**Comment by andrewtj** [comment]
Looks like `gcc.exe` is not present in `%PATH%`. Is it installed and in `%PATH%`?

**Comment by briansmith** [comment]
`x86_64-pc-windows-gnu` can probably be made to work but it I don't test it in CI and I never use it myself (I don't think people should use that target, generally). I believe you can use clang to target `-msvc` if you need to avoid the Microsoft toolchain. if there's a *very small*, *easy to understand* change that is needed to better support the `windows-gnu` target then I would accept a PR for it. But, I am not going to keep the issue open.
