### ISSUE TITLE
error: failed to run custom build command for `ring v0.16.20`

### ISSUE THREAD

**Issue by bmbper** [briansmith/ring#1626]
when i use mac os ,compile my rust app for ubuntu ,  create an error like follow 

cargo build --release --target=x86_64-unknown-linux-musl

error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/Users/zgk/Code/10prod/bmb/bmbp/target/release/build/ring-3300419bd5bb928f/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-musl")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-musl
  CC_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_musl
  CC_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = Some("x86_64-unknown-linux-musl-gcc")
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-musl
  CFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_musl
  CFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

  --- stderr
  running "x86_64-unknown-linux-musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/Users/zgk/Code/10prod/bmb/bmbp/target/x86_64-unknown-linux-musl/release/build/ring-d18c8780601be6dc/out/aesni-x86_64-elf.o" "/Users/zgk/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"
  thread 'main' panicked at 'failed to execute ["x86_64-unknown-linux-musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/Users/zgk/Code/10prod/bmb/bmbp/target/x86_64-unknown-linux-musl/release/build/ring-d18c8780601be6dc/out/aesni-x86_64-elf.o" "/Users/zgk/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/ring-0.16.20/pregenerated/aesni-x86_64-elf.S"]: No such file or directory (os error 2)', /Users/zgk/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/ring-0.16.20/build.rs:653:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by andrewtj** [comment]
https://github.com/briansmith/ring/blob/main/BUILDING.md#cross-compiling

**Comment by briansmith** [comment]
I'm going to close this as I think it amounts to "cross-compiling *ring* is harder than it should be," which is a valid concern but not directly actionable. You can make cross-compiling work today but it isn't easy if you don't have experience doing it. I hope we make it easier. (Thanks @andrewtj for jumping in.)

**Comment by elibroftw** [comment]
Brian, please state which individual components of C++ we need on Windows. I'm not trying to cross compile, just compile a project I made last year that uses MongoDB. I already have Visual Studio installed with the desktop C++, but still does not work. Which of these should we have installed?
![image](https://github.com/briansmith/ring/assets/21298211/e36055d6-d2ac-4a60-9baa-edd8e5c88b28)

**Comment by briansmith** [comment]
From https://github.com/briansmith/ring/blob/3d993da5049a8eefaf5bf49165c7736ab4479a3e/mk/cargo.sh#L145-L151:

I think you are hoping to check some boxes within the Visual Studio installer but I think instead you may need to install Clang/LLVM from llvm.org.
