### ISSUE TITLE
cargo build is failed on ppc64le platform

### ISSUE THREAD

**Issue by bogdansavu** [briansmith/ring#1630]
Hello I'm trying to build LogDNA agent on ppc64le platform using this config:
[patch.crates-io]
ring = { git = "https://github.com/ibm/ring.git", branch = "ppc-0.16.20" }

and I'm getting this error:
error[E0599]: no method named description_ found for struct KeyRejected in the current scope
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rcgen-0.9.3/src/lib.rs:1624:35
|
1624 | RcgenError::RingKeyRejected(err.description_())
| ^^^^^^^^^^^^ method not found in KeyRejected

For more information about this error, try rustc --explain E0599.
error: could not compile rcgen due to previous error

**Comment by ecnelises** [comment]
I tried building with that branch, no error emitted. And no dependency is named `rcgen`, could you test with that single crate?

**Comment by chereskata** [comment]
I do not know if this is relevant, but trying to build `gst-plugins-rs` [sources]() on Alpine Linux with ppc64le results in ring 1.16.20 failing to build. I have also reported the issue to their upstream [here](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/428).

```
Compiling gst-plugin-version-helper v0.7.5 (/builds/chereskata/aports/testing/gst-plugins-rs/src/gst-plugins-rs-0.11.0/version-helper)
error: failed to run custom build command for `ring v0.16.20`
Caused by:
  process didn't exit successfully: `/builds/chereskata/aports/testing/gst-plugins-rs/src/gst-plugins-rs-0.11.0/output/target/release/build/ring-50882fe0efd368b9/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/buildozer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: CliError { error: Some(1 job failed), exit_code: 101 }
```

**Comment by bogdansavu** [comment]
I successfully compiled logdna using branch = "ppc-0.16.20-rework", this branch will be soon merged.

**Comment by runlevel5** [comment]
@bogdansavu since you are using the IBM's fork of ring. I do not think this is the right place to report. Having said that it's good to know you have your app compiled successfully. You can close the ticket now.
