### ISSUE TITLE
Fails compiling on Linux x86-64 / Rust 1.72 due to missing include/GFp/arm_arch.h

### ISSUE THREAD

**Issue by sdroege** [briansmith/ring#1639]
When building `cargo-deny` the following build error happens during the build of `ring`. I'm not sure why it even looks for some ARM header here.

Previously this was definitely working, IIRC also with Rust 1.72, and `ring` 0.16.20 is two years old so I have no idea what actually changed here.

```
[...]
   Compiling ring v0.16.20
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling plain v0.2.3
   Compiling lazy_static v1.4.0
   Compiling cfg-expr v0.15.4
   Compiling codespan-reporting v0.11.1
   Compiling fs-err v2.9.0
   Compiling funty v2.0.0
   Compiling fern v0.6.2
   Compiling spdx v0.10.2
   Compiling rmp v0.8.12
   Compiling nu-ansi-term v0.49.0
   Compiling codespan v0.11.1
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installlqev8R/release/build/ring-14a06657df55d57c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"include/GFp/arm_arch.h": Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/slomo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:769:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-deny v0.14.2`, intermediate artifacts can be found at `/tmp/cargo-installlqev8R`.
```

**Comment by sdroege** [comment]
That's concerning. After a clean build this works fine now (previously it happened multiple times after a clean build too).

**Comment by briansmith** [comment]
> That's concerning. After a clean build this works fine now (previously it happened multiple times after a clean build too).

Are you using the same target directory (e.g. `target/debug`) and switching back between two target architectures? I think Cargo has some issue where it doesn't rerun the build script in all cases in these kinds of scenerios where the target changes but the target directory is the same.

**Comment by sdroege** [comment]
No, that was just a plain simple build. I have no idea what happened there :upside_down_face: It's gone now fortunately.
