### ISSUE TITLE
Add Big-endian PowerPC code coverage measurement

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1679]
Right now neither 32-bit nor 64-bit PowerPC code coverage is being measured in CI because neither target supports the profiler builtins. 

`powerpc64le-unknown-linux-gnu` *does* support the profiler builtins.

Also @uweigand added profiler builtins to the `s390x-unknown-linux-gnu` in https://github.com/rust-lang/rust/pull/104304, so big-endian support is already there.

/cc @runlevel5 @ecnelises @q66 @erichte-ibm

**Comment by briansmith** [comment]
Hi friends, would it be possible to make progress on this? Would it be helpful if I filed the issues in the rust-lang/rust repo for adding the profiler builtins for these targets? I am planning to file an issue asking that having working profiler builtins be a requirement for all "Tier 1" targets for Rust.

**Comment by ecnelises** [comment]
Big endian PowerPC on Linux is not so popular today. But let me check it inside QEMU first.

**Comment by ecnelises** [comment]
I enabled profiler and cross built rust compiler for powerpc64-unknown-linux-gnu successfully on a ppc64le machine. I will try build for powerpc/powerpc64-linux and verify compiling programs with profile-generate and profile-use. IIUC that is all the necessary test?

BTW the CI Dockerfiles for powerpc and powerpc64 seems outdated. I may need to do some update.

**Comment by briansmith** [comment]
You can try the equivalent of `RING_COVERAGE=1 mk/cargo.sh +nightly --target={YOUR_TARGET} test` to see if code coverage measurement works. This basically adds `-Cinstrument-coverage` to `$RUSTFLAGS` and `-fprofile-instr-generate -fcoverage-mapping` to `$CFLAGS`, as well as setting `$CC` to `clang`. (You probably have to set clang as the linker as well.) If this builds and runs the tests then it should generate coverage output in which case it is probably exactly what I need.

**Comment by briansmith** [comment]
@ecnelises Any chance we may see a PR for the code coverage soon? I do believe it is just a matter of adding `--enable-profiler` to the Docker file? I understand you also think the Docker file should get updated in other ways but I wonder if we could do this minimal change. or maybe it's not sufficient?

I get nervous about supporting these big-endian targets when BoringSSL explicitly doesn't, especially when they keep reinforcing that, e.g. https://boringssl.googlesource.com/boringssl/+/ec87e1a7672044cbd7d484f2478cd618a7f1f81a%5E%21/#F0. Getting the code coverage measurement working would help alleviate those concerns.

**Comment by ecnelises** [comment]
Sorry for so late response! I tested cross building a Rust toolchain targeting ppc64-unknown-linux-gnu and ran mk/cargo.sh test with coverage. It went well until last step SIGILL in QEMU, but I believe that's environment issue. I will try on another machine and do update this week.

Per my understanding, I should add `powerpc64-unknown-linux-gnu` (and 32-bit one) into CI config profiling builtin section of this repo, after adding profiler builtin to Rust Dockerfile build flags?

**Comment by briansmith** [comment]
> Sorry for so late response! I tested cross building a Rust toolchain targeting ppc64-unknown-linux-gnu and ran mk/cargo.sh test with coverage. It went well until last step SIGILL in QEMU, but I believe that's environment issue. I will try on another machine and do update this week.

Great!

> Per my understanding, I should add powerpc64-unknown-linux-gnu (and 32-bit one) into CI config profiling builtin section of this repo, after adding profiler builtin to Rust Dockerfile build flags?

That would be awesome. You should be able to copy the `powerpc64le-unknown-linux-gnu` entries. It's easy for either you or me to do.

Getting the profiler builtins working in rust-lang/rust and testing it is the part I could use the most help with.

**Comment by briansmith** [comment]
PR #1874 added this for powerpc64, thanks to @ecnelises. PR #1877 is attempting to do the same for 32-bit PowerPC but it is blocked on rust toolchain issues; see that PR for details. Regardless, I'm going to close this issue since the PR tracks it.
