### ISSUE TITLE
Benchmark ChaCha20 and Poly1305 vs Andrew Moon's implementations

### ISSUE THREAD

**Issue by DemiMarie** [briansmith/ring#170]
Andrew Moon has very fast ChaCha20 and Poly1305 implementations at https://github.com/floodyberry/chacha-opt and https://github.com/floodyberry/poly1305-opt respectively.  _ring_'s code should be benchmarked against them.

**Comment by briansmith** [comment]
Sure, this seems reasonable. FYI, *ring*s benchmarks are in https://github.com/briansmith/crypto-bench.

**Comment by drbo** [comment]
Note the 32-bit ChaCha20 x86 AVX2 code is broken as of git HEAD.  Reverting the last commit seems to give a working version.

**Comment by briansmith** [comment]
On Thu, Jun 9, 2016 at 11:23 AM, Demetri Obenour <notifications@github.com>
wrote:

> Note the 32-bit ChaCha20 x86 AVX2 code is broken as of git HEAD. Reverting
> the last commit seems to give a working version.


What do you mean by broken? Are the tests failing? Or, do you mean that
when you enable the AVX2 x86 code, things break?


-- 
https://briansmith.org/

**Comment by briansmith** [comment]
This is actually pretty important to do for x86 (32-bit), ARM, and AAarch64 now, so we can decided whether it is worthwhile to keep using the asm code, or whether it is better to switch to an easier-to-maintain Rust or C implementation.

**Comment by briansmith** [comment]
Let's do this in crypto-bench.
