### ISSUE TITLE
curve25519_64_adx.h missing

### ISSUE THREAD

**Issue by dswd** [briansmith/ring#1707]
I just ran into the following issue when building a project with `ring = "0.17.1"` as dependency:

```
crypto/curve25519/curve25519_64_adx.c:23:10: fatal error: ../../third_party/fiat/curve25519_64_adx.h: No such file or directory
     23 | #include "../../third_party/fiat/curve25519_64_adx.h"
```

The file `curve25519_64_adx.h` is not present in the `fiat` directory.
I guess it is missing in the list here: https://github.com/briansmith/ring/blob/main/Cargo.toml#L144

Building with dependency `ring = { git = "https://github.com/briansmith/ring", rev = "2afc921" }` works fine.

I am just wondering why I am the only one having this problem....

**Comment by mcseemk** [comment]
I have the same problem.

**Comment by briansmith** [comment]
Please update to 0.17.2. Sorry; I tested the built package using almost every target except x86_64 non-Windows, which are the targets that use that header. See https://github.com/briansmith/ring/pull/1708.
