### ISSUE TITLE
Cache more downloaded build prerequisites in CI

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#173]
- [ ] For ARM[32] and AAarch64 builds, the C compiler is downloaded from https://releases.linaro.org/components/toolchain/binaries/. This should be cached using Travis CI's caching feature, as was done for kcov in https://github.com/briansmith/ring/commit/1a1f458e3b8d41431bb32cac32fe5160bf4b2ca5.
- [ ] No caching is done on Appyveyor at all. The Travis CI work should be replicated on Appveyor. Actually, Windows builds require extra downloads like Yasm so they can actually benefit more from caching than the Travis CI.

**Comment by pietro** [comment]
According to travis documentation caching binaries won't speed things much because they still need to be downloaded from S3. They recommend caching dependencies that need to be built. Anyway to point moot if #174 gets merged and we use ubuntu's gcc packages.

**Comment by briansmith** [comment]
Thanks @pietro. Closing this based on your comments.
