### ISSUE TITLE
Missing APIs after upgrading to 0.17

### ISSUE THREAD

**Issue by sheepduke** [briansmith/ring#1753]
After upgrading `ring` dependency from `0.16` to `0.17`, I noticed some API changes that broke our build pipeline. Some were trivial to fix (e.g. `public_modulus_len()`), while others were not.

I dig into the documents but did not find any resource on how to achieve the same thing as before:
* `public_key.modulus().big_endian_without_leading_zero()`
* `public_key.exponent().big_endian_without_leading_zero()`

Could you please kindly help with it? Am I missing a migration or so guide somewhere?

**Comment by briansmith** [comment]
> ```
> public_key.modulus().big_endian_without_leading_zero()
> public_key.exponent().big_endian_without_leading_zero()
> ```

Can you try this?:

```rust
let components = `RsaPublicKeyComponents<&[u8]>::from(x.public());`
c.modulus();
c.components();
```

**Comment by sheepduke** [comment]
Thank you @briansmith for your quick reply!

I cannot test it out now, but as long as there is an one-to-one solution, it should be fine.

BTW I think it would be really helpful to provide a simple migration guide for these breaking changes. :-)

I am closing this issue now. Will re-open it when I have issues with the new functions.
