### ISSUE TITLE
Documentation not accessible from Tor due to CloudFlare

### ISSUE THREAD

**Issue by burdges** [briansmith/ring#179]
Appears the site briansmith.org used for the [documentation](https://briansmith.org/rustdoc/ring/) cannot be accessed from Tor due to its CloudFlare configuration requiring an unsolvable captcha.  See : [faq](https://people.torproject.org/~lunar/20160331-CloudFlare_Fact_Sheet.pdf) [blog](https://blog.torproject.org/blog/trouble-cloudflare), [trac](https://trac.torproject.org/projects/tor/ticket/18361), [etc](http://www.slashgeek.net/2016/05/17/cloudflare-is-ruining-the-internet-for-me/).

**Comment by briansmith** [comment]
I changed the CloudFlare settings which should allow Tor traffic to work as well as CloudFlare will allow. Please let me know how it is now.

**Comment by burdges** [comment]
Yup.  It appears to load just fine now.  It might depend upon the specific exit node of course, but I tried it form several without problem.  Thanks!  :)

**Comment by briansmith** [comment]
Thanks for reporting back!
