### ISSUE TITLE
Compilation fails on ESP32 "xtensa-esp32-espidf"

### ISSUE THREAD

**Issue by marcozetaa** [briansmith/ring#1848]
I get the following error when i try to compile a rust program to flash in an ESP32:

`[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/marco/Desktop/rust_client/tests/target/debug/build/ring-d5da1aab0170b63a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/marco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::panicking::panic
     3: core::option::Option<T>::unwrap
at /home/rust/rust/library/core/src/option.rs:935:21
     4: build_script_build::build_c_code
               at ./build.rs:352:34
     5: build_script_build::ring_build_rs_main
               at ./build.rs:279:5
     6: build_script_build::main
               at ./build.rs:240:13
     7: core::ops::function::FnOnce::call_once
               at /home/rust/rust/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

Is it not supported or do I have to add some extra config?

**Comment by marcozetaa** [comment]
I fixed it by overriding the version `ring = "=0.17.6`

**Comment by briansmith** [comment]
> I fixed it by overriding the version ring = "=0.17.6

`cargo update -p ring` will update your Cargo.lock to update the project to the latest (0.17.x) version automatically.
