### ISSUE TITLE
windows x64 build failed 

### ISSUE THREAD

**Issue by luoxing** [briansmith/ring#1870]
git clone https://github.com/briansmith/ring.git
cd ring
.\mk\install-build-tools.ps1
cargo build

PS C:\Users\luoxing\ring> cargo build
   Compiling ring v0.17.7 (C:\Users\luoxing\ring)
error: failed to run custom build command for `ring v0.17.7 (C:\Users\luoxing\ring)`

Caused by:
  process didn't exit successfully: `C:\Users\luoxing\ring\target\debug\build\ring-cf63204d3274b06f\build-script-build` (exit code: 1)
.
.
.

  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "include" "-I" "C:\\Users\\luoxing\\ring\\target\\debug\\build\\ring-405868303ff5af9c\\out" "-W4" "/Gy" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "-WX" "-FoC:\\Users\\luoxing\\ring\\target\\debug\\build\\ring-405868303ff5af9c\\out\\crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

**Comment by briansmith** [comment]
See https://github.com/briansmith/ring/blob/main/BUILDING.md#supported-toolchains-and-cross-compiling and look at how we build for AArch64 Windows in our GitHub Actions.
