### ISSUE TITLE
want windows on arm support

### ISSUE THREAD

**Issue by Rei1mu** [briansmith/ring#1872]
want windows on arm support,  its important when woa cargo build

**Comment by briansmith** [comment]
Do you mean 64-bit ARM, i.e. ARM64/AArch64? It was added in https://github.com/briansmith/ring/issues/1167, ring 0.17.0. Make sure you don't have any dependencies that are using earlier versions of *ring* and it should work fine. See BUILDING.md.

**Comment by Rei1mu** [comment]
thanks ,build it success.
![image](https://github.com/briansmith/ring/assets/94012185/98d8e5b6-2446-41bc-b6d3-32d5f32d8370)
