### ISSUE TITLE
Hard-coding of ar?

### ISSUE THREAD

**Issue by xuxiaocheng0201** [briansmith/ring#1891]
When I cross-compiled from Windows to Android, it occurred an error:
```text
 error occurred: Failed to find tool. Is `i686-linux-android-ar` installed? (see https://github.com/rust-lang/cc-rs#compile-time-requirements for help)
```
However, I set the `[target.aarch64-linux-android.ar]` in `.cargo/config.toml`.

Then I created a symbol link linked to ar and it worked, so I'm not care about the real reason. But I think this should be a bug.

**Comment by briansmith** [comment]
> However, I set the `[target.aarch64-linux-android.ar]` in `.cargo/config.toml`.

The documentation at https://doc.rust-lang.org/cargo/reference/config.html says:
> [target.<triple>.ar](https://doc.rust-lang.org/cargo/reference/config.html#targettriplear)
> This option is deprecated and unused.

**Comment by briansmith** [comment]
It looks like you need to set AR (if not using `--target` to build) or `TARGET_AR` or related environment variable, instead of .cargo/config.toml, based on the above. See `mk/cargo.sh` in *ring*'s source code.

**Comment by xuxiaocheng0201** [comment]
> It looks like you need to set AR (if not using `--target` to build) or `TARGET_AR` or related environment variable, instead of .cargo/config.toml, based on the above. See `mk/cargo.sh` in _ring_'s source code.

Thank you, I will try later.
