### ISSUE TITLE
Rust 1.77 issues false positive `dead_code` warnings for `#[repr(transparent)]` structs.

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#1917]
See https://github.com/rust-lang/rust/issues/119659. This affects all the `#[repr(transparent)]` tuple structs like `N0` where the field is actually used by C or assembly code, but not by Rust code.

**Comment by riking** [comment]
Upstream issue is fixed

**Comment by briansmith** [comment]
Thanks. It seems l already made the code changes to revert the workaround so there's nothing left to do here.
