### ISSUE TITLE
Figure out what to do with x86 Poly1305 AVX implementation

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#192]
This is about the `$avx` flag in crypto/poly1305/asm/poly1305-x86.pl. Currently it is set to zero. It could be set to 2.

BoringSSL has it disabled ("0") because they can't generate their test coverage reports for it and so they don't trust the code.

This code also seems to use only this build-time flag, and not runtime feature detection, to determine whether to try the AVX code. That seems wrong.

Maybe the best solution is to stick to the SSE2 code and then just delete the AVX code.

**Comment by drbo** [comment]
I don't think that the AVX code should be deleted.

Why can't BoringSSL generate test coverage for it?  That seems like the problem.

Runtime feature detection can be added on to the code once the testing issue is fixed.

**Comment by briansmith** [comment]
> Runtime feature detection can be added on to the code once the testing issue is fixed.

That would be great. I would love for somebody to try.

**Comment by briansmith** [comment]
Closing this. It's unlikely there's any need for 32-bit x86 AVX code.
