### ISSUE TITLE
Issue while crosscompiling ring for aarch64

### ISSUE THREAD

**Issue by chiru091096** [briansmith/ring#1936]
Hello,

I'm was trying to cross compile ring v0.17.3 for aarch64. I got the below error 
```
fatal error: stdint.h: No such file or directory
#include_next <stdint.h>
```
Upon adding path of stdint.h in build.rs (at line no. 537) I was able to fix the error. (Added c.flag("-I/path/to/include"))
https://github.com/briansmith/ring/blob/ee5db436170388b28b8e8f548eee62de61f1268f/build.rs#L534-L544

However, same changes in ring v0.17.2 is not fixing the error. I specifically want to cross compile ring v0.16.20.
What changes can I make to build.rs in older versions of ring to fix this error. I'm fairly new to rust. Any help on this will be appreciated.

**Comment by briansmith** [comment]
What are the exact commands you are using to build? `TARGET_CC=? TARGET_AR=? cargo build --target=?`

**Comment by chiru091096** [comment]
@briansmith 
I can see below logs when building
TARGET_CC= None
cargo build --target=aarch64-unknown-linux-gnu

**Comment by briansmith** [comment]
OK, take a look at `mk/{install-build-tools,cargo}.sh` in this repo to understand how to configure the C toolchain to cross-compile *ring*.

**Comment by chiru091096** [comment]
> OK, take a look at `mk/{install-build-tools,cargo}.sh` in this repo to understand how to configure the C toolchain to cross-compile _ring_.

I will check that. Thanks @briansmith

**Comment by chiru091096** [comment]
@briansmith 
using the command `./mk/cargo.sh build --target=aarch64-unknown-linux-gnu`, I'm able to build older versions of ring. However, the command `cargo build --target=aarch64-unknown-linux-gnu` fails with same initial error. Since I'll be building ring indirectly (as a dependency of some other library), how can I make this work.
