### ISSUE TITLE
x86_64-linux-gnu -> {x86_64,aarch64}-apple-darwin cross-compilation broken with `cc 1.0.85`

### ISSUE THREAD

**Issue by rvolosatovs** [briansmith/ring#1945]
Not sure if this is caused by an issue in Ring or in `cc` (therefore, filing a duplicate here), but cross-compiling `ring v0.17.7` from x86_64 Linux to x86_64-apple-darwin and aarch64-apple-darwin is broken when upgrading from `cc 1.0.83` to `cc 1.0.85`
See more details at https://github.com/rust-lang/cc-rs/issues/948
Refs https://github.com/bytecodealliance/wit-deps/pull/118

**Comment by briansmith** [comment]
@rvolosatovs it seems like cc-rs yanked the release, so it should be working now with the latest non-yanked release?

**Comment by rvolosatovs** [comment]
> @rvolosatovs it seems like cc-rs yanked the release, so it should be working now with the latest non-yanked release?

It does indeed, I found out that the cause for this is `--target` flag, which is now specified by `cc`.
