### ISSUE TITLE
error: failed to run custom build command for `ring v0.16.20`

### ISSUE THREAD

**Issue by Adarsh999bh** [briansmith/ring#2000]
Hi,
I'm trying to build ( cross compile ) a client using [fastembed-rs](https://github.com/Anush008/fastembed-rs)  for aarch64 architecture in x86_64 linux, but it's failing with the above error mentioned in the title, while analysing logs (stdout) I found that TARGET and HOST are both same ( x86_64-unknown-linux-gnu )
And i believe that is also the reason while building it is trying to pass the option -m64 which is also leading to the error ```aarch64-linux-gnu-gcc: unrecognised command line option '-m64'```

Any idea why this is happening.? did I miss out any flags.?

**Comment by briansmith** [comment]
Hi, this is a supported configuration. You need to set some environment variables for it to work. Look at mk/cargo.sh .
