### ISSUE TITLE
Consider using `zeroize` crate for key materials

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [briansmith/ring#2005]
I'm working on software that uses AES encryption and I see that the `rsa` crate is actively using the `zeroize` crate as a dependency that automatically removes private keys from memory.

Also see: https://docs.rs/zeroize/1.7.0/zeroize/struct.Zeroizing.html

**Comment by briansmith** [comment]
Thanks for the suggestion. There's already an issue for zeroization, issue #15, so I'm going to close this as a duplicate of that.
