### ISSUE TITLE
Deal with undefined behavior due to memcpy

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#201]
I know there are some cases where we seem to `memcpy(NULL, ..., 0)`, which is bad due to being undefined behavior. In particular, there are some places in crypto/bn. Apparently all forks are affected. Find the bug report and smash the bugs.

**Comment by 0x64616E69656C** [comment]
I'm currently using this:

```
AWESOME_memcpy(void *dest, const void *src, size_t len) {
  /* src || dest NULL == UB. len == 0 defined, but makes no sense */
  if (src != NULL && dest != NULL && len > 0) {
#ifndef NDEBUG
    /* should not happen */
    if ((dest < src && dest + len > src) ||
        (src < dest && src + len > dest)) {
      assert(0);
    }
#endif

    if (src == dest) {
      memmove(dest, src, len);
    } else {
      memcpy(dest, src, len);
    }
  }
}
```

One might argue that this adds overhead, compiler optimizes out, blah blah, but it makes UBSan happy, and that makes me happy. "should not happen" was introduced in OpenBSD's bcopy IIRC, and I'm skipping zero-len because it doesn't make much sense to me.
That would leave you with maybe a few UB's in memset, for me that's just in BN_bn2bin_padded(), which I'm keeping for a rainy day.

**Comment by briansmith** [comment]
Here's a good way to make it easy to verify the code is correct with respect to cross-type memcpys: For every use of memcpy copying a single value to another value of the *same* type *T*, create a wrapper function:

```c
static inline void t_copy(T *dest, const T *src) { memcpy(dest, src, sizeof(T)); }
```

If we're copying arrays, we need to deal with the case where the input array length *n* is zero-sized and/or too large, something like.

```c
static inline void t_copy_array(T *dest, const T *src, size_t n) {
    if (n == 0) {
        return;
    }
    /* TODO: how to prevent |sizeof(T) * n| from overflowing? */
    memcpy(dest, src, sizeof(T) * n);
}
```

If we know that `n` is never zero then such functions could be named something like `t_copy_array_nonempty` and an assertion can replace the `if (n == 0)` condition with an assertion.

When this is done, every use of `memcpy` should be in one of these functions.

**Comment by briansmith** [comment]
As of now `memcpy` is only used in cases where the destination is a local array, which makes it easy to see that the destination is never NULL. So this is done!
