### ISSUE TITLE
Replace crypto/chacha/chacha_test.cc with Rust equivalent

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#202]
We're trying to get rid of the requirement for a C++ compiler to build *ring*, and this is one of the blockers to that.

The license of crypto/chacha/chacha_test.cc is the same ISC-like license *ring*'s Rust code uses, so feel free to reuse (i.e. transliterate it to Rust) as much of it as is useful to reuse. If any parts are transliterated then make sure the Google copyright/license block is copied exactly.

The test vectors should be put into a chacha_tests.txt file and read using the ring::file_test framework.

**Comment by NilSet** [comment]
This should be closed as of f5be9c34b10cd0d192a5eda394dd655a2db707c4

**Comment by briansmith** [comment]
> This should be closed as of f5be9c3

Thanks!
