### ISSUE TITLE
Replace crypto/poly1305/poly1305_test.cc with a Rust equivalent

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#203]
We're trying to get rid of the requirement for a C++ compiler to build _ring_, and this is one of the blockers to that.

The license of `crypto/poly1305/poly1305_test.cc` is the same ISC-like license _ring_'s Rust code uses, so feel free to reuse (i.e. transliterate it to Rust) as much of it as is useful to reuse. If any parts are transliterated then make sure the Google copyright/license block is copied exactly.

Note that the _ring_ already has a Rust equivalent to the C++ file_test.h framework: `ring::file_test`. Also note that after poly1305_test.cc is removed, the C++ file_test framework will no longer be used and so it can be removed (in a separate commit).

**Comment by newpavlov** [comment]
We can't remove the C++ file_test framework yet, since crypto/bn/bn_test.cc depends on it too.

**Comment by briansmith** [comment]
> We can't remove the C++ file_test framework yet, since crypto/bn/bn_test.cc depends on it too.

That's right. At the time I wrote my comment, bn_test wasn't using it, but it is now.

**Comment by briansmith** [comment]
This was done in 3b5ae496b97ac3414ea51d67b5bd3e6014ffc905. Thanks!
