### ISSUE TITLE
Ring no longer builds with Rust 1.61 due to cc dependency

### ISSUE THREAD

**Issue by uweigand** [briansmith/ring#2035]
As of cc 1.0.95, the minimum required Rust version is 1.63: https://github.com/rust-lang/cc-rs/pull/1031

However, the Ring CI still attempts to build with 1.61, which now fails with:
```
error: package `cc v1.0.95` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.61.0
```

We should either increase the minimum required Rust level for Ring as well, or else force use of an older cc version.

**Comment by briansmith** [comment]
> We should either increase the minimum required Rust level for Ring as well, or else force use of an older cc version.

The user of *ring* could already force an older cc-rs version if they want to, using their `Cargo.lock`. However, I updated the MSRV of *ring* to 1.63 in PR #2037 so that I don't have to add any complication to the GitHub Actions configuration regarding this.
