### ISSUE TITLE
Replace crypto/aes/aes_test.cc with a Rust equivalent

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#204]
We're trying to get rid of the requirement for a C++ compiler to build ring, and this is one of the blockers to that.

The license of crypto/aes/aes_test.cc is the same ISC-like license ring's Rust code uses, so feel free to reuse (i.e. transliterate it to Rust) as much of it as is useful to reuse. If any parts are transliterated then make sure the Google copyright/license block is copied exactly.

aes_test.cc has some `fprintf`s for when the tests fail; this isn't necessary in the Rust variant.

Instead of hard-coding the test vectors into the Rust source code, please use the `ring::file_test` framework for the test vectors.

**Comment by newpavlov** [comment]
If my understanding is correct then aes_test.cc tests only `AES_encrypt` which is not used directly by the rust code, but only indirectly through `evp_aead_aes_gcm_*` functions. So if I am to rewrite this tests should I simply write it for  `AES_set_encrypt_key` and `AES_encrypt` using exec or should I expose pure AES encryption (i.e. by writing a thin wrapper around `AES_encrypt`) and test it instead?

**Comment by briansmith** [comment]
> should I expose pure AES encryption (i.e. by writing a thin wrapper around AES_encrypt) and test it instead?

I would test it like `ChaCha20_ctr` is tested. in the `tests` submodule of src/aead/aes_gcm.c, declare `AES_*` as an `extern` functions and then have the test function call them. No need for `exec` and they don't need to be added to the public *ring* API.

**Comment by briansmith** [comment]
This was done in #204.
