### ISSUE TITLE
support for RISCV32

### ISSUE THREAD

**Issue by ub-tech** [briansmith/ring#2041]
Hi - I'm trying to run a repo with ring as dependency on a RISC32 arch.  I tried to override the dependency based on [this convo](https://github.com/briansmith/ring/pull/1627#issuecomment-1726060248).  Is riscv32 supported?  Am I trying to implement this override correctly (please see below)?  TY very much for any insights.

[patch.crates-io]
ring = { git = "https://github.com/leso-kn/ring.git", package = "ring", branch = "riscv64-support-plus-riscv32" }

**Comment by briansmith** [comment]
In target.h, we have:
```
#elif defined(__riscv) && __SIZEOF_POINTER__ == 8
#define OPENSSL_64_BIT
```
So presumably we would also need to add the corresponding change for riscv32.

The bigger issue, AFAICT, is that we don't have any way of testing riscv32 code in CI.

**Comment by briansmith** [comment]
See https://github.com/briansmith/ring/pull/2042#issuecomment-2120898907 for an alternative approach.

**Comment by briansmith** [comment]
Please check out PR #2082 to see if this works for you.

**Comment by briansmith** [comment]
Closing this on the assumption that PR #2082 resolves this, at least if you're not using an old version of GCC>
