### ISSUE TITLE
Document why *ring* does not use traits to model algorithm choice

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#21]
For example, why doesn't _ring_ have a `DigestAlgorithm` trait that is implemented by types named `SHA256`, `SHA384`, etc.? Why is everything dynamically dispatched instead of parameterized on types and statically dispatched? How does the current design avoids unnecessary heap usage and minimizes code size. That means we have to verify that there is actually a code size savings relative to the type parameterization and static dispatching approach that people seem to expect in Rust.

**Comment by briansmith** [comment]
Reconsider this after the placement box stuff is stable: https://github.com/rust-lang/rfcs/pull/1228

**Comment by briansmith** [comment]
It looks like the whole placement new stuff is being tracked in https://github.com/rust-lang/rust/issues/27779. I asked about how to resolve the issues that *ring* has run into with Traits in https://github.com/rust-lang/rust/issues/27779#issuecomment-147002671.

**Comment by briansmith** [comment]
See also https://www.ralfj.de/blog/2015/10/12/formalizing-rust.html: Traits are not in the subset of Rust that they are hoping to define semantics for and/or prove correct.

**Comment by briansmith** [comment]
See https://internals.rust-lang.org/t/pre-rfc-thinness-as-a-property-of-the-data-rather-than-the-trait/2794, https://internals.rust-lang.org/t/blog-post-extended-enums-and-thin-traits/2755, https://internals.rust-lang.org/t/blog-post-extended-enums-and-thin-traits/2755, http://smallcultfollowing.com/babysteps/blog/2015/10/08/virtual-structs-part-4-extended-enums-and-thin-traits/.

**Comment by briansmith** [comment]
Now in `ring::signature` we *are* using traits. And, of course, it creates a problem: We cannot say `&'static signature::Algorithm` but instead have to say `&'static (signature::Algorithm + Sync)` because of Rust type system weirdness.

**Comment by briansmith** [comment]
> Now in ring::signature we are using traits. And, of course, it creates a problem: We cannot always say &'static signature::Algorithm but instead have to say &'static (signature::Algorithm + Sync) when referencing algorithms from other statics, because of Rust type system weirdness.

And, it was so awkward I ended up implementing wrapper types to hide the traits.

> briansmith> right now, you can use ring with "use ring;" or "use ring::{submodule, submodule, submodule};" and everything works.
20:30 <briansmith> But, as soon as you use traits, that stops working, because you need to import the traits too.
20:31 <briansmith> And also, in *ring* we usually use polymorphism to select between algorithms.
20:31 <briansmith> And so, usually, every implementation of each trait would only have one implementation, each.
20:32 <briansmith> So, instead, in *ring* I basically emulate per-object (vs per-trait) polymorphism.
20:34 <briansmith> IMO, it is something that should be fixed in the language: when a type implements a trait, it should be able to say "when I am in scope, the trait should also be in scope."
20:34 <briansmith> but, that's not the case yet.
briansmith

**Comment by Diggsey** [comment]
It looks like `VerificationAlgorithm` extends `Sync` now - doesn't that solve the problem with verbosity? And is the requirement to import traits separately really a show-stopper?

With function pointers, the algorithm structs become much larger than the double-pointer sized `&'static Algorithm`, and it becomes difficult to add more trait implementations like `Debug` in future, without introducing even more inefficiencies. It also prevents downstream crates from extending the set of possible algorithms.

From a security perspective, storing multiple function pointers in writable locations on the stack also seems much more dangerous than a reference to a vtable in read-only memory.

**Comment by briansmith** [comment]
> It looks like VerificationAlgorithm extends Sync now - doesn't that solve the problem with verbosity?

Yes.

> And is the requirement to import traits separately really a show-stopper?

It's a real usability problem. But, it's not worse in *ring* than it is in other APIs.

> With function pointers, the algorithm structs become much larger

It doesn't matter, because there is only one copy of every `Algorithm`, so I don't think it creates any bloat.

> it becomes difficult to add more trait implementations like Debug in future

Not really, because the best implementation of `Debug` for `Algorithm` types is just to output the name of the algorithm and omit the details anyway.

>  It also prevents downstream crates from extending the set of possible algorithms.

True. OTOH, we don't have to worry about external crates' implementations when we refactor the code, because of this. People can contribute implementations of new algorithms to *ring* if they want more algorithms supported.

> From a security perspective, storing multiple function pointers in writable locations on the stack also seems much more dangerous than a reference to a vtable in read-only memory.

Very true, but the compiler should be able to put them in read-only memory since they are all `static` and not `static mut`, just like trait vtables. I'm not sure if the compiler actually does this, though.

**Comment by burdges** [comment]
There is an RFC somewhere to allow types to bring trait methods into scope.  I forget where or what the syntax is, but maybe something like `struct MyStruct: MyTrait+Sync where ..`.  And no movement recently.

**Comment by Diggsey** [comment]
> It doesn't matter, because there is only one copy of every Algorithm, so I don't think it creates any bloat.

Ah, some of my arguments were based on the mistaken assumption that `Algorithm`s were passed around by value.
