### ISSUE TITLE
`function import requires a callable` LinkError error with Cloudflare workers WASM 

### ISSUE THREAD

**Issue by pawurb** [briansmith/ring#2155]
Hi. I'm trying to use the project with Cloudflare Rust workers. I can compile using a custom target and `wasm32_unknown_unknown_js` flag. But adding any import results in:

```
Uncaught LinkError: WebAssembly.Instance(): Import #9 "./index_bg.js" "__wbg_error_53abcd6a461f73d8": function import requires a callable

    at null.<anonymous> (shim.js:41:9)

✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above
```

when running `npx wrangler dev`

I've recreated the issue here: https://github.com/pawurb/ring-wasm-test . Any tips how to resolve it will be appreciated.

**Comment by agustfricke** [comment]
With Rust version 1.82.0, I was getting the same error. Just downgrade Rust to version 1.81.0, which works. You can do this with the command: rustup install 1.81.0, rustup default 1.81.0. https://github.com/cloudflare/workers-sdk/issues/7028, Regards!

**Comment by pawurb** [comment]
@agustfricke thanks, but i'm getting the same error on 1.80, 1.81, and 1.82 . I'm using a bunch of crates in my cf-workers project, and so far `ring` is the only one triggering this bug.

**Comment by aN4ksaL4y** [comment]
faced the same error, and then install as @agustfricke suggested. and seems working.

**Comment by Meowu** [comment]
Same issue. It works with 1.81.0
