### ISSUE TITLE
Remove C code that supports AES-GCM nonces that aren't 96 bits

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#22]
It takes a fair amount of code to support these non-optimal nonce lengths. Very few applications will need to support these non-standard nonce lengths and it isn't worth the effort to test the code to verify that it works correctly for them. The ```ring::aead``` interface is much simplified if the nonce length is fixed per ```ring::aead::Algorithm``` instance.

It looks like it will be easier to do this if the non-AEAD AES-GCM interface in crypto/cipher/e_aes.c is removed first.

See Chromium issue https://code.google.com/p/chromium/issues/detail?id=535758.

**Comment by briansmith** [comment]
This was done in commit fa2324001aa786a9d18961ff6edb30247b11ddb9: Remove support for GCM nonces that aren't exactly 96 bits.

**Comment by moparisthebest** [comment]
This makes it impossible to write rust code to inter-operate with some other software that uses 16 byte nonces.  The [rust-crypto library has the same problem](https://github.com/DaGenix/rust-crypto/issues/422).  Examples of software I need to interoperate with are:
https://github.com/moparisthebest/ImageDownloader (C)
https://github.com/iNPUTmice/ImageDownloader (Java)

**Comment by briansmith** [comment]
> This makes it impossible to write rust code to inter-operate with some other software that uses 16 byte nonces. The rust-crypto library has the same problem. Examples of software I need to interoperate with are:
> https://github.com/moparisthebest/ImageDownloader (C)
> https://github.com/iNPUTmice/ImageDownloader (Java)

I'm not sure. It seems likely that the problem due to a bug in that other software, namely that it is using that odd nonce format. It would be good to see the security analysis of that software's use of nonces before we decide to undo this.
