### ISSUE TITLE
Test cases where pbkdf2_hmac panics

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#23]
Currently there are some test cases in pbkdf2_tests.txt that are commented out because they are invalid inputs for _ring_'s PBKDF2 module. In particular, they request an output longer than the output length of the the digest function being used. We should turn those test cases into the equivalent of `[should_panic]`. AFAICT, this means we need to:
1. Uncomment those test cases.
2. Annotate those test cases with "FAILS: OUTPUT_LARGER_THAN_DIGEST_OUTPUT".
3. Change the testing code so that for the cases marked "FAILS: OUTPUT_LARGER_THAN_DIGEST_OUTPUT", a task gets spawned that does the test case. We have to wait for the task to end and then verify that it was ended due to a `panic!`. In other words, we need to create the equivalent of a `[should_panic]` test.

Additionally, we should add more test cases, particularly a test case for `iterations == 0`, as BoringSSL has (had) a bug when `interations == 0`.

AFAICT, this is complicated by https://github.com/rust-lang/rust/issues/25869, as I believe we cannot do `[should_panic]` tests or create a data-driven alternative to `[should_panic]` on Win32 since Rust on Win32 doesn't implement `panic!` correctly; `panic!`` just kills the entire process. We should probably just work around that by not running these tests on Win32.

**Comment by briansmith** [comment]
`#[should_panic]` works on all platforms now and is already being used by some tests. So we can definitely do this now.

**Comment by joshuata** [comment]
I believe this was resolved by f87e2e87 and a316606b

**Comment by briansmith** [comment]
Yes, you're right, given the description above. However, we should add a `#[should_panic]` test for the case where `iterations == 0`, which is the remaining case that can panic.

**Comment by joshuata** [comment]
Okay. I will get on that ASAP.

**Comment by briansmith** [comment]
Fixed in #466. Thanks again, @joshuata.
