### ISSUE TITLE
Replace crypto/modes/gcm.c and crypto/cipher/e_aes.c with Rust code

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#240]
The following should stay as C code: `rem_4bit`, `gcm_gmult_4bit`, `gcm_ghash_4bit`.

Do **NOT** transliterate the C code to Rust. The C code has the wrong license and so we cannot use it, even transliterated to Rust. Instead, write brand-new code.

Don't bother implementing pure Rust implementations of AES or the GHASH function. It's unlikely we'll ever use a pure-Rust implementation any time soon.

This is purely about the layer over the AES and GHASH functions, which combines them together.

I recommend starting out with doing a basic implementation that ignores all the platform-specific issues: i.e. Make replacements for `CRYPTO_gcm128_encrypt_` and `CRYPTO_gcm128_decrypt` and `evp_aead_aes_gcm_open` and `evp_aead_aes_gcm_seal` and `evp_aead_aes_gcm_init_and_aad` in Rust. Hack everything else to get your new code to work, e.g. by hacking `aes_ctr` to return NULL all the time (or whatever is most convenient to get the same effect), and always use `AES_set_encrypt_key` instead of platform-specific logic. K.I.S.S.

Then, get some feedback.

Then, over the course of several commits, deal with all the special cases of platform-specific implementations and other performance optimizations.

Regarding optimization, the main thing to keep in mind is that it is faster to encrypt `GHASH_CHUNK` chunks of bytes and then hash them (or hash `GHASH_CHUNK` bytes and then decrypt them) for some value `GHASH_CHUNK`. In other words, we don't usually encrypt one block and then hash and then encrypt the next block and then hash.... Instead, we do it in chunks. I would take the value of `GHASH_CHUNK` in the C code as a suggestion and keep in mind that it is probably outdated for modern processors. I wouldn't spend too much time optimizing the exact value of GHASH_CHUNK to use, especially on x86-64.

**Comment by briansmith** [comment]
Note that the ChaCha20-Poly1305 code was already done, and it might be useful to read about that work: https://github.com/briansmith/ring/pull/107

**Comment by briansmith** [comment]
I have done some exploratory work on making this doable in PR #369.

**Comment by frewsxcv** [comment]
This seems to overlap with https://github.com/briansmith/ring/issues/85.

**Comment by briansmith** [comment]
Mostly done. The fallback GHash implementation is the only thing left in gcm.c. e_aes.c is gone.
