### ISSUE TITLE
Make it possible to build *ring* from crates.io without yasm and perl installed on Windows

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#241]
* On Windows (x86 and x86-645) we should just pregenerate a .lib file that contains all the objects from the assembly language code, and stuff that into the crate.
* On other platforms, we should pregenerate the assembly language code and also stuff *that* into the package that gets uploaded to crates.io, so that the end-users don't need to have Perl installed.

**Comment by djc** [comment]
I looked into this a little bit the other day (mostly the other platforms part). I think this means that we should generate the assembly language code elsewhere (e.g. not in `OUT_DIR`). I wasn't sure what a good name would be, maybe something like `pregen/asm`? We could generate the `.S` files there, then add them to the Cargo manifest.

**Comment by briansmith** [comment]
499c752af69609ad7029421e9dbd0c3cf6ffb719
fb776c6bc628b2acfdef5f363ec4e113b4fb9275
278cf73cb5839d9cd3598308e18eaa02cd48dcff
6440d1cdad04847b35482f55289bd3eece381980
078d3c2bae08a6db58f636e8ad84bf2c53d09292
f8bb8677e916d693cf3c2fb2bef2a2e6974ec966
caa4df6e680394a5a524d8b9d54e9c341aef65ac
d59b70cec33555c66b4586b2173a3da4eb28ff64
086227aba45bcdfb2ab65d414288683a5967e041
8fcfeb315ee717d7e467ca164879d5b01e46fbe7
