### ISSUE TITLE
Add arm64ilp32 / x32 / IL64P32 targets

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#26]
See https://github.com/openssl/openssl/commit/5e5ece561d1f7e557c8e0ea202a8c1f3008361ce and https://github.com/openssl/openssl/commit/a93d3e06a9849deeceadf1b51c10492ae77c43eb

**Comment by briansmith** [comment]
See https://lwn.net/Articles/456731/

**Comment by briansmith** [comment]
Note that this memory model is only good for cases where ASLR isn't necessary. This is perfect for Rust.

On GCC for MIPS, this is `-mlong32`
On GCC for PowerPOC, this is `-mpowerpc64 -m32`

See ICC's `/Qauto-ilp32 (-auto-ilp32)` https://software.intel.com/en-us/node/523141
> Specifies that the application cannot exceed
a 32-bit address space, which allows the compiler to use 32-bit pointers
whenever possible.

See https://en.wikipedia.org/wiki/X32_ABI:
> The x32 ABI was merged into the Linux kernel for the 3.4 release with support being added to the GNU C Library in version 2.16.

See https://sites.google.com/site/x32abi/
> * Ubuntu 13.04 added x32 support.
> * GCC 4.8.0 has been released with address size prefix improvement. GCC 4.8 is the recommended minimum version of GCC for x32.
> * X32 support is checked into GDB 7.5.
> * X32 support is checked into GLIBC 2.16.
> * X32 support is checked into Linux kernel 3.4.
> ... and more...

See http://lwn.net/Articles/456731/

See http://www-cs-faculty.stanford.edu/~uno/news08.html:
> A Flame About 64-bit Pointers
>
> It is absolutely idiotic to have 64-bit pointers when I compile a program that uses less than 4 gigabytes of RAM. When such pointer values appear inside a struct, they not only waste half the memory, they effectively throw away half of the cache.
>
> The gcc manpage advertises an option "-mlong32" that sounds like what I want. Namely, I think it would compile code for my x86-64 architecture, taking advantage of the extra registers etc., but it would also know that my program is going to live inside a 32-bit virtual address space.
>
> Unfortunately, the -mlong32 option was introduced only for MIPS computers, years ago. Nobody has yet adopted such conventions for today's most popular architecture. Probably that happens because programs compiled with this convention will need to be loaded with a special version of libc.
>
> Please, somebody, make that possible.

**Comment by briansmith** [comment]
Note: Some parts of the code, e.g. gcm.c, use `size_t`, which is 32-bits on these platforms, when instead they should be using `uint64_t` on these platforms. We need to audit the code for all the places where `size_t` is being used for something other than a size.

Similarly, we need to audit the code for places where `int` and `long` and the `unsigned` variants thereof are being used, and replace them with the appropriate type.

**Comment by briansmith** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=219015

**Comment by briansmith** [comment]
https://github.com/rust-lang/rfcs/issues/1339

**Comment by briansmith** [comment]
https://github.com/rust-lang/rfcs/issues/1797

**Comment by sanxiyn** [comment]
x32 landed in Rust.
