### ISSUE TITLE
Implement `fmt::Debug` for `Digest` and possibly `Algorithm`

### ISSUE THREAD

**Issue by tomprogrammer** [briansmith/ring#270]
While refactoring some code to use`ring` I discovered that `Digest` doesn't implement `fmt::Debug`. I worked around that limitation using a newtype wrapper.

 I think that `Digest` as a container of the hash value should implement `fmt::Debug`. I think the output should be a string of hexadecimal numbers. Maybe the algorithm used to calculate the hash value should be printed too?

Do you have any objections or suggestions?

**Comment by briansmith** [comment]
> I worked around that limitation using a newtype wrapper.

Good approach.

> I think that Digest as a container of the hash value should implement fmt::Debug. I think the output should be a string of hexadecimal numbers. Maybe the algorithm used to calculate the hash value should be printed too?

Right now, *ring* doesn't store the names of the algorithms in any strings. If we do this, I'd like to avoid adding the algorithm name to `ring::Digest::Algorithm` and instead have the implementation of `Debug::fmt` map the `ring::Digest::Algorithm::nid` to the string using `match` or similar. This way, we don't increase the size of the compiled code when the `Debug` impl isn't used.

Presumably the output should be something like <digest algorithm name> + ":" + <hex string>.

**Comment by tomprogrammer** [comment]
I agree with you that `ring::digest::Algorithm` shouldn't store the name of the algorithm directly. That is what `fmt::Debug` is made for in my opinion.

I will open a PR implementing your suggestion for the output format.

**Comment by tomprogrammer** [comment]
Closed, cherry-picked #272.
