### ISSUE TITLE
Cannot cross compile macOS (host) to Linux

### ISSUE THREAD

**Issue by nathansizemore** [briansmith/ring#281]
```
$ rustc --version
rustc 1.11.0 (9b21dcd6a 2016-08-15)

$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)

$ perl --version
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
```

```
$ cargo build --target=x86_64-unknown-linux-gnu

--- stderr
/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aes-x86_64.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^
/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aes-x86_64.S:594:8: error: invalid alignment value
.align 64
       ^
make: *** [/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aes-x86_64.o] Error 1
make: *** Waiting for unfinished jobs....
thread 'main' panicked at 'make execution failed', build.rs:212
stack backtrace:
   1:        0x10923b89b - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:        0x10923f2aa - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:        0x10923eeda - std::panicking::default_hook::heb8b6fd640571a4f
   4:        0x109232358 - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:        0x10923f886 - std::panicking::begin_panic::h941ea76fc945d925
   6:        0x1092334c8 - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:        0x10922b4da - build_script_build::run_command_with_args::h61cc2c216e356153
   8:        0x10922596e - build_script_build::build_c_code::ha989d1d039095349
   9:        0x10922313b - build_script_build::main::he5071e1b00fcfe0e
  10:        0x10923eabd - std::panicking::try::call::hca715a47aa047c49
  11:        0x10923f95b - __rust_try
  12:        0x10923f8f5 - __rust_maybe_catch_panic
  13:        0x10923e8e1 - std::rt::lang_start::h162055cb2e4b9fe7
  14:        0x109227219 - main```

**Comment by briansmith** [comment]
Did you configure your .cargo/config to point at a cross-compiling linker? If so, we probably need to do the same to configure the cross-compiling assembler.

The symptoms kind of look like the assembler is too old. What assembler is it?

**Comment by nathansizemore** [comment]
```
$ yasm --version
yasm 1.3.0
```

I'm not actually invoking linking stage with cargo because of needing to hook into epoll syscalls, so that might have something to do with it. I'm just using the `--target` directive, so I can at least make sure rustc is happy before pushing to Linux server for testing.

**Comment by briansmith** [comment]
I think that Linux targets expect a GNU AS or compatible assembler. IIRC, only Windows is set up to use Yasm, and if you were to change the makefile to tell PerlAsm to generate Yasm-compatible stuff, it would probably also generate Windows-specific stuff.

IIUC, cargo and rustc don't know about external assemblers, so they don't know which assembler to invoke. The Makefile will then use `$(AS)`. As a workaround, you can try setting `AS=<your cross-assembler> cargo test --target=i686-unknown-linux-gnu`.

**Comment by nathansizemore** [comment]
Sounds good. Thanks!

**Comment by briansmith** [comment]
Does setting `AS` during the build work?

**Comment by nathansizemore** [comment]
Sorry, closed too early it appears. 

So, after installing x86_64 GNU binutils for as:

```
$ x86_64-unknown-linux-as --version
GNU assembler (GNU Binutils) 2.26.20160125
```

```
$ RUST_BACKTRACE=1 AS=x86_64-unknown-linux-as cargo build --target=x86_64-unknown-linux-gnu

--- stdout
AS: x86_64-unknown-linux-as
RUST_BACKTRACE: 1
SHELL: /bin/bash
RUST_SRC_PATH: /Users/nathan/development/rust/src
RUST_RECURSION_COUNT: 1
RUSTUP_TOOLCHAIN: stable-x86_64-apple-darwin
RUSTUP_HOME: /Users/nathan/.multirust
CARGO_PKG_VERSION: 0.3.0
CARGO_PKG_NAME: ring
CARGO_FEATURE_DEFAULT: 1
DEBUG: true
CARGO_FEATURE_USE_HEAP: 1
OPT_LEVEL: 0
HOST: x86_64-apple-darwin
TARGET: x86_64-unknown-linux-gnu

--- stderr
/Users/nathan/development/ring/target/x86_64-unknown-linux-gnu/debug/build/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aes-x86_64.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^ 

.... Several of those unknown directive errors

/Users/nathan/development/ring/target/x86_64-unknown-linux-gnu/debug/build/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aesni-x86_64.S:1215:8: error: invalid alignment value
.align 64
       ^

... Several of those invalid alignment values

make: *** [/Users/nathan/development/ring/target/x86_64-unknown-linux-gnu/debug/build/ring-772418b28e9a78c5/out/obj/crypto/aes/asm/aesni-x86_64.o] Error 1
thread 'main' panicked at 'make execution failed', build.rs:212
stack backtrace:
   1:        0x10cc9789b - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:        0x10cc9b2aa - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:        0x10cc9aeda - std::panicking::default_hook::heb8b6fd640571a4f
   4:        0x10cc8e358 - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:        0x10cc9b886 - std::panicking::begin_panic::h941ea76fc945d925
   6:        0x10cc8f4c8 - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:        0x10cc874da - build_script_build::run_command_with_args::h61cc2c216e356153
   8:        0x10cc8196e - build_script_build::build_c_code::ha989d1d039095349
   9:        0x10cc7f13b - build_script_build::main::he5071e1b00fcfe0e
  10:        0x10cc9aabd - std::panicking::try::call::hca715a47aa047c49
  11:        0x10cc9b95b - __rust_try
  12:        0x10cc9b8f5 - __rust_maybe_catch_panic
  13:        0x10cc9a8e1 - std::rt::lang_start::h162055cb2e4b9fe7
  14:        0x10cc83219 - main
```

**Comment by briansmith** [comment]
Hi, sorry, I said `$(AS)` but it is probably `$(CC)` that is relevant, because the compilation is done through `$(CC)` in GNU make by default, I believe. Please try setting `$CC` and `$CXX` appropriately and report back.

Also, I think I probably should add support for `$CROSS` or similar so that you can set CROSS=`x86_64-unknown-linux-` and have it automatically prefix things with that prefix.

**Comment by briansmith** [comment]
For example, this is how we do cross-compiling from Linux host to Android targets on Travis CI (simplified):
`CC=arm-linux-androideabi-gcc CXX=arm-linux-androideabi-g++ cargo test`

**Comment by nathansizemore** [comment]
Well, I believe it does have to do with the proper setup of `gcc` and `g++` in the GNU toolchain. I forgot that my toolchain was setup without `glibc` and kernel headers, because I was using it for bare metal stuff, so no libc was needed. Once I set the proper compilers in `${CC}` and `${CXX}`, it started failing on locating `<stdint.h>`, then I remembered I didn't have `glibc` installed.

Unfortunately, I've yet to find a decent way to install `glibc` and kernel headers on macOS. Been compiling/failing all day. Even tried [crosstool-ng](http://crosstool-ng.org/), and it fails as well. From the places I've been today online, it seems people just don't cross compile from `x86_64-apple-darwin` to `x86_64-unknown-linux-gnu`. Or if they do, it is with 3-5+ year old toolchains.

Anyway, thanks for the help!

**Comment by briansmith** [comment]
Do I understand correctly that your target is one that doesn't have libc? I would be happy to help with that, as *ring* is supposed to support bare-metal programming to a certain extent, which will improve over time. In particular, if you build with `cargo build --no-default-features` then some features (RSA signing and, temporarily, RSA verification) that require a C heap will get disabled. However, the Makefiles haven't been modified to skip over the libc-using source files yet and the non-libc-using source files probably haven't been completely scrubbed of unnecessary `#includes`.

This may be something you may be able to help to fix. Otherwise, it is something I will eventually get to.

**Comment by nathansizemore** [comment]
Oh, nope. I'm trying to achieve:

```
host:    x86_64-apple-darwin
target: x86_64-unknown-linux-gnu
```

I had one of my GNU toolchains labeled incorrectly. I think in a few weeks, I might be back here for `aarch64`, and that will be more or less bare, so I might be able to help get the make files setup for that target if troubles arise then.
