### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by badboy** [briansmith/ring#29]
Is there any reason this is not yet published on crates.io?

**Comment by briansmith** [comment]
> Is there any reason this is not yet published on crates.io?

I just haven't gotten around to it yet. I think most people can use `git = "https://github.com/briansmith/ring"` in their Cargo.toml so I'm not sure what the advantage of being on crates.io is.

Can a crate on crates.io use `git = "https://github.com/briansmith/ring"`, or does crates.io require that all the dependencies be on crates.io too?

**Comment by SShrike** [comment]
AFAIK crates on `crates.io` can use Git dependencies, at least last time I checked.

**Comment by badboy** [comment]
Yup, @SShrike is right. Crates on crates.io need to have all their dependencies on crates.io as well.
If no technically reason prohibts that, a release would be nice.

No rush though.

**Comment by briansmith** [comment]
I see. I also verified that that is the case on #rust, though I didn't try it myself.

I am going to shoot for having *ring* on crates.io by the end of the month, if not sooner. I am hoping to improve the AEAD interface and maybe the ECC interfaces before then.

**Comment by badboy** [comment]
<3 Thank you!

**Comment by briansmith** [comment]
An update on this:

I spent some time refactoring the `ring::digest`, `ring::hmac`, and `ring::pbkdf2` APIs in preparation for publishing on crates.io, so that I won't (I hope) need to make breaking changes to them afterward. here are the tasks remaining:

* Refactor the asymmetric crypto API's interface.
* Enable the assembly language optimizations on Windows.

So, I am going to push this back to December.

**Comment by badboy** [comment]
Thanks for the hard work! I really appreciate it.
Better wait for a good and stable version to be released than to rush it.

**Comment by pravic** [comment]
Any progress?

**Comment by briansmith** [comment]
> Any progress?

Yes, actually we've made tons of progress. I think we could do this soon.

**Comment by briansmith** [comment]
I created the milestone [crates.io](https://github.com/briansmith/ring/milestones/crates.io) to track this.

**Comment by pravic** [comment]
Thanks.

**Comment by briansmith** [comment]
Please test out https://crates.io/crates/ring. Thanks!

**Comment by djc** [comment]
Seems to work well on Linux, good stuff!

**Comment by badboy** [comment]
:+1: Just published  [nobsign](https://crates.io/crates/nobsign) to crates.io

**Comment by briansmith** [comment]
Thanks for testing this out! Closing this. Thanks to all the people who contributed to this.
