### ISSUE TITLE
Allow extraction of RSAKeyPair public key components

### ISSUE THREAD

**Issue by djc** [briansmith/ring#299]
So I started implementing _ring_-based crypto in my project, and it turns out I forgot about this part. It needs what is basically a precursor to `signature::primitive::verify_rsa()`: a way to extract `n` and `e` out of an `RSAKeyPair`, similar to `EdDSA`'s `public_key_bytes()`. Does that sound like an okay API to add?

To avoid allocation, it could take a tuple of two `u8` slices as arguments, the first one of which should be exactly `public_modulus_len()` bytes long and the second one just 5 bytes, I guess. So:

`pub fn public_key_components((n, e): (&[u8], &[u8]) -> Result<(), Unspecified>`

It would return `Err` if the slices have incorrect sizes. Otherwise, the argument slices would contain `n` and `e` in big-endian form, similar to how `verify_rsa()` takes them. The zero padding for `e` is a bit awkward, I guess an alternative would be to just take `Vec`s for both?

What do you think? Hopefully this will be easier than the `verify_rsa()` API itself!

**Comment by briansmith** [comment]
> To avoid allocation, it could take a tuple of two u8 slices as arguments, the first one of which should be exactly public_modulus_len() bytes long and the second one just 5 bytes, I guess.

The exponent isn't always 5 bytes. It could be one byte, e.g. when it is 3. So, with this design there would need to be a `public_exponent_len()` function added as well.

> pub fn public_key_components((n, e): (&mut [u8], &mut [u8]) -> Result<(), Unspecified>
> 
> It would return Err if the slices have incorrect sizes. Otherwise, the argument slices would contain n and e in big-endian form, similar to how verify_rsa() takes them.  The zero padding for e is a bit awkward, I guess an alternative would be to just take Vecs for both?

I think it should be the case that the output of `public_key_components()` should be able to be directly fed into `verify_rsa()`, which would mean no padding.

**Comment by djc** [comment]
> I think it should be the case that the output of public_key_components() should be able to be directly fed into verify_rsa(), which would mean no padding.

That sounds right. So we pass in a slice of at least `public_modulus_len()` + 5, and it will return slices matching the lifetime of the argument?

**Comment by briansmith** [comment]
I would expect something like this (which, I guess, should appear in a doc comment:

```
let n = vec![0, key_pair.public_modulus_len()];
let e = vec![0, key_pair.public_exponent_len()];
try!(key_pair.public_key_components(&mut n, &mut e));
let public_key = (untrusted::Input::from(&n), untrusted::Input::from(&e));
signature::verify_rsa(..., public_key, ...);
````

**Comment by briansmith** [comment]
This is done:

```rust
struct RsaPublicKey {
    pub fn modulus(&self) -> io::Positive { ... }
    pub fn exponent(&self) -> io::Positive { ... }
}
```
