### ISSUE TITLE
Add support for verifying ECDSA signatures in PKCS#11 form r||s where r and s are fixed length

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#302]
This is needed for web crypto support, PKCS#11 interop, and for DNSSEC.

We'll add `_FIXED` variants of all the ECDSA signature algorithms. e.g. `ECDSA_P256_SHA256_ASN1` -> `ECDSA_P256_SHA256_FIXED`.

**Comment by briansmith** [comment]
This is also needed for JWK/JWA/JWT support: https://tools.ietf.org/html/rfc7518#section-3.4

**Comment by alex** [comment]
SSH as well, IIRC

**Comment by briansmith** [comment]
SSH chooses the digest algorithm based on the size of the curve: https://tools.ietf.org/html/rfc5656#section-6.2.1.

DNSSEC does similar: https://tools.ietf.org/html/rfc6605#section-4.

The Web Crypto API recommends "ECDSA using P-256 curve and SHA-256" as the suggested ECDSA support: https://w3c.github.io/webcrypto/Overview.html#algorithm-recommendations-implementers.

Therefore, it seems like for this we only need to support P-256 with SHA-256 and P-384 with SHA-384. This is different than what we need to do for the ASN.1 encoding of signatures, where compatibility issues force us to support P-256 + SHA-384 and P-384 + SHA-256.

**Comment by briansmith** [comment]
This was implemented in a13b8e279e30c2b296ef0dae5843837da7ea51e9, which will be in *ring* 0.7.4.

**Comment by andrewtj** [comment]
@briansmith as only uncompressed public keys are supported, could the leading encoding byte be dropped? This would allow DNSSEC public keys to be used without copying.

**Comment by briansmith** [comment]
> @briansmith as only uncompressed public keys are supported, could the leading encoding byte be dropped? This would allow DNSSEC public keys to be used without copying.

I have no plans to make that change now. I understand why that would be convenient. I can think of some reasons to leave things the way they are too. I made a note to re-evaluate this in the future. In the meantime, I would recommend that a DNSSEC library take advantage of the fact that ECC public keys are always small to avoid allocations when reformatting such public keys.
