### ISSUE TITLE
Allow applications to use RDRAND/RDSEED instead of OS PRNG on x86/x64

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#327]
RDRAND/RDSEED will not be the default on any platform, but there should be some way to use it in specific scenerios where `getrandom()` and reading from `/dev/[u]random` and similar can't be used.

See https://software.intel.com/en-us/blogs/2012/11/17/the-difference-between-rdrand-and-rdseed for a good description of the differences between RDRAND and RDSEED.

It may be a good idea to provide a way to use RDRAND/RDSEED in conjunction with some other PRNG like BoringSSL does, to reduce concerns about the safety of relying on RDRAND/RDSEED being secure.

**Comment by briansmith** [comment]
RDSEED is only available on Broadwell and later. It is OK if this feature only works on Broadwell and later.

**Comment by nagisa** [comment]
https://crates.io/crates/rdrand
