### ISSUE TITLE
Remove ECDSA {P-256, P-384}+SHA-512 signature algorithms

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#332]
The Chromium/BoringSSL team showed that it isn't necessary to support ECDSA with SHA-512 for the P-256 and P-384 curves for HTTPS; see https://groups.google.com/a/chromium.org/d/msg/security-dev/SlfABuvvQas/qOil2X4UBQAJ. Accordingly, we should be able to remove `ECDSA_P256_SHA512_ASN1` and `ECDSA_P384_SHA512_ASN1` without negatively affecting anybody. Let's do that.

One complication is that the test for #244 uses P-256 + SHA-512, for some reason. @ctz, is there any particular reason you used SHA-512 there? Do you know of any reason to keep supporting these?

**Comment by ctz** [comment]
That test is from a TLS transcript between rustls and cloudflare, and rustls has a [fairly basic ordering](https://github.com/ctz/rustls/blob/7af1e3eb1bf33c3c632608131f97d982d7049f77/src/msgs/handshake.rs#L202) that prefers SHA512 most. Presumably cloudflare supports that and respects our preference. I can make a new test vector with a different hash, it only takes a hundred-ish connections.

**Comment by briansmith** [comment]
> I can make a new test vector with a different hash, it only takes a hundred-ish connections.

Thanks for the info. No need to generate new test vectors, as I've done that in  257b3898697153da4d2f2e3dd8cf89c00d4e8edb, which uses SHA-256 with P-256 and also adds P-384 + SHA-384 variants. I verified that these test vectors triggered a failure using the old implementation.

This issue is fixed with c5b81134c8fc747793dc8cda39acc32d2c27c1d2, which removes the `ECDSA_*_SHA512` algorithms, and 66602e73100bdcca7d124f4d90a46c1d57f5f161, which clarifies the documentation of the P-256+SHA-384 and P-384+SHA-256 variants.
