### ISSUE TITLE
Support building with MSVC even when the Windows XP compatibility support isn't installed

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#336]
From #330:

> I tried to open the ring.sln in Visual Studio and it complained about a missing C++ support for Windows XP. So I installed that, now the project loads and it builds without errors in Visual Studio.

Since stock rustc doesn't support Windows XP as a target, we should only use the Windows-XP-compatible toolchain when it is specifically requested, probably.

**Comment by briansmith** [comment]
I filed https://github.com/rust-lang/rust/issues/37638 to get the Rust toolchain to give us the necessary information. Also, extending #321 to -MSVC targets might make this partially or completely unnecessary. Conversely, we might not be able to extend #321 to non-MSVC targets easily if the gcc crate can't handle this.

In the meantime, we could add a "xp-compatible" feature to *ring* that is off-by-default, and which can be enabled by the application if they want to target XP too.

**Comment by briansmith** [comment]
Note that since we don't test on Windows XP, we might be relying on features that don't even work on Windows XP. So, we should probably just change the default now and punt the real Windows XP support to another bug.

**Comment by briansmith** [comment]
I've changed the toolchain from "v140_xp" to "v140" in c96d59a7605774c12c528bb5f65b14c0b92f6cf3, dropping XP support, which probably didn't work anyway. #339 is the issue tracking (re-)adding XP support.

**Comment by lygstate** [comment]
We only need add a link parameter to make sure the subsystem to be 5.01, there is no need the toolchain v140_xp

**Comment by briansmith** [comment]
> We only need add a link parameter to make sure the subsystem to be 5.01, there is no need the toolchain v140_xp

I'd like to see some documentation for this. In particular, I'd like to see some documentation that says it's OK to compile C and C++ code using MSVC toolchain v140 and then run the resulting code on XP.

**Comment by lygstate** [comment]
@briansmith, Well, that's for sure, I am tested with that, and v140_xp are also do the same things.
Besides, Chrome also do that before when Windows XP support are not dropped yet.
