### ISSUE TITLE
Add Visual Studio 2017 builds to AppVeyor

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#338]
[Note that Visual Studio “15” is the successor to Visual Studio 2015 and will probably have a different name; see https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes.]

Let's support building the C/C++ components with Visual Studio “15” and using its linker.

The AppVeyor issue for Visual Studio “15” support is https://github.com/appveyor/ci/issues/753, where they say they'll wait at least until there's a beta release. But, we'll take patches to support it in *ring* before then.

**Comment by briansmith** [comment]
This may blocked on rustc/cargo adding support for VS2017. See https://github.com/rust-lang/rust/issues/38584.

**Comment by sanmai-NL** [comment]
@briansmith 
> This may blocked on rustc/cargo adding support for VS2017. See rust-lang/rust#38584.

It seems that issue’s been resolved. Also, I didn’t have problems compiling a crate that uses ring 0.13alpha on an instance of the [Windows 10 development VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines), which seems to only contain Visual Studio 2017. So it now comes down to modifying the AppVeyor config, right?

**Comment by davlia** [comment]
Currently still experiencing this issue on Windows 10 using VS 2017 build toolchain

**Comment by davlia** [comment]
Manage to fix the issue by setting some environment variables `set CL="/wd5045"`. I also verified that my rust triple was correct: `x86_64-pc-windows-msvc`. @trsh

**Comment by Szczurowski** [comment]
On my 15.7.4 the build fails :( Although I set the CL env-var.
BTW: here's a bit info about linker:
:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26431 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

**Comment by dmitry-vorobiev** [comment]
> set CL="/wd5045"
Thanks, it helped me))

I ran into the same issue with VS 15.7.5

**Comment by briansmith** [comment]
Probably not going to add Visual Studio 2017 coverage given 2019 has been out for a while, and due to CI/CD constraints.
