### ISSUE TITLE
Use `BitLength` in FFI when transparent structs are supported

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#345]
Example before:
```rust
        fn GFp_AES_set_encrypt_key(key: *const u8, bits: usize,
                                   aes_key: *mut AES_KEY) -> c::int;
```

Example after:
```rust
        fn GFp_AES_set_encrypt_key(key: *const u8, bits: BitLength,
                                   aes_key: *mut AES_KEY) -> c::int;
```

This depends on https://github.com/rust-lang/rfcs/pull/1758.

**Comment by briansmith** [comment]
The rust feature is being tracked in https://github.com/rust-lang/rust/issues/43036

**Comment by pietro** [comment]
The FFI functions use `c::uint` instead of `usize`. I don't think there's any length that would overflow `u32` but on most 64-bit platforms we would still convert from `u64` to `u32` (I think).

**Comment by pietro** [comment]
I added the `#[repr(transparent)]` to `BitLenght` and changed the functions on `aes.rs` to use `BitLenght` instead of `c::uint` in pietro/ring@0db50fa6d9257cdb29c0dfdd5949349e2c5de3f4.

**Comment by briansmith** [comment]
In BoringSSL, David Benjamin did some analysis and determined that, in general, we have to be very careful in changing the `int`, `unsigned`, `size_t`, etc. types in assembly language function declarations. In particular, if a function is expecting an `unsigned` but we change the declaration to `usize` then it might incorrectly zero out the high bits of the argument (if `usize` is larger than `int`/`unsigned`). In the case of `set_encrypt_key` it probably doesn't matter because the valid values are well within the range of `unsigned`, but also I don't see a lot of value in changing the declaration.

More generally, we now very rarely pass bit lengths to the C/asm code so I don't think it's worth even thinking about this as a TODO item.
