### ISSUE TITLE
Use `BitLength` in constant expressions when `const_fn` is stable

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#346]
Example before:
```rust
        pub static $NAME: agreement::Algorithm = agreement::Algorithm {
            i: ec::AgreementAlgorithmImpl {
                public_key_len: 1 + (2 * (($bits + 7) / 8)),
                elem_and_scalar_len: ($bits + 7) / 8,
                [...]
            },
        };
```

Example after:
```
        pub static $NAME: agreement::Algorithm = agreement::Algorithm {
            i: ec::AgreementAlgorithmImpl {
                public_key_len: 1 + (2 * $bits.as_usize_bytes()),
                elem_and_scalar_len: $bits.as_usize_bytes(),
                [...]
            },
        };
```

This depends on https://github.com/rust-lang/rust/issues/24111 since `as_usize_bytes()` and the constructors for `BitLength` must be constant functions.

**Comment by briansmith** [comment]
> I created a new function `as_usize_bytes`

I don't have a strong preference here. Generally I prefer the code to avoid `panic!` so `as_usize_bytes_rounded_up` variant seems better with that in mind, because it is clear it will never panic and it is clear that it rounds. Maybe in the future we can get type-level programming in Rust such that we can restrict the input type to a multiple of 8. Alternatively, we could flip the definitions around so that the `xxx_BITS` variables are defined to have value `8 * xxx_BYTES`. I don't have strong feelings either way there.

**Comment by pietro** [comment]
I pushed a commit using `as_usize_bytes_rounded_up`. It will break `no_heap` builds though.

**Comment by briansmith** [comment]
> I pushed a commit using `as_usize_bytes_rounded_up`. It will break `no_heap` builds though.

IIRC, that function is marked `#[cfg(feature = "use_heap")]` only because it is only used by other functions that are marked that way. In other words, it is right to remove the `#[cfg(feature = "use_heap")]` if that is needed to make the no-heap builds work.
