### ISSUE TITLE
Restrict RSA *private* keys to public moduli that are a multiple of 1024 bits.

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#401]
I don't know of any uses of (two-prime) RSA keys that have a public key modulus larger than 2048 bits that aren't still a multiple of 1024 bits, but we have non-trivial complexity to do exponentiation for oddly-sized keys. Quite a bit of that non-trivial complexity isn't being tested because we're only testing with 1024- and 2048- bit keys from NIST test vectors.

Rather than build awkward-sized test vectors, let's just drop support for awkward-sized keys.

**Comment by briansmith** [comment]
@ctz Do you see this as being problematic for Rustls?

**Comment by ctz** [comment]
I don't think so, but it would be nice if the error that results is distinctive. See also https://github.com/ctz/rustls/issues/26

**Comment by briansmith** [comment]
I'll try to get #384 landed so that we can provide a detailed error code for when an unsupported size is used.

**Comment by briansmith** [comment]
There might not be much advantage to restricting to 1024-bit multiples but some code works better if we restrict things to, e.g. 8 64-bit limbs, which is similar to, but not quite the same as, requiring the key to be a multiple of 512 bits.

**Comment by briansmith** [comment]
> There might not be much advantage to restricting to 1024-bit multiples but some code works better if we restrict things to, e.g. 8 64-bit limbs

Note that for a long time, on x86-64, *ring* required the RSA private key `q` and `p` values to be multiples of 8 64-bit limbs, somewhat accidentally, and in the next release, 0.13.0, this will be the case for all platforms. This allows us to eliminate an otherwise duplicate code path for handling weirdly-sized keys.

**Comment by briansmith** [comment]
97d5877fbf8605d2c3aacb19c709a1ce40e672bc now enforces this at key construction time for all platforms. Previously, this was only enforced on x86-64, and it was only enforced at signature time. That was confusing. Now things should be less confusing. This will be part of 0.14.
