### ISSUE TITLE
Fragment identifier broken in README.

### ISSUE THREAD

**Issue by frewsxcv** [briansmith/ring#404]
https://github.com/briansmith/ring#documentation

links to

https://github.com/briansmith/ring/blob/master/BUILDING.md#building-the-rust-library

which has the fragment identifier `#building-the-rust-library`, but that heading does not exist on the subsequent page.

**Comment by briansmith** [comment]
Thanks! Fixed in 7e82a1faa970b1bc965945ec6d28845f1ad19f4d.
