### ISSUE TITLE
Crashing bug using reference to digest::SHA1

### ISSUE THREAD

**Issue by badboy** [briansmith/ring#41]
When using your proposed code directly (badboy/nobsign/issues/2) I hit a bug crashing (and coredumping) the compiler.

This little piece of Rust reproduces it:

```rust
extern crate ring;

static _ALGORITHM: &'static ring::digest::Algorithm = &ring::digest::SHA1;

pub fn bug() {
    vec![0u8; ring::digest::SHA1.digest_len];
}
```

Compiling that (add this repo as a dependency to a crate, then `cargo build`) leads to:

```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Constants.cpp:2044: static llvm::Constant* llvm::ConstantExpr::getGetElementPtr(llvm::Type*, llvm::Constant*, llvm::ArrayRef<llvm::Value*>, bool, llvm::Type*): Assertion `DestTy && "GEP indices invalid!"' failed.
```

and a coredump.

@kimundi was so nice to explain a bit:

> library does wrong unsafe things => invariants are violated => rust compiler emits IR with UB to llvm => llvm in debug mode checks somke of the invariants and triggers an assertion error => assertion do abort the process => abort is implemented as a invalid instruction => core dump

It seems that this usage of references to `digest::SHA1` (which [itself is a static](https://github.com/briansmith/ring/blob/master/src/digest.rs#L207)) leads to this undefined behavior.

Of course it might be nice if rustc can prevent this.
But nevertheless ring should try to provide safe abstractions.

**Comment by briansmith** [comment]
Thanks for the bug report. It is definitely concerning.

@badboy @kimundi Could you fill me in on more details of your conversation. I am open to the idea that *ring* is doing something wrong, but from the description above it isn't clear what *ring* could be doing wrong. It seems purely like a compiler bug to me.

Still investigating.

**Comment by briansmith** [comment]
I have created a minimal test case for the rustc bug that doesn't use *ring* at all. So, *ring* isn't the problem. If the coding pattern I'm using related to how `static`s are used is wrong, then I think people will clue me in in the rust bug report, https://github.com/rust-lang/rust/issues/29265.

**Comment by badboy** [comment]
Thanks for the quick investigation. Let's fix rustc instead!

**Comment by briansmith** [comment]
I'm going to close this since it is a rustc issue, not a *ring* issue. Thanks for reporting it though!
