### ISSUE TITLE
Build release builds with debug info

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#44]
See https://llvm.org/bugs/show_bug.cgi?id=15393. Building with debug info breaks the Windows build, so we can't build with debug = true yet.

**Comment by briansmith** [comment]
I reported the bug as Rust https://github.com/rust-lang/rust/issues/29413. I filed Cargo https://github.com/rust-lang/cargo/issues/2087 to add a workaround to Cargo.

**Comment by briansmith** [comment]
See also https://github.com/rust-lang/rust/issues/28947

**Comment by briansmith** [comment]
See also https://github.com/rust-lang/rust/issues/34122

**Comment by jonas-schievink** [comment]
I've replaced `debug = false` with `debug = true` and it seems to build fine now
