### ISSUE TITLE
HMAC: Split `hmac::SigningKey::new`

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#447]
We have this code in `hmac::SigningKey::new`

```rust
    pub fn new(digest_alg: &'static digest::Algorithm, key_value: &[u8])
               -> SigningKey {
        …

        let key_value = if key_value.len() <= digest_alg.block_len {
            key_value
        } else {
            key_hash = digest::digest(digest_alg, key_value);
            key_hash.as_ref()
        };

        …
    }

```

I want to experiment with changing `hmac::SigningKey::new()` and `hmac::VerificationKey::new()` to require `key_value <= digest_alg.block_len`; i.e. dropping the `} else {` above. to do that, I think we should create a new constructor like this:

```rust
    pub fn new_deprecated(digest_alg: &'static digest::Algorithm, key_value: &[u8])
               -> SigningKey {
        …

        let key_value = if key_value.len() <= digest_alg.block_len {
            key_value
        } else {
            key_hash = digest::digest(digest_alg, key_value);
            key_hash.as_ref()
        };
        new(digest_alg, key_value)
    }
```

Then we can remove that logic from `new()` and update its documentation. The documentation for `new_deprecated()` should explain why we discourage it. See https://www.ietf.org/mail-archive/web/cfrg/current/msg08942.html (the whole thread).

PBKDF2 would need to change to use `new_deprecated()`.

Another open question: Can we require in `new()` that `key_value.len() >= digest_alg.output_len` in addition to the aforementioned change to require `key_value <= digest_alg.block_len`? If we can, then we'll reject many improper uses of HMAC where the key is a password instead of a proper key, and we can give people advice about using PBKDF2 or similar key stretching instead of using a password as the key.

**Comment by 46bit** [comment]
Hiya. I can go ahead and implement the first item of this with a little guidance.

* Should the replacement `new` not perform this check, or should it perform the check and return `Result<SigningKey, ?>` to allow for failure? I'm guessing the latter.

When it comes answering the second item, my first idea was to comment out `new` and see from the compile errors what is using it. I could then read about each and conclude whether there might be an issue. This seems a little extended a project. Is the testsuite sufficient or is there a better path you could suggest?

Cheers!

**Comment by briansmith** [comment]
Going to close this. At the time I filed this, it seemed like a good idea. But, practically speaking, we're not really here to help people design their own new protocols; instead we're here to help people implement existing protocols, and the specs for those protocols will already handle this, so it's not worthwhile.
