### ISSUE TITLE
Remove rustc_serialize dependency

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#452]
#378 adds a new dev_dependency on rustc_serialize, which is deprecated and larger than what we need. Let's replace that dependency with a dependency on a smaller base64-specific crate.

**Comment by briansmith** [comment]
In the case of the tests added in ring/src/der.rs, it seems like we can just extract the base64 parts of the input files and have the test files use the binary (base64-decoded) encoding, so we won't need a base64 library at all.

**Comment by marshallpierce** [comment]
I just rewrote most of https://github.com/alicemaz/rust-base64 to be as fast as I could make it, so see if that suits you. The encode optimizations are still waiting in a PR, but the decode side is in.

If it doesn't seem suitable, I'd be curious to know why so I can fix it!

**Comment by briansmith** [comment]
> just rewrote most of https://github.com/alicemaz/rust-base64 to be as fast as I could make it, so see if that suits you. The encode optimizations are still waiting in a PR, but the decode side is in.
> 
> If it doesn't seem suitable, I'd be curious to know why so I can fix it!

That seems like the best choice. Not too concerned about the performance since this is a dev-dependency only. More concerned about correctness and testing.

**Comment by marshallpierce** [comment]
I added a lot of testing while I was in there, including various flavors of random input for both decoding and encoding. I'm pretty confident in it, but I'm happy to take feedback on how the tests could be more robust.

**Comment by marshallpierce** [comment]
Should be addressed by https://github.com/briansmith/ring/pull/378/commits/234c327e8dac0b628e8883a60238793ad9fa2510.

**Comment by briansmith** [comment]
*ring* no longer depends on rustc-serialize.
