### ISSUE TITLE
Rewrite `GFp_ed25519_sign()`, `GFp_ed25519_verify()`, and `GFp_ed25519_public_from_private()` in Rust

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#459]
The most immediate goal is to get rid of the `GFp_SHA512_4()` function. That weird function calculates a SHA-512 hash over up to 4 byte arrays. In Rust code, it can be replaced with use of `digest::digest()` for the single-item case, or use of `digest::Context` for the multi-item case.

The longer-term goal is to move the Ed25519 code to Rust.

For this step, let's just replace `GFp_ed25519_verify()`, `GFp_ed25519_sign()`, and `GFp_ed25519_public_from_private()`, while keeping all the underlying functions in C.

This is easier than it sounds because it's basically just transliteration from C to Rust.

To demonstrate the approach that I think is best, I've done `GFp_ed25519_public_from_private()` in the [ed25519-rust](https://github.com/briansmith/ring/tree/ed25519-rust) branch.

The main issue that we need to keep track of is performance. We need to make sure the refactoring doesn't regress performance.

**Comment by newpavlov** [comment]
How about using [`ed25519-dalek`](https://github.com/isislovecruft/ed25519-dalek) for it? (it could be published under `ed25519` later) If you don't want to depend on it, code can be copy-pasted with necessary changes (e.g. replace sha2 crate dependency with ring implementation). As I understand CC-0 license should allow it without any complications.

**Comment by briansmith** [comment]
Using ed25519-dalek is a possibility I'm considering. However, I want to experiment with improving the *ring* implementation, such as doing things like this, first.

**Comment by ranweiler** [comment]
@briansmith, my schedule is finally settling down again, so I'm picking this up.

**Comment by ranweiler** [comment]
Opened https://github.com/briansmith/crypto-bench/pull/27 to support the performance side of this issue.

**Comment by briansmith** [comment]
I'm closing this with the understanding that it is all done.
