### ISSUE TITLE
Improve consistency of `Algorithm` attributes & accessors

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#461]
`ring::digest::Algorithm` uses public attributes, not functions, to expose algorithm properties like `output_len`, `chaining_len`, etc. But, `ring::aead::Algorithm` uses accessor functions like `tag_len()` instead. This is confusing. The original motivation for doing things the current way might no longer be valid.

**Comment by ocrickard** [comment]
What's the status of these commits?

**Comment by Zeromika** [comment]
What's the status of this issue, I am interested in picking it up.

**Comment by briansmith** [comment]
0.17.0 addressed this for `digest::Algorithm`.
