### ISSUE TITLE
X448 / Ed448 / Ed25519 support

### ISSUE THREAD

**Issue by TerraX-net** [briansmith/ring#462]
Quote from https://github.com/ctz/rustls/issues/52

> X448 is a perfect replacement for secp521r1 to gain "level 8" security here: https://www.keylength.com/en/3/
> 
> Ed25519 and Ed448 are needed for DNSSEC resolvers and servers anyway:
> [RFC8080: Edwards-Curve Digital Security Algorithm (EdDSA) for DNSSEC](https://tools.ietf.org/html/rfc8080)
> And when those dns replies [get stapled into the tls handshake](https://bugzilla.mozilla.org/show_bug.cgi?id=672600#c65), Firefox (and other tls clients) should be able to handle both.
> 
> 
> [btls](https://gitlab.com/ilari_l/btls) has both, but no TLS 1.3.
> Maybe this would be something for ring, @briansmith. (You convinced me that P-521 has no future.)

**Comment by briansmith** [comment]
@TerraX-net we already have Ed25519 and X25519. Please file a separate issue for X448 and/or a separate issue for Ed448 if you want those to be added.
