### ISSUE TITLE
.der enocded RSA public key in test does not appear to be a valid key

### ISSUE THREAD

**Issue by heartsucker** [briansmith/ring#470]
I noticed this when I was unable to get the `ring` library to verify an RSASSA-PSS signature.

```
heartsucker@pythagoras:~/code/misc/ring (master)$ openssl version
OpenSSL 1.1.0e  16 Feb 2017
heartsucker@pythagoras:~/code/misc/ring (master)$ openssl rsa -pubin -in ./src/rsa/signature_rsa_example_public_key.der -inform DER -outform PEM 
unable to load Public Key
139706476819648:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1112:
139706476819648:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:274:Type=X509_ALGOR
139706476819648:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:609:Field=algor, Type=X509_PUBKEY
```

**Comment by lawliet89** [comment]
Try it with `openssl rsa -RSAPublicKey_in -in ./src/rsa/signature_rsa_example_public_key.der -inform DER -outform PEM ` instead.

The `RSAPublicKey_in` is different.

**Comment by briansmith** [comment]
Thanks to both of you for pointing this out. I'm going to close this in favor of landing #472, which will hopefully clear things up. I suspect #384 will also help people learn the right format to use. Also #378 will add support for parsing the RSAPublicKey format out of SubjectPublicKeyInfo format keys.
