### ISSUE TITLE
Switch from GCC to clang for android builds

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#473]
Currently we use `arm-linux-androideabi-gcc` and `arm-linux-androideabi-g++` for Android builds. According to [the NDK 14 changelog](https://github.com/android-ndk/ndk/wiki/Changelog-r14), support for GCC is deprecated in the NDK. So, let's switch to clang.

**Comment by briansmith** [comment]
Fixed by #480.

**Comment by briansmith** [comment]
Reopining because I rolled this back in 63691d4245866c6081b9cc89aa5a0a94f90532ae since switching to clang seems to have broke things. Thanks to @pietro for pointing out the bustage.

**Comment by pietro** [comment]
I got AArch64 working when using clang by defining `BORINGSSL_CLANG_SUPPORTS_DOT_ARCH` and passing the flag `-fno-integrated-as`.

I haven't found the right flags to get 32 bit arm working with clang.

**Comment by briansmith** [comment]
For the record, this was done in 72d3b9d3ba8dcab5da235b10fc67c69b33ff3591 (PR #652) back on May 18, 2018.
