### ISSUE TITLE
Use Android NDK 14 on Travis CI

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#474]
Android NDK 14 will become the minimum supported version of the NDK for *ring*. We should use it on Travis CI instead of NDK 10e.

The changelog for NDK 14 is here: https://github.com/android-ndk/ndk/wiki/Changelog-r14. We might benefit from switching to use the "unified headers". We may also benefit from other changes I'm not aware of, including in particular improvements in r13, r12, r11, etc.

**Comment by briansmith** [comment]
I think this is fully fixed in #478. @pietro Is there anything left to do?

**Comment by pietro** [comment]
We still need to switch to unified headers . You already picked up the change to export the android api level on build.rs so we need to pass the right args to the ndk install script. I have that stashed on my repo and I'll submit a PR for that in a couple of hours.

**Comment by pietro** [comment]
Sorry I got confused. This issue can be closed. I'll work on using clang for android builds.

**Comment by briansmith** [comment]
OK, thanks again!
