### ISSUE TITLE
Ios simuator and new build

### ISSUE THREAD

**Issue by kali** [briansmith/ring#475]
Since #321, the build to the ios simulator is broken. I think it's because some assembly sources with pure GCC syntax are included on the build:

```
"cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-m64" "-mios-simulator-version-min=7.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk" "-I" "include" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Werror" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-o/Users/kali/dev/snips/ring/target/x86_64-apple-ios/debug/build/ring-f803c09579669be5/out/sha512-x86_64.o" "/Users/kali/dev/snips/ring/target/x86_64-apple-ios/debug/build/ring-f803c09579669be5/out/sha512-x86_64.S"

--- stderr
/Users/kali/dev/snips/ring/target/x86_64-apple-ios/debug/build/ring-f803c09579669be5/out/x86_64-mont.S:5:1: error: unknown directive
.hidden GFp_ia32cap_P
^
/Users/kali/dev/snips/ring/target/x86_64-apple-ios/debug/build/ring-f803c09579669be5/out/aesni-x86_64.S:4:1: error: unknown directive
.hidden GFp_ia32cap_P
^
/Users/kali/dev/snips/ring/target/x86_64-apple-ios/debug/build/ring-f803c09579669be5/out/aes-x86_64.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^
```

... and so on.

We can try and fix them, like we did a few weeks ago for the arm curve thing. Or we can be more specific when including assembly sources in build_c_code by separating clang target. Do we still have some assembly files with clang-compatible syntax ?

**Comment by briansmith** [comment]
Thanks for checking this.

I think these files were always included in the build. Otherwise RSA and ECC stuff wouldn't work in the simulator.

Probably the issue is that the command line for "perl" is passing the wrong value on the command line for the simulator. I suggest looking at the build output (`cargo build -vv`) of a working build and comparing its output to the build output of a broken build, especially in the area of the perl invocations.

It's probably a one-line fix.

**Comment by briansmith** [comment]
According to #584 this was fixed.
