### ISSUE TITLE
Remove the C++ Dependency

### ISSUE THREAD

**Issue by mitsuhiko** [briansmith/ring#477]
Currently the build process seems to have two c++ dependencies which causes issues for me compiling for musl with cross where no C++ compiler is available. This is caused by the `RING_TEST_SRCS` list of libraries.

Is there any way this could be removed? There is currently a comment that says this ideally only compiles during test but I do not see how this could be accomplished easily.

**Comment by briansmith** [comment]
In the short term, I would accept a patch that adds a default feature "bn_tests" that controls whether bn_test.cc (and the other C++ stuff it depends on) gets built, linked, and run.

In the longer term, we're rewriting all the functionality that bn_test.cc tests, and we're replacing the contents of bn_test.cc with Rust code as we do that. So all the C++ code will go away naturally on its own.

**Comment by steveatinfincia** [comment]
@briansmith will something like this work? https://github.com/infincia/ring/commit/655d7ce15841237ebdc5d41c3100a242a8befca2

**Comment by briansmith** [comment]
I removed the C++ dependency in efdffc91db7adb9923a6635ebdd49829db61d7cb.
