### ISSUE TITLE
Switch from arm-android-linuxeabi to armv7-android-linuxeabi on Travis CI

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#482]
I think we should switch to armv7-android-linuxeabi, because it is built with -mthumb (IIUC), whereas arm-android-linuxeabi isn't. We'd need to ensure that `-mthumb` gets passed to the C and C++ compilers and the assembler properly.

WDYT @pietro?

**Comment by briansmith** [comment]
See https://internals.rust-lang.org/t/what-is-the-current-status-of-arm-linux-androideabi/4507/3:
> When the armv7-android-linuxeabi target was added, the plan was to eventually change Rust's arm-linux-androideabi target to no longer target ARMv7 but instead to match Android's armeabi ABI. This wasn't done immediately in order to allow time for existing crates to migrate to the new ARMv7 target. That was about six months ago; it's probably a good time to push forward with this.

**Comment by pietro** [comment]
I was about to write a comment in one of the android issues about that. I think we need to pass`-march` on #480 because the target is set to `arm-android-linuxeabi` instead of `armv7-android-linuxeabi`.  We should be able to pass `-mthumb` too. I'll work on this issue and the compiler flags after clang on android lands.

**Comment by briansmith** [comment]
What you're suggesting sounds good to me, IIUC.

**Comment by pietro** [comment]
I didn't have time to figure out why building with clang for android fails so I went ahead and switched travis to armv7 on #488. I'll work on #486 before resuming working on clang.

**Comment by briansmith** [comment]
Fixed by #488. Thanks again!
