### ISSUE TITLE
Improve ARM build options

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#490]
@pietro wrote:
> According to [this](https://developer.android.com/ndk/guides/standalone_toolchain.html#abi_compatibility) we should also pass `-mfloat-abi=softfp`. We may also want to pass `-thumb` and `-mfpu=neon` and lean on on the runtime detection for arm cpu features. There's also the recommended flags to the linker that we may want to pass to both gcc and rustc.

**Comment by pietro** [comment]
Because the other ARMv7 flags are added by the gcc crate I submitted a [PR](alexcrichton/gcc-rs/#148) to it adding `-mfloat-abi=softfp`.

**Comment by pietro** [comment]
The float ABI option patch was merged into gcc-rs. Hopefully there will be a new release of the crate soon.

**Comment by briansmith** [comment]
Thanks to @pietro's patch to cc-rs, I think this is done automatically for us.
