### ISSUE TITLE
Does not compile with older versions of GCC

### ISSUE THREAD

**Issue by kardeiz** [briansmith/ring#498]
When I try to compile `ring` (which I am using via the `cookie` crate), I get the following errors:

```
cc1: warnings being treated as errors
cc1: error: command line option "-Wenum-compare" is valid for C++/ObjC++ but not for C
cc1: error: unrecognized command line option "-std=c1x"
[...]
```

I'm using RedHat 6.8, which provides only GCC 4.4.7.

**Comment by briansmith** [comment]
I currently don't have any plans to support such ancient compilers. In theory it could be done; if it is important then please send me an email: brian@briansmith.org.

**Comment by kardeiz** [comment]
Thanks for the response! I totally understand not wanting to support old compilers, though I would argue that RedHat 6 is not obsolete (it's old but not near end of life).

In any case, I just discovered that RH has a Software Collection [devtoolset-6](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/) that provides newer versions of gcc and c++. For anyone else encountering this issue: follow the directions at that page, and then set env vars `CC`, `CXX`, and `CPP` to the newly installed files (all within `/opt/rh/devtoolset-6/`).

**Comment by briansmith** [comment]
Thanks for sharing that!
