### ISSUE TITLE
"ignoring unknown option '/utf-8'" causing the build to fail

### ISSUE THREAD

**Issue by r3c0d3x** [briansmith/ring#502]
`cargo` is attempting to build `ring 0.7.3` as a dependency for a crate I'm using, but `build.rs` appears to be [misinterpreting](https://github.com/briansmith/ring/blob/8a46eb57b861973c934f6df034ac9c4c24e425c5/build.rs#L712) a warning from the compiler as an actual error (because it outputs warnings using stderr).

```
--- stderr
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
thread '<unnamed>' panicked at 'execution failed', C:\Users\r3c0d3x\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.7.3\build.rs:712
note: Run with `RUST_BACKTRACE=1` for a backtrace.
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
cl : Command line warning D9002 : ignoring unknown option '/utf-8'
```

It appears to be caused by [this](https://github.com/briansmith/ring/blob/8a46eb57b861973c934f6df034ac9c4c24e425c5/build.rs#L291). I'm using whatever build tools are provided with Visual Studio 2015 and it apparently doesn't need the command line option, but I get that older toolchains might.

**Comment by briansmith** [comment]
I think you may not be using the newest version of the MSVC 2015 build tools. Can you do `cl /version`? And/or, try removing your MSVC 2015 build tools and then downloading and installing the newest (pre-2017) build.

Regardless, it's probably better to just remove the non-ASCII characters from the C/C++ source files. Then we can remove this option. There are only a few, and they are all in comments.

**Comment by r3c0d3x** [comment]
I uninstalled Visual Studio 2015 (wasn't using it anyways), which was using version `19.00.23506` and installed version `19.00.24210`. This worked fine and `ring 0.7.3` is building correctly. 

But I completely agree; if you're only using that option for non-ASCII characters in a few comments here and there, it would probably be worth it to remove them.

**Comment by briansmith** [comment]
I believe this is fixed in 3c95a29cc31d6d4f8529eed6facd7be00a9439c2.

@itn3000, you were the one that originally reported the issue that prompted me to add the `/utf-8` option to cl.exe. Can you verify that the current master branch builds in your environment, now that we've removed `/utf-8`?  Basically I just removed all the non-ASCII text in the source code (just one character in one file). Thanks!

**Comment by itn3000** [comment]
I tested to compile, but fail in crypto/curve25519/curve25519.c because of C4819.
so I created PR(#503) for this problem, please check it.

**Comment by briansmith** [comment]
@itn3000. Thanks! I merged your PR (with minor changes).
