### ISSUE TITLE
Replace `GFp_x25519_ecdh()` and `GFp_x25519_public_from_private()` with Rust code

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#510]
`GFp_x25519_ecdh()` is just a wrapper around the point multiplication, so it's simple.  `GFp_x25519_public_from_private()` is a little more work because it has two implementations: One for ARM NEON and one for the rest of the platforms.

Note that the functions `fe_*()` and `x25519_scalar_mask()` should NOT be replaced with Rust code yet; we're going to convert all the constant-time functions last.

One particular short-term goal of this is to get rid of the `GFp_memcmp()` and `memcpy()` calls.

A longer-term goal is to try to share (more) logic with the Ed25519 code.

**Comment by ranweiler** [comment]
> Note that the functions `fe_*()` and `x25519_scalar_mask()` should NOT be replaced with Rust code yet; we're going to convert all the constant-time functions last.

Oh, does that mean we should hold off on #500 for right now?

**Comment by briansmith** [comment]
> Oh, does that mean we should hold off on #500 for right now?

No, #500 is OK. Basically, we just are just deferring oxidizing anything at the twiddling-the-bits level. But any function that just calls other functions is a good target for oxidation.

**Comment by ranweiler** [comment]
@briansmith, should this actually be in "Not Started" on the Oxidation board, or do you have a branch where this is done?

These functions (may) transitively call the `x25519_scalar_mult_generic()` function, which calls `fe_invert()`, which we want to oxidize. If this hasn't actually been completed (or even started), I'm going to pick it up en route to #500.

**Comment by briansmith** [comment]
Probably I got confused when moving the cards around and put them in the wrong column.

Go for it. I moved it to "in progress."

**Comment by ranweiler** [comment]
Cool, thanks!

**Comment by clarcharr** [comment]
Stumbled upon `GFp_memcmp` in the code and was a bit confused why that hadn't been converted to Rust yet, considering how it could be basically verbatim converted to Rust as-is. Would you accept a PR making this change?

**Comment by aled1027** [comment]
Has this issue been address and if not, is it still of interest?

I'm looking for a good-first-bug issue to tackle and looks like this could be a good candidate.
