### ISSUE TITLE
Do calculation of RSA Montgomery RR in Rust

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#513]
I already have a WIP in my tree. This will fix #431.

**Comment by kjvalencik** [comment]
Firstly, thanks for the great crate! Secondly, any movement on this? I tried out #465 locally and it made an order of magnitude improvement.

**Comment by briansmith** [comment]
@kjvalencik I think it will be at least a few weeks before I can get back to this. As far as RSA performance in general, there are *several* things we can do to make it significantly faster.

Are you measuring this at the public key end (verification) or the private key end (signing)?

**Comment by kjvalencik** [comment]
Public key verification.

**Comment by briansmith** [comment]
I'm closing this in favor of using #431 as the RSA public key construction performance issue.

We now have a very good plan for making the performance much much better while still allowing for easy formal verification.
