### ISSUE TITLE
Remove the syscall(2) dependency.

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#514]
syscall(2) is a varargs function, which we strive to avoid categorically. We should probably just issue the getrandom syscall with inline assembly, or, when we get to the end of removing C dependencies, straight assembly language.

**Comment by briansmith** [comment]
Also, we're striving to remove dependencies on libc (both the actual libc and the libc crate). The use of `syscall()` also forces us to care about `errno`, which is mutable global state, which we're also trying to avoid depending on.

**Comment by briansmith** [comment]
@jeandudey submitted a PR for this in #617. Thanks!

@jeandudey's PR uses hand-written (AFAICT) inline asm code for x86 and x86-64. It's missing 32-bit ARM and 64-bit ARM support so I cannot check it in as-is. Also, I'd like to avoid hand-written assembly code if at all possible.

I want to suggest an alternative approach:

The Android bionic project is an implementation of libc for Android; See https://android.googlesource.com/platform/bionic.git.  The libc/tools/gensyscalls.py program in that project reads libc/SYSCALLS.TXT and generates assembly language code that wraps the syscall in a C function for all platforms that Android supports. I would like to use that approach to generate a `GFp_getrandom()` function:

* Create an input file that contains a single line: `ssize_t getrandom(void*, size_t, unsigned) all`
* Extract libc/tools/gensyscalls.py from bionic and put it into third-party/bionic.
* Modify libc/tools/gensyscalls.py so that it generates functions with a "GFp_" prefix so that we don't collide with any `getrandom()` function defined by libc on any platform.
* Modify libc/tools/gensyscalls.py so the generated code does NOT do anything with `errno`.
* Run the modified libc/tools/gensyscalls.py and save the output assembly language files to third-party/bionic.
* Add all the files in third-party/bionic to version control so that we don't have to run libc/tools/gensyscalls.py during the build (so we don't require Python to build *ring*).
* Modify the assembly language files to build.rs so that they get assembled and linked into Linux builds (only).
* Modify the Rust code to use the new `GFp_getrandom()` function on all Linux targets instead of `syscall()`.

@jeandudey WDYT? It's basically the same idea as yours, but without any hand-written code.

**Comment by jeandudey** [comment]
@briansmith Hi! thanks for the response, i'm going to take a look at it.

**Comment by FauxFaux** [comment]
I had a look at doing this. I don't think it's a good idea.

> Extract libc/tools/gensyscalls.py from bionic and put it into third-party/bionic.

This [involves](https://android.googlesource.com/platform/bionic.git/+/6880f936173081297be0dc12f687d341b86a4cfa/libc/tools/gensyscalls.py#572) pulling in a load of the semi-parsed, semi-generated kernel headers shipped inside [`libc/kernel/uapi/*/*`](https://android.googlesource.com/platform/bionic.git/+/6880f936173081297be0dc12f687d341b86a4cfa/libc/kernel/uapi/asm-arm/asm), and all the assembly and C code references that. Shipping the (semi-generated, GPL) kernel headers for a load of architectures, when all we want is a syscall number and maybe a typedef, seems like overkill.

> Modify libc/tools/gensyscalls.py so the generated code does NOT do anything with errno.

This basically requires rewriting all the hand-written assembly, as it mostly exists to fiddle with `errno`.

```python
x86_64_call = """\
    movl    $%(__NR_name)s, %%eax
    syscall
    cmpq    $-MAX_ERRNO, %%rax
    jb      1f
    negl    %%eax
    movl    %%eax, %%edi
    call    __set_errno_internal
1:
    ret
END(%(func)s)
"""
```
A rewrite of this would be (probably):

```asm
    movl    $%(__NR_name)s, %%eax
    syscall
    ret
```

..which only works with access to the kernel headers, where the definition of `__NR_getrandom` comes from. See above.

At that point we've hand-written assembly for every syscall, so it'd be better to have just hand-written code for `getrandom` for the other three architectures?

---

For `syscall.rs` I wrote [a script that generates the numbers from the kernel sources directly](https://github.com/japaric/syscall.rs/blob/master/tools/nr_from_src.py), and that's probably a better place to maintain the script, if access to the numbers is a concern.

**Comment by briansmith** [comment]
This has been hung up for a while. Basically what happened is that I learned that some ABIs require us to go through libc to do any syscalls. In particular, glibc requires us to use `syscall(2)` because its `syscall(2)` has an interaction with its implementation of mutexes/etc. In particular, glibc sometimes uses hardware transactions (TSX) and those don't work across a syscall boundary.

So if we want to bypass `syscall(2)` we need to figure out which ABIs guarantee us that doing so is safe.

Alternatively, maybe we should use weak linking for dynamicly-linked libc to use `getrandom(2)`/`getentropy(3)` first, and then fall back on `syscall(2)` if that fails? On statically-linked libc we'd require `getrandom(2)`/`getentropy(3)` to be present?

Remember that the main goal here is to avoid an the error-proneness of `syscall(2)` due to varargs and due to bugs in the TSX interaction, so minimizes the instances in which we'd cal `syscall(2)` instead of eliminating it might provide a much better bang-for-the-buck.

Thoughts?

**Comment by briansmith** [comment]
I'm closing this because the idea turned out to be more problematic than beneficial due to the TSX issue. Thank you to everybody who contributed to this.
