### ISSUE TITLE
build fails on ubuntu

### ISSUE THREAD

**Issue by vks** [briansmith/ring#523]
I'm getting build failures with ring on travis:

```
thread '<unnamed>' panicked at 'execution failed', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.7.5/build.rs:720
crypto/ec/ecp_nistz256.c: In function ‘GFp_nistz256_point_mul’:
crypto/ec/ecp_nistz.h:106:20: error: inlining failed in call to ‘booth_recode.part.0’: call is unlikely and code size would grow [-Werror=inline]
```

On a different a different system (`Linux 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64` and `gcc 4.8.4`) I'm getting similar build failures, also in `crypto/limbs/limbs.inl`. On a current Fedora system everything works.

**Comment by vks** [comment]
This only occurs when ring is used as a dependencies and optimizations are enabled for debug builds, i.e.
```toml
[profile.dev]
opt-level = 2  # otherwise the tests run for too long
```
makes `cargo test` fail.

**Comment by briansmith** [comment]
Thanks! Probably we should make `-Werror` depend on whether `.git` exists; i.e. don't do `-Werror` when building from crates.io.

**Comment by vks** [comment]
This would not work if you depend on ring via a git repository (local or remote). Maybe there is a way to detect whether ring is bild as a dependency? I think that would be a better option, however for my issues it is indeed sufficient to fix it on crates.io.

**Comment by briansmith** [comment]
> This would not work if you depend on ring via a git repository (local or remote).

That's OK. We don't really support that any way as nobody seems to need that supported.

**Comment by briansmith** [comment]
I took a stab at resolving this with 76a44de074e3116728873d64165592acf30d6fa2.

**Comment by vks** [comment]
Thanks! I'll give it a try once the next version of ring is released.

**Comment by briansmith** [comment]
@vks ping. Did you try this out with the newer *ring*? Is it working now? Thanks.

**Comment by vks** [comment]
Yes, I believe this is fixed, I'm not getting build files anymore. Thanks!

**Comment by briansmith** [comment]
Thanks @vks!

**Comment by king6cong** [comment]
> This would not work if you depend on ring via a git repository (local or remote).
> That's OK. We don't really support that any way as nobody seems to need that supported.

@briansmith 

`cargo build --all --release --target x86_64-apple-ios` will result error in the lasted crates.io version (0.12.1), and has been fixed in origin/master on git repo.

I use `"ring:0.12.1" = { git = "https://github.com/briansmith/ring" }` for moment, so I think depend on ring via a git repository should be considered as needed.
