### ISSUE TITLE
Implement `PartialEq` and `Eq` for all public Algorithm types

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#542]
I suggest that for each Algorithm type, we define a simple enum, like this:

```rust
#[derive(Eq)]
pub struct WhateverAlgorithm {
    // existing fields
    id: WhateverAlgorithmID, // Add this field
}

#[derive(PartialEq, Eq)]
#[allow(non_snake_case_types)]
enum WhateverAlgorithmID { // Not public
     FIRST_ALGORITHM,
     SECOND_ALGORITHM,
     // etc.
}

impl PartialEq for WhateverAlgorithm {
    fn eq(&self, other: &Self) -> bool { self.id == other.id }
}
```

The use case for this to make it easier to embed references to algorithms into other (external user) types that want to implement `PartialEq` and `Eq`.

**Comment by mrwhythat** [comment]
Just submitted PR #553 for this.

**Comment by jeffgran** [comment]
Looks like this should be closed?

**Comment by briansmith** [comment]
> Looks like this should be closed?

Some of the work has been done but there's more work to do.

**Comment by briansmith** [comment]
I think this is done. If there's anything missing, please submit a PR.
