### ISSUE TITLE
Export all components of all keys (secret and public)

### ISSUE THREAD

**Issue by P-E-Meunier** [briansmith/ring#545]
So, I started to implement an SSH agent client (and potentially a server if the client works). This requires me to supply unencrypted secret keys by component, in a custom encoding.

Since others (and myself) have asked for this in the past, here are the relevant issues:
#441 and #299

**Comment by briansmith** [comment]
Doesn't the agent protocol have a way for the agent to keep the private key private, so that it can work with smartcards and similar, which don't allow one to extract the private key?

**Comment by briansmith** [comment]
@P-E-Meunier ping? I'd like to make sure we do the stuff needed to do that kind of stuff, but I'd like to find a better approach, as indicated in the comment above. WDYT?

**Comment by P-E-Meunier** [comment]
Oops, sorry, I forgot to answer.
The spec is there: https://tools.ietf.org/html/draft-miller-ssh-agent-00

I started looking for a different answer, didn't find one, and didn't come back here. It seems the answer is "no", but I can't be sure.

I could also implement a different agent, just for Thrussh, that would work with better formats. Thrussh already implements all of SSH 2, I guess it wouldn't be too hard to extend that with an actual SSH client and server.

**Comment by briansmith** [comment]
In https://tools.ietf.org/id/draft-miller-ssh-agent-00.html#rfc.section.4.5 it says "A client may request the agent perform a private key signature operation using [SSH_AGENTC_SIGN_REQUEST.] Where "key blob" is the key requested to perform the signature, "data" is the data to be signed and "flags" is a bitfield containing the bitwise OR of zero or more signature flags (see below)."

So, the agent doesn't need to send its private key to ssh(1) for any reason.

You need to be able to export the public keys in the "wire format" of SSH, which may be a SSH-specific format. I think you can do that already for Ed25519 but not yet for RSA or ECDSA. AFAICT the wire format of an ECDSA public key in SSH is an X509 certificate. So, is this issue just about being able to read the individual components of an RSA public key from the private key?

**Comment by heartsucker** [comment]
Seconding some of this. It would be nice to be able to export the public component from an `RSAKeyPair` and `Ed25519KeyPair`. Preferably as something nicely DER encoded so we can ship it along to other application.

Relevant to:
- https://github.com/heartsucker/rust-tuf/issues/78
- https://github.com/heartsucker/rust-tuf/issues/81
- https://github.com/heartsucker/rust-tuf/issues/82

**Comment by briansmith** [comment]
It's already possible to get the public component from `Ed25519KeyPair` and getting the public components from `RSAKeyPair` is already another issue.

**Comment by briansmith** [comment]
I'm going to close this because the scope is too broad:

* Exporting public key for Ed25519 and X25519 is already done.
* Exporting public key components for RSA is already covered by one or two other existing issues and PRs.
* Exporting public key components for P-256 and P-384 can be covered by another issue if anybody cares to file one.
* Exporting the private key components of keys is intentionally not implemented. It can be discussed in a separate issue if people want to discuss it further.
