### ISSUE TITLE
Could not find native static library "ring-test" on Alpine Linux (using Docker)

### ISSUE THREAD

**Issue by PatrikCyvoct** [briansmith/ring#546]
I have a docker image based on Alpine Linux, which should run a rust app relying on rusoto, which is using ring. I can cargo build without problems but when I try to run I have this : 
```
[...]
Compiling ring v0.9.7
error: could not find native static library "ring-test", perhaps an -L flag is missing?
fatal runtime error: failed to initiate panic, error 5
error: Could not compile "ring".
```

Here is my dockerfile : 
```
FROM alpine:edge
ENV rust_version 1.17.0-r2
ENV cargo_version 0.18.0-r0
RUN apk add --update rust=$rust_version cargo=$cargo_version ca-certificates openssl-dev openssl musl-dev gcc
COPY . /app/
RUN cd /app && cargo build --target x86_64-alpine-linux-musl
WORKDIR /app
CMD ["cargo", "run"]
```

Any ideas on how to fix it ?

**Comment by briansmith** [comment]
Please attach (or add a comment using the \<details\> tag the full build log with `cargo build -vv`

**Comment by PatrikCyvoct** [comment]
Stupid me, I copied the target folder to the docker images, which was compiled in OS X. Works perfect when I remove it!
