### ISSUE TITLE
Link to first version of the Rust book is broken.

### ISSUE THREAD

**Issue by cedenday** [briansmith/ring#554]
The one I found:

https://github.com/briansmith/ring/blob/67c526b53265e1de45e0ed9af01e49f55407e9a4/src/error.rs#L81-L82

More are likely though.

**Comment by dowoncha** [comment]
Should they continue to link to first version or update to the second?

**Comment by briansmith** [comment]
It's good to link to the second version.

**Comment by KolesnichenkoDS** [comment]
There's no such topic in the second edition yet, so I created PR with the fixed link to the first edition.

**Comment by briansmith** [comment]
> There's no such topic in the second edition yet, so I created PR with the fixed link to the first edition.

Thanks! Fixed in 825843301748352480f737b2d1f0283ce8b7bd95.
