### ISSUE TITLE
PKCS #7 / CMS signnature support

### ISSUE THREAD

**Issue by luser** [briansmith/ring#555]
Is PKCS #7 / CMS signature support something that ring could support? I've been working on a [reimplementation](https://github.com/luser/darwincodesign) of Apple's `codesign` tool, and the signatures there use CMS, and there doesn't seem to be an existing Rust crate for this. For Mozilla's purposes I'm probably going to wind up just submitting the calculated hashes to an API to do the actual signing, so we can use an implementation in another language, but it would be nice to have a way to validate existing signatures without having to call out to an external service.

**Comment by briansmith** [comment]
*ring* is designed to make it possible to implement a PKCS#7/CMS implementation externally.  I would probably try to implement it in a separate crate. I did a rough prototype of such a crate a while back and I can't think of any impediments. If there is some part of the functionality that can't be implemented with *ring*'s APIs, let me know.

**Comment by luser** [comment]
I'm unlikely to do an actual implementation myself, but that's good to know. I'll just close this since it sounds like the answer to my original question is "no, ring will not ship an implementation". Thanks for the info!

**Comment by briansmith** [comment]
Hi Ted, I think there are two issues: Who has time to do the implementation, and whether the implementation should live in *ring* or in a separate crate. IMO it should be in a separate crate, similar to webpki. If you are looking for somebody to actually do the implementation, email me (brian@briansmith.org).
