### ISSUE TITLE
Partially homomorphic encryption in scope?

### ISSUE THREAD

**Issue by modalduality** [briansmith/ring#561]
Are partially homomorphic encryption schemes like Paillier and Damgård-Jurik within the scope of Ring, or would a new crate be more appropriate?

**Comment by burdges** [comment]
I think ring is trying to provide a difficult to miss-use API, but homomorphic properties are inherently easy to miss-use.  It's possible some higher level usage of Paillier or Damgård-Jurik might be in scope of course. 

Also, ring provides a degree of algorithm agility, which you do not want as you move into stranger primitives.  As an example, it'd be risky for some pairing library to provides algorithm agility over curves whose pairings had different types (I/II/III).

**Comment by briansmith** [comment]
@modalduality I think it should be done in another crate that has a maintainer really dedicated to homomorphic encryption.
