### ISSUE TITLE
RSA signing example error

### ISSUE THREAD

**Issue by metsuke0** [briansmith/ring#565]
I copied and pasted the following example, replacing only the private key:
https://briansmith.org/rustdoc/ring/signature/index.html#signing-and-verifying-with-rsa-pkcs1-15-padding

I receive the following output errors:
https://gist.github.com/metsuke0/1f42bc46b625b9b2d13948f1f3b7eb61

Is there something more I should be doing for proper compilation?

OS: FreeBSD 11.0-RELEASE-p11
rust version: 1.19.0 and 1.21.0

**Comment by andrewtj** [comment]
Do you have the rsa_signing feature enabled in Cargo.toml? Something like:

```
ring = { version = "0.11.0", features = ["rsa_signing"] }
```

**Comment by metsuke0** [comment]
That got me further, thanks.
