### ISSUE TITLE
Compressed Ed25519 public points can't always be decompressed

### ISSUE THREAD

**Issue by heartsucker** [briansmith/ring#568]
I'm using `ring` alongside `curve25519-dalek` to decompress the public point because some other application expects both the x and y coordinates of the public point. `ring`'s points don't always decompress correctly. [This gist](https://gist.github.com/heartsucker/be15bfa592055460dd10907e1e7ec9e5) shows a minimal sample of the problem. I'm not entirely sure where the error lies (what lib, my code), but it seems worth addressing here.

Link to related issue: https://github.com/isislovecruft/curve25519-dalek/issues/70

**Comment by briansmith** [comment]
There's a bug in the test code. Please reopen this if fixing that doesn't resolve the issue.

**Comment by heartsucker** [comment]
Wow. I cannot believe I spent all day on this because of a typo. One day, I'm going to end up in the same city as you and buy you so much beer.
