### ISSUE TITLE
Salsa20 Cipher

### ISSUE THREAD

**Issue by mmrath** [briansmith/ring#572]
For one my hobby project I need salsa20 algo. I checked source code in this repo but could not find any source related to it. ChaCha appears to be related but not sure if it will be alright. Does anyone know if there is some support for Salsa20 yet?

**Comment by briansmith** [comment]
@mmrath Although it could change, at this time I'm not planning to add Salsa20. I recommend everybody use ChaCha20(-Poly1305) instead of Salsa20.

**Comment by mmrath** [comment]
@briansmith You mean instead of Salsa20 I can use ChaCha* to decrypt something that is encrypted with Salsa20? Sorry if that was a stupid question. In my case I am not able to influence the algo for encryption much.

**Comment by briansmith** [comment]
No, you can't use ChaCha20 to decrypt something encrypted using Salsa20.
