### ISSUE TITLE
How to use AES_256_CBC 

### ISSUE THREAD

**Issue by mmrath** [briansmith/ring#573]
Hi, Could someone please help me find out how to use AES_256_CBC?

**Comment by briansmith** [comment]
AES-CBC cipher suites aren't implemented in *ring* yet.

**Comment by musoke** [comment]
Are there plans to do so?  I'm currently evaluating dependencies and ring seems to have everything else I need (and the nicest api)

**Comment by briansmith** [comment]
@musoke What authenticator do you use AES-CBC with? HMAC-SHA-256 or similar? It's likely we'd first try to support AES-CBC only integrated with an authenticator in the same way we only support AES-CTR with GCM as AES-GCM.

**Comment by musoke** [comment]
I'm looking for HMAC-SHA-256. (And truncating the HMAC to 64 bits; I should look into the reasoning for that)

Thanks for the help!
