### ISSUE TITLE
Fails to build on target x86_64-apple-ios

### ISSUE THREAD

**Issue by mehcode** [briansmith/ring#583]
```shell
$ rustc --version
rustc 1.21.0 (3b72af97e 2017-10-09)
$ cargo build --target x86_64-apple-ios
[....] (gist of output is below)
```

https://gist.github.com/mehcode/f6e3c9f64b2cbb46c818efc155e8391c

---

Tried using latest version on Cargo and on master.

Lots of errors that look like:

```
elf.S:4119:8: error: invalid alignment value
.align 64
```

---

If there is any debugging I can do to help, let me know.

**Comment by andrewtj** [comment]
I made a guess that the wrong assembly format was being selected and have found that adding `("x86_64", Some("ios"), "macosx"),` as the first entry in [`ASM_TARGETS`](https://github.com/briansmith/ring/blob/33784df72755276c3c422a0f81dfb9f8550f13e6/build.rs#L252-L266) seems to fix the build. I haven't actually tried it in the simulator though, and I am just taking a wild stab.

**Comment by mehcode** [comment]
@andrewtj Thank you!

After running some basic experiments (making HTTPS requests with hyper-rustls and hmac signing) everything seems to be working with that change. I'll make a quick PR.

**Comment by briansmith** [comment]
According to #584 this was fixed.
