### ISSUE TITLE
Separate DER-handling code from the main crate

### ISSUE THREAD

**Issue by P-E-Meunier** [briansmith/ring#586]
I'd like to handle as many key formats as possible. PR #582 is a format-independent interface to load keys, and this could allow \*ring\* to get rid of all its ASN.1 handling, which is not its main added value.

I've started to work on such an interface in thrussh-keys, and this works fine for RSA and Ed25519 keys, encrypted or not, in several formats, including PKCS#8, but also legacy formats used by OpenSSH.

The parsing in thrussh-keys is done using "yasna", a crate to parse DER. That crate is a little wasteful in terms of memory at the moment, but it's also fairly young (0.1). The interface doesn't look too different from what \*ring\* does.

**Comment by newpavlov** [comment]
@briansmith 
What do you think about it? I could prepare PRs for ring and webpki if you interested in it.

**Comment by briansmith** [comment]
Probably not going to happen.
