### ISSUE TITLE
Blind signature support

### ISSUE THREAD

**Issue by siriux** [briansmith/ring#592]
I'm not an expert on crypto internals, so I apologize if the question is obvious, but is it possible to implement a blind signature scheme using the primitives provided by Ring?

Otherwise, do you plan to support it?

Thanks

**Comment by briansmith** [comment]
@siriux I don't have any plans to add blind signature support. If there's a particular blind signature scheme that seems like it might get widespread adoption in one or more widely-used protocols I might consider adding it. If there is such a scheme, please file a separate issue proposing with the details of the scheme. Thanks.
