### ISSUE TITLE
32-bit counter wrap-around for AES_GCM modes

### ISSUE THREAD

**Issue by schulze** [briansmith/ring#597]
The function `check_per_nonce_max_bytes()` in [aead.rs:L339](https://github.com/briansmith/ring/blob/master/src/aead/aead.rs#L339) checks for inputs that would wrap around the 32-bit counter of the ChaCha stream cipher by disallowing inputs larger than 

`(1u64 << 32) * 64 - 64` bytes.

The AES_GCM modes also use a 32-bit counter but only process 16-byte blocks instead of 64-byte blocks of ChaCha, so the counter already wraps around at

`(1u64 << 32) * 16` bytes.

Because the `check_per_nonce_max_bytes()` function is also used for the AES_GCM the function should either depend on the block size of the algorithm used, or use the latter smaller length.

**Comment by schulze** [comment]
For comparison I looked at another implementation: The Go implementation of AES GCM checks for `(1<<32)-2)*uint64(g.cipher.BlockSize())` bytes, but at the moment I can't see where these additional 2 blocks come from.

That implementation also takes the tag size into account in `Open()` and checks for `(1<<32)-2)*uint64(g.cipher.BlockSize()) + gcmTagSize`.

This check is done in the implementation of the different ciphers and not for the general AEAD interface. The test for ChaCha20 in [chacha20poly1305.go#L63](https://github.com/golang/crypto/blob/master/chacha20poly1305/chacha20poly1305.go#L63) is the same as the test in ring.

**Comment by schulze** [comment]
A last comment: ring contains a least two other similar checks:

- In [crypto/modes/gcm](https://github.com/briansmith/ring/blob/master/crypto/modes/gcm.c#L523) and other checks in that file, where the correct upper bound for GCM is used.
- In `aead_check_in_len()`in [crypto/cipher/internal.h](https://github.com/briansmith/ring/blob/master/crypto/cipher/internal.h#L102) where like above only the ChaCha20 bound is used.

So it seems, that no checks are missing, and there is only some redundancy in the checks that are implemented at different abstractions levels.

**Comment by briansmith** [comment]
Thanks. Definitely we want all the checks to be right, especially the Rust checks. In particular we generally want to replace the C code with Rust code. I think you are right that we should be using the block size instead of hard-coding 64 in that check.

The extra two blocks come from how the GCM key derivation is done.

**Comment by briansmith** [comment]
PR #610 addresses this.
