### ISSUE TITLE
Compilation error with latest version on nightly

### ISSUE THREAD

**Issue by ludwigpacifici** [briansmith/ring#621]
An [example](https://rust-lang-nursery.github.io/rust-cookbook/basics.html#ex-hmac) code from the Rust Cookbook does not compile. It relies on on the ring crates and nightly toolchain

To reproduce
1. use the upper example code
2. cargo.toml: `ring="*"`. This will pull ring v0.12.1
3. run `rustup update nightly` and switch to nightly toolchain, in my case `rustup default nightly-x86_64-unknown-linux-gnu`
4. `cargo build` into the project

Error:

```
error[E0583]: file not found for module `montgomery`
  --> /home/lud/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic/arithmetic.rs:15:9
   |
15 | pub mod montgomery;
   |         ^^^^^^^^^^
   |
   = help: name the file either arithmetic/montgomery.rs or arithmetic/montgomery/mod.rs inside the directory "/home/lud/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic"

error: aborting due to previous error

error: Could not compile `ring`.
```

Thank you

**Comment by exul** [comment]
Duplicate of https://github.com/briansmith/ring/issues/598, you can use `0.13.0-alpha` until `0.13` is released.

**Comment by ludwigpacifici** [comment]
Thanks for the update!

**Comment by nayato** [comment]
"-alpha" sounds kind of scary. Is it as stable as 0.12? Also it being minor upgrade, means it's hard to fix proxy dependencies (e.g. my crate -> cookie -> ring). With this issue now happening in beta (heading for the next stable release), would it be possible to issue another 0.12.x release to fix existing dependencies?
cc @briansmith @ludwigpacifici

**Comment by briansmith** [comment]
The next rustc nightly & beta releases will unbreak *ring* 0.12. Just wait a few days.

**Comment by nayato** [comment]
That's great news, thanks!

**Comment by FridgeSeal** [comment]
I had this problem as well (was trying to use rusoto_core): I updated nightly and I can confirm that nightly no longer breaks things (at least on my machine) 😃.
For reference, my current nightly version: rustc 1.25.0-nightly (79a521bb9 2018-01-15)
