### ISSUE TITLE
AES-OCB

### ISSUE THREAD

**Issue by rubdos** [briansmith/ring#624]
Hi!

It would be interesting to have AES in [OCB mode](https://en.wikipedia.org/wiki/OCB_mode) among the available AEAD schemes. The newer OCB modes (since OCB2) support associated data.

[edit]

**Comment by briansmith** [comment]
@rubdos I think it's better to focus on modes that are more widely deployed, including AES-SIV and maybe soon AES-GCM-SIV. Adding OCB mode would require me to do a lot of non-technical work that's really unpleasant, so there would have to be a very strong motivation for me to pursue it.

Also, I am sincerely sorry, but I removed part of your initial comment. It's important to keep the discussion limited to technical (e.g. which nodes are safest and fastest) criteria and social criteria (e.g. X, Y, Z implement it and we need this for interoperability). Thanks!

**Comment by DemiMarie** [comment]
@briansmith may I ask what that is?  Does it relate to patents?

**Comment by rubdos** [comment]
if you mean

> part of your initial comment

yes, it is. I suggested to have a `patent-encumbered` feature or something along those likes.

**Comment by briansmith** [comment]
I'm going to close this for now. I think we should see a more clear story for standardization of OCB before we try to support it, especially given the limited resources we have currently. If there's a major use case for OCB (e.g. somebody is trying to implement a standard protocol that mandates OCB support, and we think that protocol is worthwhile enough to lend support to them), we can revisit this.
