### ISSUE TITLE
"error: static declaration of 'strtof' follows non-static declaration" when building for ARM Android in some configurations

### ISSUE THREAD

**Issue by Ludea** [briansmith/ring#636]
Hello,
I try to compile rocket hello world on Android (by termux) 
But there is an issue with ring building.
`
error: failed to run custom build command for `ring v0.11.0`
`
Here the log 
```
In file included from crypto/curve25519/curve25519.c:25:
In file included from include/GFp/mem.h:62:
In file included from /data/data/com.termux/files/usr/include/stdlib.h:254:
/data/data/com.termux/files/usr/include/android/legacy_stdlib_inlines.h:42:23: error: static declaration of 'strtof' follows non-static declaration
static __inline float strtof(const char* nptr, char** endptr) {
                      ^
/data/data/com.termux/files/usr/include/stdlib.h:248:92: note: previous implicit declaration is here
static __inline__ float strtof_l(const char* __s, char** __end_ptr, locale_t __l) 
```
Do ring support arm building?

**Comment by jprider63** [comment]
What happens if you try `0.13.0-alpha`? Try adding the following to your Cargo.toml:

    ring = "0.13.0-alpha"

**Comment by Ludea** [comment]
I can not install ring 0.13. 0 alpha. 
I canot install it because native link can be linked once time. (ring asm). 
Or I already use rocket with ring 0.11.
Should I wait for an update of rocket dependancies?

**Comment by briansmith** [comment]
I'm going to close this because it's reported against *ring* 0.11. if it still affects *ring* master, let me know and I'll reopen it. Thanks for the report!
