### ISSUE TITLE
Is it possible to generate RSA key pair, and how?

### ISSUE THREAD

**Issue by light4** [briansmith/ring#640]
Generate RSA key pair by [rust-openssl](https://github.com/sfackler/rust-openssl):

https://gist.github.com/rust-play/6509bead4c6e13345f6535faf2db06bf

I want to know how to do this by [ring](https://github.com/briansmith/ring). 

Thanks for your great work!

**Comment by briansmith** [comment]
RSA key generation is tracked as issue #219. BoringSSL has a new implementation of RSA key generation that we can base our implementation on. I will be looking at doing that soon.

Thanks for filing this. I'm going to close this in favor of #219.
