### ISSUE TITLE
Expose ChaCha20 directly

### ISSUE THREAD

**Issue by nvesely** [briansmith/ring#642]
I would like to be able to use ChaCha20 as a PRF. So it would be nice if there was an implementation decoupled from Poly1305.

As far as the benchmarks I've seen, HMAC-based PRFs are generally much slower than ChaCha20, with the exception of HMAC-SHA-1, which seems similarly fast. Since HMAC-SHA-1 is a secure PRF until someone breaks the indistinguishability of the SHA-1 compression function, I suppose it is a fine choice for now.

I think providing another fast PRF option would be good though, and it might be pretty easy to provide a direct interface with ChaCha20 considering it's already part of the library.

**Comment by nvesely** [comment]
Correction: I can't actually use HMAC-SHA-1 because the scheme I'm implementing calls for a PRF and a second preimage resistant function with the same output length. I know its safe to truncate SHA-512 to 160 bytes to match the output of HMAC-SHA-1, but that drops the overall security parameter guarantees of the scheme below what I'd like.

So I have to use HMAC-SHA-512/256 for a PRF and SHA-512/256 for a SPR function. And HMAC-SHA-512/256 is much slower than ChaCha20 for producing 256-bit output blocks. The construction requires lots of calls to the PRF. More than to the SPRF.

I have seen on other issues you are motivated to include things based on needs of ring users, which is why I include this info.

**Comment by nvesely** [comment]
Note that implementing #169 (keyed blake2b) or #59 (specifically KMAC) would also provide an option to ring users looking for a 256-bit PRF significantly faster than HMAC-SHA-512/256.

**Comment by briansmith** [comment]
For better or worse, this appears to be happening in #695.
