### ISSUE TITLE
Add NIST CAVP AES-GCM tests

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#643]
See https://boringssl.googlesource.com/boringssl/+/3975ecffc22b1d98065d11e94713d258ecddbe93. Ideally we'd do something very similar, but without depending on Go. However, depending on Go in the short term for running those tests isn't a showstopper; we can use BoringSSL's Go program for now and then somebody could replace it later with a Rust equivalent.

**Comment by briansmith** [comment]
See also https://boringssl.googlesource.com/boringssl/+/1d134eee9a7f456cc100ac450abcc67243d8fbdd

**Comment by brycx** [comment]
I would like to take a swing at this, but I'm pretty new so it might take some time. Is that okay?

**Comment by brycx** [comment]
So I took the test vectors from [NIST's homepage](https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/CAVP-TESTING-BLOCK-CIPHER-MODES#GCMVS), and with the below Python script(I will have to rewrite it in Rust later on), modified it to fit the conventions used in the current test vector files for GCM. Then I added a test to `aead_tests.rs` and now I keep running into errors.

What gets me right now is, the test vectors have the "FAIL" option set, with no specification on what type of failure. I'm converting `FAIL` to `FAIL = ""`, and I added a match arm in aead_tests.rs to account for this:
```
                // Accounting for the NIST CAVP empty error string
                Some(ref error) if error == "" => {
                    assert_eq!(Err(error::Unspecified), s_result);
                    assert_eq!(Err(error::Unspecified), o_result);
                },
```
The two errors that keep popping up are:
- `'nist_cavp_aes_128_gcm_decrypt' panicked at 'internal error: entered unreachable code: Unexpected error test case: ""'`
- `thread 'nist_cavp_aes_128_gcm_decrypt' panicked at 'assertion failed: (left == right)
 left: Ok(55),
 right: Err(Unspecified)', tests/aead_tests.rs:179:21`

I would love some pointers on how to proceed with this.

Conversion script:

```
replacements = {
    'Key' : 'KEY',
    'IV' : 'NONCE',
    'PT' : 'IN',
    'AAD' : 'AD',
    'Tag' : 'TAG',
    'FAIL' : 'FAILS = '
}

lines = []

with open('./gcmDecrypt128.rsp') as infile:
    for line in infile:
        for src, target in replacements.items():
            line = line.replace(src, target)
        if line.endswith("= \n"):
            line = line.replace(' = ', ' = ""')
        if not line.startswith("Count = "):
            if not line.startswith("["):
                if line.startswith("FAILS"):
                    # ring needs the input arguments
                    # which NIST CAVP does not have for
                    # test cases that FAIL
                    lines.append('IN = ""\n')
                lines.append(line)
with open('./gcmDecrypt128_MOD.txt', 'w') as outfile:
    for line in lines:
        outfile.write(line)
```

**Comment by briansmith** [comment]
Closing this. I think there are more useful ways of testing the AES-GCM code.
