### ISSUE TITLE
Windows build fails with VS 2017 15.7.0

### ISSUE THREAD

**Issue by kjeremy** [briansmith/ring#648]
I just updated my VS2017 to the latest stable 15.7.0.  Now ring 0.12.1 fails to compile.

The first errors I see when running `cargo build` complain about errors being treated as warnings.

> c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\limbs\limbs.inl(128) : error C2220: warning treated as error - no 'object' file generated
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\limbs\limbs.inl(128) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\limbs\limbs.inl(127) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\limbs\limbs.inl(128) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3510) : error C2220: warning treated as error - no 'object' file generated
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3510) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3509) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3510) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3495) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3494) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3495) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3685) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3669) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3685) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3682) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3669) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3682) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3677) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3669) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3677) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3674) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3669) : note: index 'i' range checked by comparison on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\curve25519\curve25519.c(3674) : note: feeds call on this line
c:\users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.12.1\crypto\limbs\limbs.c(47) : error C2220: warning treated as error - no 'object' file generated

**Comment by kjeremy** [comment]
Build log: [ring-errors.txt](https://github.com/briansmith/ring/files/1985130/ring-errors.txt)

**Comment by zpgaal** [comment]
There is a new VS warning that shall be disabled in the build script

https://blogs.msdn.microsoft.com/vcblog/2018/04/20/spectre-diagnostic-in-visual-studio-2017-version-15-7-preview-4/

**Comment by kjeremy** [comment]
Is there a way to get around this when pulling in previous versions of ring?

**Comment by zpgaal** [comment]
I have no idea as build.rs turns on all the warnings and disables those are "not important".
Without patching the source I don't know is VS warning can be overridden by any other way.

**Comment by briansmith** [comment]
This specific problem is fixed by PR #650, which will get released as *ring* 0.13 soon.

> I have no idea as build.rs turns on all the warnings and disables those are "not important".

We should make the "-Werror" and "/WX" flags conditional on a new "warnings_are_errors" feature flag to prevent this in the future.

**Comment by briansmith** [comment]
> We should make the "-Werror" and "/WX" flags conditional on a new "warnings_are_errors" feature flag to prevent this in the future.

It turns out I already did that for `-Werror` but not for MSVC's `/WX`. Now I've done it for MSVC too: 9409ac757d664feb8a86f1b3af8e3a5e590048ad.
