### ISSUE TITLE
Adding features to support already out there standards

### ISSUE THREAD

**Issue by elichai** [briansmith/ring#653]
Hi,
Are you planning to expand your support of crypto functions soon?

e.g:
1. secp256k1 that is vastly use in bitcoin and bitcoin-like protocols.
2. sha3/keccak.
3. ECIES.

**Comment by briansmith** [comment]
> secp256k1 that is vastly use in bitcoin and bitcoin-like protocols.

I filed Issue #654 to track adding secp256k1.

> sha3/keccak.

There's already an issue about that.

> ECIES

Please file a separate issue that mentions what freely-implementable protocol needs ECIES and what software would use the ECIES support if/when we add it.

**Comment by briansmith** [comment]
I'm closing this because each of the things you ask about should be tracked by separate issues. Thanks for asking, though!
