### ISSUE TITLE
Add ECDSA for the secp256k1 curve

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#654]
We can probably add support for the secp256k1 curve pretty easily mostly by copy/pasting the P-384 code and changing the constants (number of limbs: 4, new `q` and `n` values). It probably won't be as fast as libsecp256k1 but it would be good enough for most uses.

**Comment by MagnumOpus21** [comment]
Hi @briansmith , I am interested in contributing to this feature. Do I need to get assigned to tasks in this Repo, or are all PR's accepted? 😁

**Comment by Zeromika** [comment]
I suppose this is still available, mind if I take a look @briansmith?

**Comment by except** [comment]
Any chance this is in the works? I was looking to use implementation over others.

**Comment by briansmith** [comment]
Do you need signing or just verification?

**Comment by briansmith** [comment]
Closing this since I think people who want secp256k1 support already are satisfied with other solutions

**Comment by mineme0110** [comment]
@briansmith Is there a possibility secp256k1  support added to this library.
