### ISSUE TITLE
license verifications

### ISSUE THREAD

**Issue by aep** [briansmith/ring#663]
since ring depends on boring, there's a plethora of licenses floating around that make this pretty much impossible to use in commercial settings. 
Is there any consensus on how to fix this? One way might be to verify with google that the license exceptions they claim to have are transferable.

**Comment by pietro** [comment]
The "easiest" way would be to compile a list of licenses from the ones that are listed on the top of each file in the ring repo.

**Comment by briansmith** [comment]
> [...] there's a plethora of licenses floating around that make this pretty much impossible to use in commercial settings.

There are already companies using *ring* commercially.

> One way might be to verify with google that the license exceptions they claim to have are transferable.

My experience with them is that they are careful about licenses and they wouldn't publish someone else's work under a license other than what it was originally distributed under unless they were confident in the license situation.

**Comment by briansmith** [comment]
If you have specific concerns about licensing, you can email me at brian@briansmith.org to discuss them. In the past we've prioritized changes to *ring* to clarify license-related stuff.

**Comment by aep** [comment]
i'll try to find time to make a list first so we have a base for verification

**Comment by briansmith** [comment]
I'm going to close this because I don't think there's anything here that needs to be done.
