### ISSUE TITLE
Cross-compiling on macOS for FreeBSD fails

### ISSUE THREAD

**Issue by kellytk** [briansmith/ring#668]
$ cargo build --target x86_64-unknown-freebsd
...
   Compiling ring v0.13.0-alpha5
error: failed to run custom build command for `ring v0.13.0-alpha5
...
--- stderr
.../ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
...
.../ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:630:8: error: invalid alignment value
.align 64

Those are the two types of errors, of which there are multiple instances.

**Comment by briansmith** [comment]
> cargo build --target x86_64-unknown-freebsd

Try setting CC to point to your C cross-compiler.

**Comment by kellytk** [comment]
That doesn't appear to have made a difference.  Here's the complete activity:

$ export CC=/usr/local/bin/gcc-8
$ export CXX=/usr/local/bin/g++-8
$ export CPP=/usr/local/bin/cpp-8
$ export LD=/usr/local/bin/gcc-8
$ export CFLAGS="-I /usr/include"

$ cargo build --target x86_64-unknown-freebsd
   Compiling ring v0.13.0-alpha5 (file:///Users/kellytk/ring)
error: failed to run custom build command for `ring v0.13.0-alpha5 (file:///Users/kellytk/ring)`
process didn't exit successfully: `/Users/kellytk/ring/target/debug/build/ring-d403a9a4edcc6e00/build-script-build` (exit code: 101)
--- stdout
Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.VCBwIhD38u/Render
CARGO: /Users/kellytk/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo
CARGO_CFG_DEBUG_ASSERTIONS:
CARGO_CFG_PROC_MACRO:
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV:
CARGO_CFG_TARGET_FAMILY: unix
CARGO_CFG_TARGET_FEATURE: fxsr,mmx,sse,sse2
CARGO_CFG_TARGET_HAS_ATOMIC: 16,32,64,8,ptr
CARGO_CFG_TARGET_OS: freebsd
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: unknown
CARGO_CFG_UNIX:
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: /Users/kellytk/.cargo
CARGO_MAKEFLAGS: --jobserver-fds=3,6 -j --jobserver-auth=3,6 -j
CARGO_MANIFEST_DIR: /Users/kellytk/ring
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE:
CARGO_PKG_NAME: ring
CARGO_PKG_VERSION: 0.13.0-alpha5
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 13
CARGO_PKG_VERSION_PATCH: 0
CARGO_PKG_VERSION_PRE: alpha5
CC: /usr/local/bin/gcc-8
CFLAGS: -I /usr/include
COLORFGBG: 7;0
COLORTERM: truecolor
COMMAND_MODE: unix2003
CPP: /usr/local/bin/cpp-8
CXX: /usr/local/bin/g++-8
DEBUG: true
DYLD_LIBRARY_PATH: /Users/kellytk/ring/target/debug/deps:/Users/kellytk/.rustup/toolchains/nightly-x86_64-apple-darwin/lib:/Users/kellytk/.rustup/toolchains/nightly-x86_64-apple-darwin/lib
HOME: /Users/kellytk
HOST: x86_64-apple-darwin
ITERM_PROFILE: Default
ITERM_SESSION_ID: w2t3p0:BAB6F1E7-DAC3-4A0C-9CD4-EB9B2AEB0F7C
LANG: en_US.UTF-8
LD: /usr/local/bin/gcc-8
LOGNAME: kellytk
NUM_JOBS: 4
OLDPWD: /Users/kellytk/cloned-repos
OPT_LEVEL: 0
OUT_DIR: /Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out
PATH: /Users/kellytk/.cargo/bin:/Users/kellytk/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
PROFILE: debug
PWD: /Users/kellytk/ring
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: /Users/kellytk/.rustup
RUSTUP_TOOLCHAIN: nightly-x86_64-apple-darwin
RUST_RECURSION_COUNT: 1
SECURITYSESSIONID: 186a7
SHELL: /bin/bash
SHLVL: 1
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.sFDxQIUjJA/Listeners
TARGET: x86_64-unknown-freebsd
TERM: xterm-256color
TERM_PROGRAM: iTerm.app
TERM_PROGRAM_VERSION: 3.1.6
TERM_SESSION_ID: w2t3p0:BAB6F1E7-DAC3-4A0C-9CD4-EB9B2AEB0F7C
TMPDIR: /var/folders/74/4jwxz2wd21lggyt12731531w0000gn/T/
USER: kellytk
XPC_FLAGS: 0x0
XPC_SERVICE_NAME: 0
_: /Users/kellytk/.cargo/bin/cargo
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-unknown-freebsd")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-unknown-freebsd = None
CC_x86_64_unknown_freebsd = None
TARGET_CC = None
CC = Some("/usr/local/bin/gcc-8")
TARGET = Some("x86_64-unknown-freebsd")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-unknown-freebsd = None
CFLAGS_x86_64_unknown_freebsd = None
TARGET_CFLAGS = None
CFLAGS = Some("-I /usr/include")
DEBUG = Some("true")
running "/usr/local/bin/gcc-8" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/usr/include" "-g" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-Werror" "-D_XOPEN_SOURCE=700" "-c" "-o/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.o" "/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S"

--- stderr
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:155:1: error: unknown directive
.size _x86_64_AES_encrypt,.-_x86_64_AES_encrypt
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:156:1: error: unknown directive
.type _x86_64_AES_encrypt_compact,@function
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:328:1: error: unknown directive
.size _x86_64_AES_encrypt_compact,.-_x86_64_AES_encrypt_compact
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:331:1: error: unknown directive
.hidden GFp_asm_AES_encrypt
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:332:1: error: unknown directive
.type GFp_asm_AES_encrypt,@function
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:333:1: error: unknown directive
.hidden GFp_asm_AES_encrypt
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:412:1: error: unknown directive
.size GFp_asm_AES_encrypt,.-GFp_asm_AES_encrypt
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:415:1: error: unknown directive
.hidden GFp_asm_AES_set_encrypt_key
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:416:1: error: unknown directive
.type GFp_asm_AES_set_encrypt_key,@function
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:452:1: error: unknown directive
.size GFp_asm_AES_set_encrypt_key,.-GFp_asm_AES_set_encrypt_key
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:454:1: error: unknown directive
.type _x86_64_AES_set_encrypt_key,@function
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:629:1: error: unknown directive
.size _x86_64_AES_set_encrypt_key,.-_x86_64_AES_set_encrypt_key
^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:630:8: error: invalid alignment value
.align 64
       ^
/Users/kellytk/ring/target/x86_64-unknown-freebsd/debug/build/ring-0866268820b88bb7/out/aes-x86_64-elf.S:1021:8: error: invalid alignment value
.align 64
       ^
thread 'main' panicked at 'execution failed', build.rs:613:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by adelbertc** [comment]
@kellytk Am hitting something similar to this, did you figure out a fix?

**Comment by kellytk** [comment]
@adelbertc Unfortunately I didn't.  I plan to revisit cross-compiling early next year.

**Comment by gihrig** [comment]
@kellytk Am hitting something similar to this, did you figure out a fix?

I'm trying to cross compile on macOS Mojave to --target x86_64-unknown-linux-gnu and hitting this error.

I see elsewhere that compiling on the desired target in a Docker container is one solution, but I would prefer to avoid Docker.

**Comment by kellytk** [comment]
@gihrig Possibly.  I still haven't revisited this issue and I probably won't for another year.

**Comment by pietro** [comment]
Try setting `TARGET_CC` to point to your C cross-compiler and adding the following to `.cargo/config`:

```
[target.YOU_TARGET]
linker= "YOUR_CROSS_COMPILER"
```

**Comment by gihrig** [comment]
@pietro I've had to step away from this issue for the time being. I'll give your suggestion a try when next I work on this.

Thanks for your help! 😀
