### ISSUE TITLE
Bump untrusted version

### ISSUE THREAD

**Issue by tirkarthi** [briansmith/ring#675]
### Description ###

This project seems to use `untrusted = 0.6.1` as I can see from the cargo.toml file on master branch. Recently a security issue was fixed as part of 0.6.2 release. Please refer to https://github.com/RustSec/advisory-db/commit/3c0458d26bd19e30dc19ae5ca9a4540cc9c0394b . You can also consider adding [cargo audit](https://github.com/RustSec/cargo-audit) as part of the build step to get notified in the future.

Kindly ignore if this is irrelevant or worked upon since you are the author of untrusted and I just wanted to add a friendly reminder.

Thanks.

**Comment by briansmith** [comment]
I did this in *ring* 0.13.2.
