### ISSUE TITLE
error: failed to run custom build command for `ring v0.12.1`

### ISSUE THREAD

**Issue by z2665** [briansmith/ring#677]
When I want to use ring. The cargo build return false
The cpp  compiler on my computer is VS2017
```
[dependencies]
ring = "0.12.1"
```
ring-0.12.1\crypto\limbs\limbs.c(93) : error C2220: warning treated as error - no 'object' file generated Driver

**Comment by briansmith** [comment]
Use *ring* 0.13.2 and this will be fixed. See the many other issues about this.
