### ISSUE TITLE
Support encryption of serialized keys

### ISSUE THREAD

**Issue by never-mind** [briansmith/ring#682]
Function signature::Ed25519KeyPair::generate_pkcs8() generates the private/public key pair in the PKCS#8 (v2) format, which basically is a byte array of length 85 (for now).

From my understanding, this means, that the "private key part" of the result is unencrypted, right?
However PKCS#8 allows for an encrypted version of the private key. This is, of course, the more secure way to store that data: If the private key is stored unencrypted, an attacker could just steal it ect...

Is there a way in ring to generate the keypair and then encrypt the private-key-part of the result on the fly with some symmetric cypher (propper salt ect) to store it securely?

**Comment by briansmith** [comment]
> This is, of course, the more secure way to store that data: If the private key is stored unencrypted, an attacker could just steal it ect...

1. How are you syoring the encryption key that would be used to encrypt the private key? If we encrypt the private key with some key X then we've just shifted the problem to protecting key X.

2. IIRC, PKCS#8 encryption is generally considered a mistake. The preferred solution is to support a CMS package that can include the private key and any associated certificates, and support encryption of the CMS package. In particular, IIRC, PKCS#8 doesn't support modern encryption schemes and so you have to use CMS to get good crypto. Most implementations of encrypted PKCS#8 directly only support bad, obsolete, and/or broken crypto schemes, IIUC.

**Comment by briansmith** [comment]
I generalized the subject to `Support encryption of serialized keys`. I'm closing this, for now, as being out-of-scope. I think a good solution would be to support encrypted CMS documents holding the keys. Such a feature can/should be implemented in an external crate that uses *ring*'s existing serialization support. If/when somebody tries to do so, if there are problems with that approach, then we can open specific issues to improve *ring* to resolve those issues.
