### ISSUE TITLE
What does signature::Ed25519KeyPair::generate_pkcs8() create exactly?

### ISSUE THREAD

**Issue by never-mind** [briansmith/ring#683]
The example says it create a PKCS8 (v2) key-pair. To the best of my knowledge PKCS8 latest version is 1.2 and it is a syntax for storing private key information only.

So the term key-pair makes no sense here. PKCS8 handles only the private key. Maybe you mean something other than PKCS8 (v2) or I can't find the latest definition and it is substantially different than PKCS8 (v1.2)

**Comment by tarcieri** [comment]
> So the term key-pair makes no sense here. PKCS8 handles only the private key.

From [RFC 5915](https://tools.ietf.org/html/rfc5915) Elliptic Curve Private Key Structure, Section 1. Introduction:

> EC private key information includes a private key and parameters.  Additionally, it may include the corresponding public key.

[...]

> This syntax is useful when distributing EC private keys using PrivateKeyInfo, as defined in PKCS #8 

[...]

> When an EC public key is included in the distributed PrivateKeyInfo, the publicKey field in ECPrivateKey is used.

**Comment by never-mind** [comment]
I see. Thanks

**Comment by briansmith** [comment]
Thanks Tony!
