### ISSUE TITLE
Sync with BoringSSL's cpuinfo parser

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#721]
Basically, merge https://boringssl.googlesource.com/boringssl/+/8cd61f710b795b6f80e1b768b6ac54ba559911f4. It was skipped during the normal merge.

**Comment by LuoZijun** [comment]
Note： https://docs.rs/raw-cpuid/6.1.0/raw_cpuid/struct.CpuId.html

**Comment by briansmith** [comment]
@LuoZijun Thanks! I'm actually going to stop parsing /proc/cpuinfo in favor of a different approach, so I'm closing this.
