### ISSUE TITLE
What is the 0.13.5 version?

### ISSUE THREAD

**Issue by eoger** [briansmith/ring#726]
Is there a tag that refers to 0.13.5? Crates.io list 0.13.5 as the latest version of ring, but the `master` branch seems out of date: https://github.com/briansmith/ring/blob/09ab5b73c6a7c8d7e3ebc8cb91c922f89518348f/Cargo.toml#L12

**Comment by briansmith** [comment]
It's 704e4216a397bd830479bcd6d7dd67fc62cdbe67. I just pushed it.

**Comment by eoger** [comment]
Thanks!
