### ISSUE TITLE
Openssl-generated PKCS#8 encoded ed25519 private key cannot be imported

### ISSUE THREAD

**Issue by shahn** [briansmith/ring#740]
Hi, I used the following to generate an ed25519 private key:

`openssl genpkey -algorithm Ed25519 -out ed25519key.pem
 openssl pkcs8 -topk8 -outform DER -in ed25519key.pem -out ed25519key.pfx -nocrypt`

Transformed it into the following rust byte string:

b"\x30\x2e\x02\x01\x20\x30\x05\x06\x03\x2b\x65\x70\x04\x22\x04\x20\x4b\xae\xf7\x72\xac\x57\xbe\x0f\x0f\x1b\x75\xef\xad\x98\xc2\x09\x63\x62\x25\x0c\x41\x15\x22\xc5\x2e\x3a\x8d\xa3\x0d\x6d\xf8\x6d";

and tried to use ring::signature::Ed25519KeyPair::from_pkcs8_maybe_unchecked() to import it in to ring. This fails. I compared the key with one from the ring tests and noticed that the 5th byte is 0x20 above, but 0x00 in the ring test key. And sure enough, this key can be imported:

b"\x30\x2e\x02\x01\x00\x30\x05\x06\x03\x2b\x65\x70\x04\x22\x04\x20\x4b\xae\xf7\x72\xac\x57\xbe\x0f\x0f\x1b\x75\xef\xad\x98\xc2\x09\x63\x62\x25\x0c\x41\x15\x22\xc5\x2e\x3a\x8d\xa3\x0d\x6d\xf8\x6d";

Is this an error in OpenSSL? Should Ring do something different? Thanks!

**Comment by briansmith** [comment]
According to https://lapo.it/asn1js/#MC4CASAwBQYDK2VwBCIEIEuu93KsV74PDxt1762YwgljYiUMQRUixS46jaMNbfht the OpenSSL-generated key you pasted in is "version 33" which seems very wrong to me.

**Comment by hahseba** [comment]
You're right, the key was wrongly converted. This is not a bug.

**Comment by briansmith** [comment]
Thakns for following up!
