### ISSUE TITLE
Reduce crate size

### ISSUE THREAD

**Issue by pravic** [briansmith/ring#762]
Currently (as of 0.14) it's about 5 MB ([Crate Size 5.46 MB](https://crates.io/crates/ring)) which is not a big deal, but there are some parts that can be excluded, for sure.

Like,

* third_party/NIST (4.5 MB)
* tests (1.6 MB)
* *.txt test files (2.8 MB overall)

Unless the *crate* (not a repository) itself is self-testing, there is no point to include tests and test data in it.

**Comment by briansmith** [comment]
What is the goal you are trying to achieve? That is, why do you want it to be smaller?

When you depend on *ring*, you can run *ring*'s tests from your own program's source tree using `cargo test -p ring`. All of those test-related files are there to make that work. Sometimes people file bugs when I forget one of those files and `cargo test -p ring` breaks.

**Comment by pravic** [comment]
> you can run ring's tests from your own program's source tree 

I didn't know that you can test any of your dependencies. In that case I misreported this.
