### ISSUE TITLE
add brainpool curves support

### ISSUE THREAD

**Issue by brenzi** [briansmith/ring#793]
It would be great to have support for ECDSA with Brainpool curves, like BrainpoolP256r1:

https://tools.ietf.org/html/rfc5639#page-11

Any plans for this?

**Comment by briansmith** [comment]
What is the motivation? Which projects (please provide links) would use *ring*'s support for these curves?

**Comment by brenzi** [comment]
[We](https://www.scs.ch) are developing solutions for the energy sector, where the german BSI demands the use of brainpool curves for energy metering applications for ECDSA:
[BSI TR-03116: (german)](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03116/BSI-TR-03116-3.pdf?__blob=publicationFile&v=9)
Chap. 8.2 demands for brainpool curves exclusively

probably they distrust NIST?

I can't provide links as the project in question is not open source (yet)

**Comment by briansmith** [comment]
@brenzi (and others interested in this) I think it would be better to discuss this by email: brian@briansmith.org.

**Comment by briansmith** [comment]
Not totally against doing this but not planning to do it in my free time either.
