### ISSUE TITLE
Should hmac::SigningKey (also) implement Clone?

### ISSUE THREAD

**Issue by dvic** [briansmith/ring#806]
I see that `hmac::SigningKey`'s only field is of type `SigningContext` and it implements `Clone`. Is there a reason `hmac::SigningKey` does not implement `Clone`?

I can open a PR to add this if needed.

**Comment by dvic** [comment]
Or should I use `SigningContext::with_key` when I need to `Clone` the key? (and use the multi-step approach of `update` / `sign`)

**Comment by briansmith** [comment]
I think it's fine to derive `Clone` for `hmac::SigningKey` and `hmac::VerificationKey`, and for `aead::Key`.
