### ISSUE TITLE
Make SystemRandom Clone and Copy

### ISSUE THREAD

**Issue by pzmarzly** [briansmith/ring#808]
`SystemRandom` is [an empty struct](https://github.com/briansmith/ring/blob/569bb6ed6a6eceaea296a8ca9f6f77c3f2a66047/src/rand.rs#L81-L87) and some things would become simpler if it had `#[derive(Clone, Copy)]`.

**Comment by briansmith** [comment]
I think we should introduce a `trait CloneableSecureRandom: SecureRandom + Clone` and have SystemRandom implement it.

I'm not sure I want to commit to supporting `Copy` now. Is `Clone` good enough?

**Comment by pzmarzly** [comment]
Yes, it is.

**Comment by josephlr** [comment]
> I think we should introduce a `trait CloneableSecureRandom: SecureRandom + Clone` and have `SystemRandom` implement it.

Is there a reason to have this as a separate trait, as opposed to just having `SystemRandom` implement `Clone`?

**Comment by briansmith** [comment]
SystemRandom implements Clone and Debug as of 490f7ee. Please check out the tests I added. The clone test isn't the best but it will prevent us from regressing the Clone-ability, at least.

> > I think we should introduce a `trait CloneableSecureRandom: SecureRandom + Clone` and have `SystemRandom` implement it.
> 
> Is there a reason to have this as a separate trait, as opposed to just having `SystemRandom` implement `Clone`?

You are right, it isn't useful for `Clone` to introduce a new trait like this. Thanks for pointing that out!
