### ISSUE TITLE
Compilation fix on recent libstd

### ISSUE THREAD

**Issue by dingelish** [briansmith/ring#809]
Hi Brian,

libstd recently adds `ToOwned` to its [prelude](https://github.com/rust-lang/rust/blob/96d700f1b7bc9c53fa0d11567adb1ed2c1c27e79/src/libstd/prelude/v1.rs#L60). So two lines of `use std::borrow::ToOwned;` block compilation. Would you consider about merging the patch like [this](https://github.com/dingelish/ring/commit/9c516507fee50366e624c71c25866f027d92d2b8)?

Thanks!

**Comment by briansmith** [comment]
I think 772fc080898c7b330fff99701c2a534580ebbf8c fixes this.
