### ISSUE TITLE
Yasm is downloaded using http in appveyor.bat

### ISSUE THREAD

**Issue by realcr** [briansmith/ring#810]
Hi, I noticed this line at `appveyor.bat`:

```
powershell -Command "(New-Object Net.WebClient).DownloadFile('http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe', 'windows_build_tools\yasm.exe')"
```
Is the usage of `http://` protocol intentional? I checked and it seems like `https://` works too  for this website.

**Comment by briansmith** [comment]
> Is the usage of `http://` protocol intentional? I checked and it seems like `https://` works too for this website.

At  the time I wrote the script, HTTPS didn't work. If it works now then I'd love to see somebody fix it to use HTTPS. (We don't use the CI-built artifacts to generate any releases so this isn't a security issue.)
