### ISSUE TITLE
Document/export some of bigint

### ISSUE THREAD

**Issue by jpgoldberg** [briansmith/ring#821]
I recognize that this may be beyond the scope of what ring is for. And I understand the desire to export as little as possible, but ... I would very much like to be able to call on ways to "from" and "to" `Elem`, `PrivateExponent`, and `Modulus` along with constant time comparison end modular exponentiation. (I anticipate a need for modular inversion as well, but that isn't an immediate need.)

There are people who may need a cryptographically appropriate big integer library. Some of us are still stuck with having to work with integer fields. If there were more suitable Rust packages instead of using ring for something beyond its intended scope, I would be happy to use those.

I am _very_ new to Rust, and so I don't know what it would take to export some of the methods and structures in  `src\rsa\bigint.rs`.

**Comment by briansmith** [comment]
I addressed this offline.
