### ISSUE TITLE
hmac::Key is too large

### ISSUE THREAD

**Issue by ctz** [briansmith/ring#827]
At the minute a `hmac::Key` is fairly large (the order of 448 bytes on x64): it is two `digest::Context`s. Most of the parts of these `digest::Context`s are statically unused for the lifetime of a given `hmac::Key`: `pending` is unused once the object is constructed, `num_pending` is statically zero, `completed_data_blocks` is statically one -- obviously removing `pending` is the big win here (256 of those 448 bytes).

The cost of this would be closer coupling between the hmac and digest modules, but the benefit would be a `hmac::Key` closer to the optimal size of 128 bytes plus one pointer size.  Would you accept a PR for this?

**Comment by briansmith** [comment]
I agree. I actually have prototyped this kind of change before. I'll see if I can dig up the code.

**Comment by briansmith** [comment]
I consider this fixed by #868.

**Comment by ctz** [comment]
Thanks!
