### ISSUE TITLE
Deal with strict aliasing issues (`-fstrict-aliasing` vs `-fno-strict-aliasing`)

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#83]
Recently we started building with `-fno-strict-aliasing` because GCC was warning about strict aliasing, e.g. in https://travis-ci.org/briansmith/ring/jobs/103464242:

```
crypto/modes/gcm.c:517:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     PUTU32(ctx->Yi.c + 12, ctr);
     ^
```

Building with `-fstrict-aliasing` is really dangerous unless we're really sure the code is correct with respect to these issues. We can probably avoid turning it off as most of the C code for which it should matter will eventually be written in Rust.

However, we need to at least (a) measure the performance difference, and (b) come up with a plan to address any performance issues we find.

**Comment by agauniyal** [comment]
Hi, did you ever perform any measurements on the above issue, or changed something else? I'm in a similar boat, was wondering how to solve this problem..

**Comment by briansmith** [comment]
> I'm in a similar boat, was wondering how to solve this problem..

What is the exact problem you are having? Is it a problem you're having with *ring*, or a problem with another library?

**Comment by agauniyal** [comment]
some code of mine, but it includes passing `-fno-strict-aliasing` in order to be safe.

**Comment by briansmith** [comment]
I see. I've already removed most pointer casts and most uses of unions from this project, *ring*, so it's unlikely that we will have to do anything more regarding strict aliasing and we can probably remove `-fno-strict-aliasing`. OTOH, because we're replacing most of the C code with Rust code, we probably won't benefit from removing the `-fno-strict-aliasing` anyway, so we might just leave it.

**Comment by briansmith** [comment]
Update:
* Issue #375 tracks the removal of all unions from *ring*'s C code. There are no more unions in the C code!
* Issue #151 tracks the removal of all pointer casts from *ring*'s C code. That has been done, AFAICT. Just waiting for a second verification.
* Issue #101 tracks reading and using pointers as integers, e.g. tricks using `uintptr_t` and `intptr_t`, including abuse of `size_t`. AFAICT there are no more such casts being done. Again, waiting for a second verification of this.
* Issue #201 tracked eliminating the potential for undefined behavior via `memcpy(NULL, ...)`. There are no such `memcpy`s in *ring* any more.

**Comment by briansmith** [comment]
Note that, along the lines of #201, there are still cases where we use `memset` and `memmove` and where it is non-trivial to see that the pointers involved are not NULL. At this point we should probably just implement our own replacements for `string.h` `mem*` functions and eliminate all `#include <string.h>` to make progress in this area.
