### ISSUE TITLE
Replace crypto/cipher/e_chacha20poly1305.c with Rust code

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#84]
This code has already diverged from the BoringSSL code quite a bit and there's no much left of it in C. We should just port it to C.

**Comment by briansmith** [comment]
> We should just port it to Rust.

To do this, the following functions need to be written in Rust:

* evp_aead_chacha20_poly1305_init,
* evp_aead_chacha20_poly1305_seal,
* evp_aead_chacha20_poly1305_open,
* evp_aead_chacha20_poly1305_old_seal,
* evp_aead_chacha20_poly1305_old_open,

Then crypto/cipher/e_chacha20poly1305.c can be removed.

**Comment by briansmith** [comment]
I should also mention that I don't mean for crypto/chacha/* to be replaced with Rust code. Soon (eventually, at least) all platforms will have assembly language code (or equivalent), so it isn't worth rewriting the primitive ChaCha20 and Poly1305 functions in Rust.

**Comment by frewsxcv** [comment]
I'm currently working on this.

**Comment by frewsxcv** [comment]
@briansmith I finished `evp_aead_chacha20_poly1305_init` this morning and the tests seem to pass. I implemented `evp_aead_chacha20_poly1305_seal`, but the tests don't seem to pass right now. Is it possible I could get a very hasty review of my progress so far, to make sure I'm heading in the right direction?

https://github.com/briansmith/ring/compare/master...frewsxcv:echacha20poly1305-to-rust?expand=1

Thanks!

**Comment by briansmith** [comment]
See https://github.com/briansmith/ring/commit/3a1570c5cb9bd0fe381e80444bccf3d5fc00c0dd to see where your bug is.

Name the chacha20poly1305 module aead_chacha20poly1305, instead of using the e_ prefix.

I suggest that you don't spend too much effort trying to make the Rust code be organized like the C code. If there's an improvement to the organization, feel free to make it. It might help to avoid thinking about the `_old` code and optimize the organization of the code as though it doesn't exist.

The goal of this, of course, is to minimize "unsafe" code. So, the only places that pointers should be used is in calls to the functions `CRYPTO_chacha_20`, `CRYPTO_poly1305_init`, `CRYPTO_poly1305_finish`, and `CRYPTO_poly1305_update` functions, converting slices to pointers using `as_ptr` and `as_mut_ptr`.

Note that is is 100% OK to change the C code as much as possible. Even changing the "ABI" is OK we we aren't trying to be OpenSSL or BoringSSL compatible.

I suggest you move the `evp_aead_chacha20_poly1305_seal` function to aead_chacha20poly1305.rs. In fact, I suggest you move `CHACHA20_POLY1305` and `CHACHA20_POLY1305_OLD` and *all* the related code to that file. Then aead.rs can export them as:
```
pub use super::aead_chacha20_poly1305::{CHACHA20_POLY1305, CHACHA20_POLY1305_OLD};
```

**Comment by frewsxcv** [comment]
Should I be replace `evp_aead_chacha20_poly1305_old_seal` and friends with Rust?

**Comment by briansmith** [comment]
> Should I be replace rewriting evp_aead_chacha20_poly1305_old_seal and friends with Rust?

That would be awesome! Up to you if you want to get the non-`old` stuff reviewed and landed first.

**Comment by frewsxcv** [comment]
When you get a chance, can you glance at https://github.com/briansmith/ring/compare/master...frewsxcv:echacha20poly1305-to-rust and see if I'm getting close?

**Comment by briansmith** [comment]
Looking good. Some general suggestions:

* Drop all the `evp_aead` prefixes and the `_impl` suffixes on functions.

* If you need the "&mut [u64] -> &mut [u8]` conversion, you should put it in polyfill.rs as `u64_as_u8_mut`; see the existing `u64_as_u8` function in that module.

* You made some functions generic with an `F` type parameter. However, I think making them generic isn't necessary; you just need to make the first parameter a `fn` type, IIUC.

* `aead_open_out_max_out_in_tag_len` and whatnot belong in aead.rs, I think.

* `out: &mut [u8], nonce: &[u8], in_: *const u8, in_len: usize,` should be replaced with the use of slices, probably using the `in_out: &mut [u8]` pattern.

* Let me know if you need help with getting rid of any other instances of `core::slice::from_raw_parts_mut` and `**core::slice::from_raw_parts`.

**Comment by frewsxcv** [comment]
I addressed all your comments. When you get a chance, can you look through it again? Thanks!

**Comment by briansmith** [comment]
@frewsxcv Can you squash the changes into a smaller number of commits (2, 3, or 4 or so) and submit them as a PR? Then I can do line comments on them.

**Comment by frewsxcv** [comment]
I imagine splitting it up into multiple commits might be non-trivial; I'm not sure how to group them in a way that makes sense. Are you opposed to just having one commit?

**Comment by briansmith** [comment]
It would be good to have it split into at least two parts: (1) refactoring aead.rs into separate files with no other changes, and (2) the the new implementation of AEADs.

**Comment by frewsxcv** [comment]
> refactoring aead.rs into separate files with no other changes

Isn't that what https://github.com/briansmith/ring/pull/106 was? I guess I'll just cherry-pick that commit and then apply the state of this branch

**Comment by burdges** [comment]
Apologies if I'm kinda clueless on the details here, but..

Aren't there issues with LLVM not doing constant time code well?  I suppose that matters less for chacha20 than for a public key system, and does not matter for poly1305 at all, but still.

Related : 
https://github.com/klutzy/nadeko
https://github.com/rust-lang/rfcs/issues/847 
https://news.ycombinator.com/item?id=8747143 

Just as a note to myself, I maybe said something wrong in https://lists.gnu.org/archive/html/gnunet-developers/2015-07/msg00021.html

**Comment by briansmith** [comment]
This was done by @frewsxcv. Awesome!

**Comment by briansmith** [comment]
> Aren't there issues with LLVM not doing constant time code well?

Sorry for the late response: I just happened to stumble across this now. Yes, in general, C compilers are somewhat likely to screw up constant-time stuff. But, I have some ideas.
