### ISSUE TITLE
how to setup NDK build environment and how to cross platform build for android 

### ISSUE THREAD

**Issue by ZhihuiYang** [briansmith/ring#841]
how to setup NDK build environment and how to cross platform build for android

**Comment by pietro** [comment]
You can take a look at `/mk/travis-install-android.sh` and `mk/travis.sh` for how i tried to get android builds going. I'm in no way shape or form an android build expert though.

**Comment by briansmith** [comment]
1. Use the latest version of NDK (I tried NDK 20).
2. Make sure the C compilers referenced in step #3 are in $PATH.
2. `TARGET_CC=aarch64-linux-android21-clang cargo build --target=aarch64-linux-android` or `TARGET_CC=armv7a-linux-androideabi21-clang cargo build --target=armv7-linux-androideabi`, etc.
