### ISSUE TITLE
Switch to modern C initialization syntax

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#844]
At https://github.com/briansmith/ring/pull/842#discussion_r293963619 @josephlr suggested using the newer initialization syntax, e.g. `alignas(32) Elem x = {0};` to initialize the array to zero. This seems like a good idea. I believe we already tried and failed to do so before, but we should try again and at least document the reasoning this time.

**Comment by josephlr** [comment]
With #851 being resolved, this can be closed.

**Comment by briansmith** [comment]
I agree this isn't worth tracking. If we find some reason to do this, we'll just do it.
