### ISSUE TITLE
Solution for #461 and #491

### ISSUE THREAD

**Issue by Draphar** [briansmith/ring#860]
According to #491, you (@briansmith) want to make it possible to use the properties of the algorithms at compile time. Today, `const fn` functions can be used to achieve this. If you want, I can open a pull request with `const` accessor functions for both `aead::Algorithm` and `digest::Algorithm`.

**Comment by briansmith** [comment]
I would like to do something like this but not immediately. I'm going to close this as a duplicate of the other issues.

**Comment by Draphar** [comment]
Ok. Feel free to message me if you have decided.
