### ISSUE TITLE
'SIZE_MAX' undeclared here

### ISSUE THREAD

**Issue by ArtemGr** [briansmith/ring#865]
Ring 0.14.6 fails to build for Android (`cross build --target=armv7-linux-androideabi`):
```
crypto/constant_time_test.c:104:3: error: 'SIZE_MAX' undeclared here (not in a function)
   SIZE_MAX / 2 - 1,
   ^
thread 'main' panicked at 'execution failed', /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/build.rs:638:9
```

No such problem occurs with ring 0.14.4 and 0.14.5.

**Comment by briansmith** [comment]
@ArtemGr Are you building with clang or GCC? Which NDK and SDK? Try using clang + the latest SDK + the latest NDK.

**Comment by ArtemGr** [comment]
@briansmith 

> Are you building with clang or GCC?

Android only works with clang IIRC, there's a shim gcc binary there that links to clang.

> Which NDK and SDK? Try using clang + the latest SDK + the latest NDK.

`cross` has a very specific NDK, https://github.com/rust-embedded/cross/blob/540dc4f5a1ca8d6d95bbf4da66ce763a2352d36f/docker/android-ndk.sh#L3. Thanks for suggesting this as a workaround. I hope you agree though that going off `cross` and upgrading the NDK is a workaround and not a fix of this particular compilation/compatibility problem.

**Comment by briansmith** [comment]
> `cross` has a very specific NDK, https://github.com/rust-embedded/cross/blob/540dc4f5a1ca8d6d95bbf4da66ce763a2352d36f/docker/android-ndk.sh#L3. Thanks for suggesting the NDK upgrade as a workaround. I hope you agree though that going off `cross` and upgrading the NDK is a workaround and not a fix of this particular compilation/compatibility problem.

Please try upgrading the NDK used by cross to a newer version of the NDK and let me know if that fixes the problem. We may just need to have cross upgrade its NDK version.

I am going to release a new pre-release version of *ring* 0.15 soon. If you want to submit a PR with a workaround (include <limits.h> if and only if targeting Android, I guess) then I can include it in 0.15.

**Comment by josephlr** [comment]
@ArtemGr I was able to build and test the `constant_time::tests::test_constant_time` unit test (the only user of `crypto/constant_time_test.c` on both 0.14.6 and master using
```
cross build --target=armv7-linux-androideabi
cross test --target=armv7-linux-androideabi
```

How did you actually get this problem to happen? I cannot reproduce it.

`crypto/constant_time_test.c` includes`"internal.h"`, which includes `<GFp/base.h>`, which includes `<stdint.h>`, which [defines `SIZE_MAX`](https://en.cppreference.com/w/c/types/limits). So this should work regardless of your specific C environment, unless it's really messed up.

**Comment by ArtemGr** [comment]
You're right, the original Docker image compiles the file just fine!

```
$     docker run \
>       -v /home/artemciy/.cargo:/cargo \
>       -ti japaric/armv7-linux-androideabi bash

root@9c5be812f442:/#
root@9c5be812f442:/# cd /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6
root@9c5be812f442:/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6# "arm-linux-androideabi-gcc" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=armv7-a" "-mthumb" "-mfpu=vfpv3-d16" "-mfloat-abi=softfp" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-o/tmp/constant_time_test.o" "crypto/constant_time_test.c"
In file included from crypto/constant_time_test.c:46:0:
crypto/constant_time_test.c: In function 'bssl_constant_time_test_main':
crypto/internal.h:231:27: warning: inlining failed in call to 'constant_time_eq_w': indirect function call with a yet undetermined callee [-Winline]
 static inline crypto_word constant_time_eq_w(crypto_word a,
                           ^
crypto/constant_time_test.c:52:15: warning: called from here [-Winline]
   crypto_word c = op(a, b);
               ^
In file included from crypto/constant_time_test.c:46:0:
crypto/internal.h:231:27: warning: inlining failed in call to 'constant_time_eq_w': indirect function call with a yet undetermined callee [-Winline]
 static inline crypto_word constant_time_eq_w(crypto_word a,
                           ^
crypto/constant_time_test.c:52:15: warning: called from here [-Winline]
   crypto_word c = op(a, b);
               ^
root@9c5be812f442:/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6#
```

We were using a modified image that's pretty much the same except the target API level was changed from 21 to 19 in order to cover more Android devices. Thanks for your help, @josephlr !
