### ISSUE TITLE
Support for weaker RSA keys used in DNSSEC

### ISSUE THREAD

**Issue by andrewtj** [briansmith/ring#870]
While 2048-bit RSA is in use for many KSKs at the top of the hierarchy, weaker keys are still in use for ZSKs. Here's what is used in a selection of names that are of interest to me:

|Name    |ZSK                        |KSK                        |
|--------|---------------------------|---------------------------|
|       .|2048-bit RSASHA256         |2048-bit RSASHA256         |
|     au.|2048-bit RSASHA256         |2048-bit RSASHA256         |
| com.au.|2048-bit RSASHA256         |1024-bit RSASHA256         |
|  id.au.|2048-bit RSASHA256         |1024-bit RSASHA256         |
| net.au.|2048-bit RSASHA256         |1024-bit RSASHA256         |
| org.au.|2048-bit RSASHA256         |1024-bit RSASHA256         |
|    com.|2048-bit RSASHA256         |1024-bit RSASHA256         |
|    net.|2048-bit RSASHA256         |1024-bit RSASHA256         |
|    org.|2048-bit RSASHA1-NSEC3-SHA1|1024-bit RSASHA1-NSEC3-SHA1|

This is likely to continue to be the case for some time yet. Verisign operate a few of the names above and are only now in the midst of switching from [1024-bit to 1280-bit KSKs](https://indico.dns-oarc.net/event/29/contributions/660/).

As these keys are unavoidable, would you consider supporting them in some form for signature verification? Perhaps there could be dedicated `ring::signature::RsaParameters` behind a feature flag whose parameters are tied to some metric in the hierarchy, such as the weakest parameters needed to support com, net, and org.

I am currently using OpenSSL to fill the gap so lack of support for weak keys isn't that big a deal, but it would be nice to drop OpenSSL.

/cc @bluejekyll and @partim as I think they're in the same boat with their projects.

**Comment by briansmith** [comment]
Sure, it's fine to add new variants that accept RSA 1024-8192 with SHA-1 and SHA-256 named with the `_FOR_LEGACY_USE_ONLY` suffix like RSA_PKCS1_2048_8192_SHA1_FOR_LEGACY_USE_ONLY now is. When doing so, please go through all the test vectors in *ring* and import the test vectors from the original source that were removed because the RSA key was too small.

My understanding is there is no need for non-SHA-1, non-SHA-256 variants, so let's not bother with those.

**Comment by andrewtj** [comment]
Okay great, thanks. I've made a start on implementing this but I've found that a 2040-bit key raises a panic in [limb.rs:245](https://github.com/briansmith/ring/blob/6c3805840e8b872ecd903404b2c9e80b307eb225/src/limb.rs#L245):
```
---- test_signature_rsa_pkcs1_verify stdout ----
thread 'test_signature_rsa_pkcs1_verify' panicked at 'assertion failed: `(left == right)`
  left: `255`,
 right: `256`', src/limb.rs:245:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
rsa_pkcs1_verify_tests.txt: Test panicked.
Digest = SHA256
Key = 308201070282010000e9bcb0e5fe68c4ebd4dd299f1434ff2378bd1e5261eda8d7466d41e1485a92118888306dc03a7a448f459556fcc2375cf8ca4f26ad2b4203952b6b60f4f23d834e30f19650753a02e44606f39807d9c1cff27114e76cac6d4ee02e3c68aea27bdf5037ce912212725af0294cf4df5173a61349ddd40f1c21bdd4a876d1b52541e1a784d11e1ca5e1615ba0c8f978534e9de112c379f530a31014425e907c9a881449c90c764f12f9831dda121ea43c7c034f5829ce4fd1445749ee461f72b763b2ab4d0cf838d48140499564985132a69dc537259905cb69dcdc658c593620c26e822ee7414c9adb1132341201689a30efa1ed733a6b5b149c81a87e02ae0b020103
Msg = ""
Sig = 951cea8d14c4fb4ae98746e4c404105f63e880692584155e7f6aa053e9e897ab07ebabf408860c0c725d454b0d206eec7668382dfb2d005f31182b1836ba1f449eb5dcfe026bc500fbe41250070e8f148bb8e4011a5730d1e4f26b228e484fa8c1211234a2d599c55c678cbed083a5dbe7857caad189cb7dd4ec3db5f16f2bef13aa2c517c3ad13511615c6171ea783c742ed87a9d451a73b968de26c2928313ebab7cabfa824988452cbc606c3968c8c7b41de733d9b6f62425512a64f89cd235681abc8498797980a646c51c3ae5dd18fbefbc813637fc6d633bb799d7dbb3c725b2f16b4b68bcdb5a4a859667f5bacb365a358d9266dd2158dbc1bed112
Result = P
thread 'test_signature_rsa_pkcs1_verify' panicked at 'Test failed.', src/test.rs:371:9
```
A similar panic can be raised by using a 4088-bit key with *ring* 0.14.16 (line 242 instead).

I don't really know what I'm looking at here, where should I go from here?

**Comment by briansmith** [comment]
> A similar panic can be raised by using a 4088-bit key with _ring_ 0.14.16 (line 242 instead).

We should fix this one first, then see if it fixes the rest.

**Comment by briansmith** [comment]
> > A similar panic can be raised by using a 4088-bit key with _ring_ 0.14.16 (line 242 instead).
> 
> We should fix this one first, then see if it fixes the rest.

I see. This is easy for me to fix. Can you submit a PR that adds these new test vectors for keys between 2048 and 8192 bits? Then I'll fix this bug.

**Comment by briansmith** [comment]
> I see. This is easy for me to fix. Can you submit a PR that adds these new test vectors for keys between 2048 and 8192 bits? Then I'll fix this bug.

Actually, never mind. I have such test vectors already. Not sure why I didn't push this fix earlier.

**Comment by vavrusa** [comment]
FWIW I added the constants in https://github.com/vavrusa/ring/tree/rsa_1024, but they're behind feature flag and not in this specific format (`_FOR_LEGACY_USE_ONLY`)

**Comment by vavrusa** [comment]
There's a non-insignificant amount of hosting companies with RSASHA512 and 1024b ZSK (e.g. forpsi.cz), it might be worth considering adding `_FOR_LEGACY_USE_ONLY` for this algorithm too.

**Comment by andrewtj** [comment]
I'd only be interested in 1024-bit RSASHA512 if it were used by a TLD.

**Comment by briansmith** [comment]
I merged PR #871 into master.

**Comment by briansmith** [comment]
I just released *ring* 0.16.11 with this feature.

**Comment by vavrusa** [comment]
> I'd only be interested in 1024-bit RSASHA512 if it were used by a TLD.

Is this decided or would you still be open to add `_FOR_LEGACY_USE_ONLY` for SHA512?
It's used by a few TLDs (and a bunch of IDN TLDs):

```
.alstom
.barcelona
.bauhaus
.bcn
.cat
.cologne
.erni
.eurovision
.eus
.gal
.gmx
.ifm
.lacaixa
.madrid
.man
.mango
.nrw
.quebec
.radio
.ruhr
.sap
.scot
.seat
.sport
.swiss
.vu
```

**Comment by briansmith** [comment]
> > I'd only be interested in 1024-bit RSASHA512 if it were used by a TLD.
> 
> Is this decided or would you still be open to add `_FOR_LEGACY_USE_ONLY` for SHA512?
> It's used by a few TLDs (and a bunch of IDN TLDs):

If somebody sends a PR for it, that includes tests, I'll add it.
