### ISSUE TITLE
Undefined symbol for _GFp_x25519_NEON on ios armv7

### ISSUE THREAD

**Issue by kylefleming** [briansmith/ring#877]
## Description

I'm encountering the following linker issue when integrating ring (via a rust lib that depends on ring) into my ios app.

```
Undefined symbols for architecture armv7:
  "_GFp_x25519_NEON", referenced from:
      ring::ec::curve25519::x25519::x25519_neon::h143823cc79dca7d5 in libxx.a(ring-86258846f6e684aa.ring.ulab98nq-cgu.5.rcgu.o)
```

## Investigation

It appears BoringSSL is `ifdef`ing out `x25519_NEON` (`GFp_x25519_NEON`) on Apple platforms ([BoringSSL](https://github.com/google/boringssl/blob/09050cb498336655883157c6e6055db9e5542857/crypto/curve25519/asm/x25519-asm-arm.S#L26) / [ring](https://github.com/briansmith/ring/blob/b791dd65857c5f017510a7cd197b46e60c21844d/crypto/curve25519/asm/x25519-asm-arm.S#L26)), however ring is referencing `GFp_x25519_NEON` on all ARM platforms, leading to an undefined symbol on Apple ARM platforms ([referenced here](https://github.com/briansmith/ring/blob/b791dd65857c5f017510a7cd197b46e60c21844d/src/ec/curve25519/x25519.rs#L148))

I couldn't determine the reason that Apple ARM platforms were disabled from using the NEON versions, but it appears to have been added in [this commit](https://boringssl.googlesource.com/boringssl/+/aff72a38052508664439b6d8bcaca97e23c6cc6a).

## Recommendation

In addition to changing ring to only reference `GFp_x25519_NEON` when it's been defined, it's also possible that the Apple ARM platforms can be re-enabled to use the NEON versions in BoringSSL upstream.

**Comment by briansmith** [comment]
Thanks for the bug report. Please see if #878 works.

**Comment by kylefleming** [comment]
Thanks for the quick response. If possible, it would beneficial if you could also integrate the patch into version `0.14.x`. Thanks!

**Comment by briansmith** [comment]
> Thanks for the quick response. If possible, it would beneficial if you could also integrate the patch into version `0.14.x`. Thanks!

Thanks for reporting this and your fast feedback. I've merged the PR into master.

There are a lot of reasons to upgrade to 0.16 (which should get released today or tomorrow), I recommend you do that instead. Check the git history on master between 0.14.6 and now to see why.

If you really need it in 0.14.x, please email brian@briansmith.org about a paid support agreement.
