### ISSUE TITLE
Cannot make an HKDF PRK from bytes

### ISSUE THREAD

**Issue by rozbb** [briansmith/ring#880]
The MLS protocol requires users to receive path secrets and pass them into HKDF-Expand. That means the user must construct a `Prk` from bytes. However, there is no way to do this currently.

**Comment by briansmith** [comment]
> The MLS protocol requires users to receive path secrets and pass them into HKDF-Expand. That means the user must construct a `Prk` from bytes. However, there is no way to do this currently.

If I understand correctly, for MLS what would be ideal is the ability to directly generate a random PRK for `path_secret[0]`, right?

**Comment by briansmith** [comment]
In *ring* 0.16.5 we have https://briansmith.org/rustdoc/ring/hkdf/struct.Prk.html#method.new_less_safe. However, I am hoping to remove it in *ring* 0.17.0. If the ability to generate a random `Prk` from the PRNG is sufficient, then I'll add that before I remove `new_less_safe`.

**Comment by rozbb** [comment]
Getting a random path secret is nice (although my current workaround of making a random salt + secret and `extract`ing that would probably work just fine). But what I actually need `from_bytes` for is for using path secrets that I receive in `DirectPath`s. In particular, `DirectPathNode` has an `encrypted_path_secret` field that users need to decrypt to a `Prk` that can be passed to HKDF-Extract.

On the flip side of this, I also need a `as_bytes` method for `Prks`. Storing `path_secret` as an `Okm` doesn't help me, since I can only use it once, so if I serialize `path_secret`, I can't turn it into a `Prk` to use in a ratchet, and if I ratchet it, I can't serialize it.

**Comment by briansmith** [comment]
> Getting a random path secret is nice (although my current workaround of making a random salt + secret and extracting that would probably work just fine). 

Right, I realized this after I submitted my previous comment. This is how HKDF is "supposed" to be used, IIUC.

> But what I actually need from_bytes for is for using path secrets that I receive in DirectPaths. In particular, DirectPathNode has an encrypted_path_secret field that users need to decrypt to a Prk that can be passed to HKDF-Extract.

Thinking about this for only one minute, this seems like a potential flaw in the protocol. Regardless, the ability to construct a `Prk` from its raw value is available currently.

> On the flip side of this, I also need a as_bytes method for Prks. Storing path_secret as an Okm doesn't help me, since I can only use it once, so if I serialize path_secret, I can't turn it into a Prk to use in a ratchet, and if I ratchet it, I can't serialize it.

Create a new `PathSecret` type that implements `From<hkdf::Okm<'_, hkdf::Algorithm>>` This will give you access to the raw output of the HKDF operations as bytes. Then you can do whatever and then also create a `Prk`. Check out https://github.com/ctz/rustls/pull/279 where I did something similar.

**Comment by rozbb** [comment]
Ah I see. So as long as I can continue to make a `Prk` from bytes, this should be fine.
Closing bc this works and I just forgot to Cmd+Shift+R the docs page so I never saw 0.16.5 :p
