### ISSUE TITLE
Compiling on Ubuntu

### ISSUE THREAD

**Issue by knokko** [briansmith/ring#884]
I just tried to compile one of my projects requiring Ring on an Ubuntu computer, but it failed:

```
Compiling ring v0.16.5
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.5/src/lib.rs:69:1
   |
69 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ring`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The Ring dependency is in the dependencies section of my Cargo.toml like this:
```
[dependencies]
ring = "*"
```

My rustc version is 1.35.0,
Any idea why this happens? Or why it compiles fine on Windows 10?
Please let me know if you need any additional info.

**Comment by briansmith** [comment]
The alloc crate is new in Rust 1.36, so just upgrade to Rust 1.36 and you should be good to go. (See https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html#whats-in-1.36.0-stable)
