### ISSUE TITLE
AES API isn't intuitive for the uninitiated

### ISSUE THREAD

**Issue by Xaeroxe** [briansmith/ring#887]
I'm by no means a cryptography expert, but I have some experience using cryptography with other APIs. Specifically Crypto JS.

I wrote a simplistic password manager in HTML and JavaScript [using this API](https://www.npmjs.com/package/crypto-js#object-encryption). Crypto JS presents a simple two argument function. I'm trying to parse this data in Rust now, and am looking into using your AES implementation, but I'm having difficulty producing a few lines that would have the same input and output as my Crypto JS approach.

I know I need to use the AES 256 algorithm, and I don't have the ability to use a nonce so I'm going with the LessSafeKey, however I still have two questions remaining.

1. How can I generate a fixed length key from a variable length string similar to CryptoJS?
2. [The LessSafeKey still requests a nonce when decrypting.](https://briansmith.org/rustdoc/ring/aead/struct.LessSafeKey.html#method.open_in_place) I thought the purpose of it was that it didn't need a nonce, and I'm not sure how to correctly provide the one being asked for here. What should be provided here?

I hope this issue doesn't come off as flippant, as I recognize I'm dabbling in things I barely understand. I'm mostly just struggling to use the API as presented and would like some assistance.

**Comment by briansmith** [comment]
[using this API](https://www.npmjs.com/package/crypto-js#object-encryption). Crypto JS presents a simple two argument function.

Please log the output value of `ciphertext` in `var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data), 'secret key 123');` in the example documentation you provided. I'm pretty sure there is a nonce there.

**Comment by Xaeroxe** [comment]
[passwords.txt](https://github.com/briansmith/ring/files/3498445/passwords.txt)

This is a file output by my password manager. The data seems to be base64 encoded. The output of decoding it isn't easy to print cleanly. It was encrypted with the password "Test1234". A successful decryption should result in some JSON with a couple example passwords.

**Comment by Xaeroxe** [comment]
If "salt" and "nonce" mean the same thing in this context I might have found the data you're looking for though.

**Comment by Xaeroxe** [comment]
Okay so on further research it seems not all AES implementations are made equal. I was operating under the mistaken belief that AES was a format much like JSON or Base64. My data is encrypted with CBC mode, whereas this crate only supports GCM.

After some research I can see GCM is the more desirable of the two. I guess I should try and figure out how to migrate to it. I've got a lot of thinking to do on that, so in the mean time I'm going to close this issue. Thanks for prodding me in the right direction.
