### ISSUE TITLE
There is no way to construct hkdf::Algorithm with HMAC_SHA1_FOR_LEGACY_USE_ONLY

### ISSUE THREAD

**Issue by zonyitoo** [briansmith/ring#911]
In #754 has decided to deprecate SHA1 in ring. But for legacy crates, we still need SHA1 for compatibility.

I hope SHA1 could be enabled by a feature.

**Comment by briansmith** [comment]
@zonyitoo I would accept an MR to add this.

**Comment by briansmith** [comment]
PR #926 addressed this.
