### ISSUE TITLE
How to use SM2/3/4 in ring

### ISSUE THREAD

**Issue by HaoXuan40404** [briansmith/ring#916]
Is there possible to support China business crypto, like SM2 algorithm?

Note:
The secret algorithm is the abbreviation of the national commercial cryptographic algorithm. Since 2012, the National Password Authority to the “People’s Republic of China password industry standard” approach, have announced the SM2 / SM3 / SM4 and other cryptographic algorithm standards and application specifications. Which “SM” on behalf of “business crypto”, that is used for commercial, not involving state secrets of the password technology. SM2 is a public key cryptography algorithm based on elliptic curve cryptography, including digital signature, key exchange, and public-key encryption. It is used to replace international algorithms such as RSA / Diffie-Hellman / ECDSA / ECDH. SM3 is a hash algorithm, SM4 is a block cipher used to replace DES / AES and other international algorithms. SM9 is an identity-based cryptographic algorithm that can replace PKI / CA based on digital certificates. By deploying the secret algorithm, you can reduce the security risks caused by weak passwords and bug implementations and the overhead of deploying PKI / CA.

**Comment by Pencil-Yao** [comment]
I have same problem

**Comment by luojia65** [comment]
Yes, this is the main blocker in our project too. We are required to use SM2/3 for production use but by now we cannot use it through `ring`.

**Comment by briansmith** [comment]
No plans to do this. I don't even know who would be open to funding it.
