### ISSUE TITLE
Code coverage reports are indicating <90% code coverage

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#932]
Previously, I remember coveralls reporting >90% code test coverage, but not it is reporting ~85%. Why?

Recently in #927 we switched the code coverage configuration, so perhaps this change in configuration is changing how code coverage is being measured, and maybe nothing actually changed.

Or, maybe there is another problem.

Regardless, we should get the code coverage close to 100%.

**Comment by pietro** [comment]
Coverage went down 10% on 4455a4e987c817e534472b6bb3acf4e664a77df5: https://coveralls.io/builds/27771003

Specifically the x86_64 build: https://coveralls.io/jobs/57148575

I don't know if the changes confused kcov/coveralls. some files are listed multiple times and the number of relevant lines changes drastically.

**Comment by briansmith** [comment]
The code coverage isn't as high as we'd like but it is back to where we expect it to be. I believe the problem was that we changed some stuff in the Travis CI configuration that reduced the coverage measurement. Now we're using GitHub Actions and a totally different way of measuring coverage (LLVM source-based coverage). I'm going to close this.
