### ISSUE TITLE
Add x86_64-unknown-linux-musl to CI/CD

### ISSUE THREAD

**Issue by Andy320** [briansmith/ring#934]
error is : 
/root/xxx/target/x86_64-unknown-linux-musl/release/deps/libring-25b4eec2a3595d27.rlib: error adding symbols: File format not recognized
          collect2: error: ld returned 1 exit status

while compiling is successful :  
cargo build --release --target x86_64-unknown-linux-gnu 
--------------------------------------------------------------
env: 
ubuntu 18.04
llvm 9.0
gcc 9.2
musl 1.1.24
--------------------------------------------------------------

my question is : 
Does ring support musl ？

thanks a lot

**Comment by briansmith** [comment]
> Does ring support musl ？

It is intended to support musl but we don't test it yet. Do you have any other diagnostics?

My guess is you need to use TARGET_CC to tell the build system to use the musl-targetting C toolchain.

**Comment by Andy320** [comment]
@briansmith 
Correctly. I checked my dockerfile, and it has below lines:
ENV TARGET_CC=$OUTPUT/bin/$TARGET-gcc
ENV TARGET_CXX=$OUTPUT/bin/$TARGET-g++
ENV TARGET_C_INCLUDE_PATH=$OUTPUT/$TARGET/include/

Now I changed my dockerfile, removed above lines. And the build for musl and llvm successful.

$ alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src mycompiler:v1.0'
$ rust-musl-builder cargo build --release

Finished release [optimized] target(s) in 11m 22s

**Comment by osa1** [comment]
I'm having the same problem. The CI logs are [here](https://github.com/osa1/tiny/runs/446794154?check_suite_focus=true) (expand the failing job and scroll to the bottom). Interestingly I'm using the same system as the CI box (Ubuntu 18.04) and locally I can build it just fine. No idea what the difference is.

**Comment by briansmith** [comment]
I'm glad you got it working. Morphing this into "Add x86_64-unknown-linux-musl" since it seems you got it working.

**Comment by briansmith** [comment]
Closing in favor of the general issue: https://github.com/briansmith/ring/issues/713.
