### ISSUE TITLE
Consider enabling auto build cancel on Travis CI

### ISSUE THREAD

**Issue by cbiffle** [briansmith/ring#936]
From the build behavior I'm currently seeing, I'm jumping to the conclusion that the project's Travis CI config may not have automatic build cancellation enabled for PRs. If I'm wrong, and the behavior I'm seeing is for some other reason, then ignore me. :-)

I created a PR that kicked off a CI build, in part because I don't have access to any Ubuntu machines and I wanted to check my changes to `.travis.yml`. They were wrong, of course, so I updated the PR. 90 minutes later the original build is still running -- I don't appear to be able to cancel it. It would improve the contributor experience if updating a PR canceled the now-obsolete builds.

It's also possible you've deliberately disabled this feature for a reason I haven't thought of, but just in case it *wasn't* deliberate, I thought I'd ask. :-)

**Comment by briansmith** [comment]
Thanks. "Auto cancel pull request builds" was enabled but "Auto cancel branch builds" was not. I tentatively enabled "Auto cancel branch builds" and I'll see if that does the right thing going forward.
