### ISSUE TITLE
Document the ASN.1 codec

### ISSUE THREAD

**Issue by DemiMarie-parity** [briansmith/ring#947]
Currently, the decoder is `#[doc(hidden)]`, and the encoder is private.  It would be nice if these were public, since they are likely safer and faster than ASN.1 libraries such as yasna.

**Comment by briansmith** [comment]
I'd like to say "PRs welcome" but honestly I'm not even interested in reviewing PRs for documenting the ASN.1 code. I think the bigger issue with the ASN.1 code is the testing; I'd love to see more testing or proving of the ASN.1 code.
