### ISSUE TITLE
Where all the crypto at?

### ISSUE THREAD

**Issue by cheako** [briansmith/ring#953]
I've joined some chat rooms asking about stuff and for the past few days have had no response.

Looking for a refresher on ECC.  I remember reading about Bitcoin's HD wallets.  For my project I think I will be using some of those concepts.

Users edit notes and the edits are eyncripted and signed.  Then the users can share the notes for both read and write access levels.
WebSocket is used for sharing.
Sharing is done by link:. https://server.com/notes/#eyncriptionkeymaterial

11:51 PM <cheakoirccloud> Hello, I'm starting a new project and I think I'm choosing ECC Domain Parameters.  I thought I was just going to pick one from a selection, but it's not that simple... is it.
11:53 PM <cheakoirccloud> I remember seeing something where periodically this group was going to release new parameters where everyone could verify that these are the next paramiters in the "list" without "everyone" being able to know the parameters ahead of time.
11:56 PM <cheakoirccloud> Anyway, regardless of what parameters I choose.  I'm writing HTML5/wasm "PWA".  I want to be able to enter something into my phone and have it show up on another pone or tablet.  I have a web-server and planed on using web sockets to handle the data shuffling.
12:00 AM <cheakoirccloud> The server should get encrypted packets that are signed in the clear.  The server should verify the signature and store the packet in a key/value data-store.  Both server and browser/client should be able to validate that this packet belongs at the key.  Ideally the server shouldn't have any idea what's going on, though I'm not sure that's possible.
12:05 AM <cheakoirccloud> I haven't researched using Twister, Sone, ect.

I've settled on just using secp128k1, but I don't know what it means just that it's half Bitcoin's.

**Comment by Darkspirit** [comment]
Documentation: https://briansmith.org/rustdoc/ring/
https://github.com/briansmith/ring/tree/master/tests has further examples on how to encrypt and decrypt.
See how other crates are using ring: https://crates.io/crates/ring/reverse_dependencies

https://github.com/seanmonstar/warp is a simple Rust web server which also supports web sockets.

You could also fork and contribute to https://github.com/xwiki-labs/cryptpad or https://github.com/mozilla/send.

Is this is a commercial project?

**Comment by briansmith** [comment]
Closing this as inactionable.

**Comment by briansmith** [comment]
> Looking for a refresher on ECC. I remember reading about Bitcoin's HD wallets. For my project I think I will be using some of those concepts.

That's understandable, but that isn't what this issue tracker is for.
