### ISSUE TITLE
How to generate random numbers?

### ISSUE THREAD

**Issue by toadzky** [briansmith/ring#954]
Since the documentation is pretty sparse, I'm not sure how to go about this. 

I've done 

```rust
let gen = SystemRandom::new();
let random_number: u64 = ring::rand::generate(&gen)?.expose();
```

and that gives me the error:

```
the trait `ring::rand::sealed::RandomlyConstructable` is not implemented for `u64`
```

What am I missing?

**Comment by briansmith** [comment]
> the trait `ring::rand::sealed::RandomlyConstructable` is not implemented for `u64`
> What am I missing?

I will likely be adding support for constructing random `u64` soon. Until then, you can construct a random `[u8; 8]` and then use `u64::from_ne_bytes` to convert it to a random `u64`.

**Comment by keepsimple1** [comment]
+1.  Could we please have some example added to the [doc](https://briansmith.org/rustdoc/ring/rand/index.html)?
