### ISSUE TITLE
Ed25519KeyPair verification outputs "Unspecified" ~1/3 of the time in ring 0.16.11

### ISSUE THREAD

**Issue by TheBats** [briansmith/ring#955]
I use the crate, ring = "0.16.11". 

At the beginning of my code I generate a key_pair using the code given by the documentation

`let rng = rand::SystemRandom::new();
		let pkcs8_bytes = signature::Ed25519KeyPair::generate_pkcs8(&rng).unwrap();
		let key_pair = signature::Ed25519KeyPair::from_pkcs8(&pkcs8_bytes.as_ref().clone()).unwrap();`

and then I save the pkcs8_bytes variable as a vector in a static variable to be able to retrieve it later

`static mut PKS: Vec<u8> = Vec::new();`

Now I use the static variable to generate a key_pair I can use to verify a leu
```
let key_pair = signature::Ed25519KeyPair::from_pkcs8(unsafe{PKS.as_ref()}).unwrap();
let sig = key_pair.sign(&transaction.get(index).unwrap()[..]);
let public_key = signature::UnparsedPublicKey::new(&signature::ED25519,    unsafe{PUBLICKEY});
		
       match public_key.verify(&transaction.get(index).unwrap()[..], sig.as_ref()) {
		Ok(m) => {
			println!("Public key oke: {:?}", m);
			println!("Valid transaction: {:?}", transaction.get(index));

			unsafe{AV_TRANSACTIONS.push(ITEM {
				key: transaction.get(index).unwrap().to_vec(), value: transaction,
			});}
		},
		Err(e) => println!("Error: {:?}", e),
	}
```

I don't know I am doing anything wrong or if it is a bug but I do get an "Unspecified" error ~1 time out of 3.

**Comment by briansmith** [comment]
@TheBats Thanks. I will take a look at this for the next 0.16.n release.

**Comment by briansmith** [comment]
@TheBats Did you figure out the problem?

What architecture are you running this on? x86-64? 32-bit x86? ARM?

I noticed you are using lots of `unsafe` in your demo code so I don't know if it is a good example.

I made this:

```rust
#[test]
fn issue_955() {
    let rng = rand::SystemRandom::new();
    loop {
        let pkcs8_bytes = signature::Ed25519KeyPair::generate_pkcs8(&rng).unwrap();
        let key_pair = signature::Ed25519KeyPair::from_pkcs8(pkcs8_bytes.as_ref()).unwrap();
        const MESSAGE: &[u8]= b"";
        let signature = key_pair.sign(MESSAGE);
        let public_key = signature::UnparsedPublicKey::new(&signature::ED25519,    key_pair.public_key().as_ref());
        assert!(public_key.verify(MESSAGE, signature.as_ref()).is_ok());
        print!(".");
    }
}
```

I would expect that if there were an intermittent issue within *ring*, then this code would fail sometimes. I ran it with `cargo test issue_955 -- --nocapture` and it runs fine. What am I overlooking?

**Comment by TheBats** [comment]
I am running it on x86_64 but now it is fixed. I changed my code a lot and updated it so I won't be explain how I fixed it. I am sorry I forgot to post my fix or even to close it

**Comment by briansmith** [comment]
Thanks for responding @TheBats. Just to confirm, you now think that this was a problem in your own code, and not a problem in *ring*? Or did you patch *ring*? Thanks!

**Comment by TheBats** [comment]
It definitely was in my code, I think it was because the length of the key was not correct... It might be useful to make the error a bit more precise
