### ISSUE TITLE
"-Wpedantic" not recognized as warning flag, breaking windows-gnu build.

### ISSUE THREAD

**Issue by nes77** [briansmith/ring#957]
When attempting to build ring v0.16.11 on Windows 10 (stable-x86_64-pc-windows-gnu), I get the following error.

```
--- stderr
crypto/fipsmodule/ec/gfp_p384.c: In function 'GFp_p384_elem_neg':
crypto/fipsmodule/ec/gfp_p384.c:201:8: warning: declaration of 'is_zero' shadows a global declaration [-Wshadow]
crypto/fipsmodule/ec/gfp_p384.c:70:20: warning: shadowed declaration is here [-Wshadow]
third_party/fiat/curve25519.c:60:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
In file included from third_party/fiat/curve25519.c:62:0:
third_party/fiat/./curve25519_64.h:12:16: error: ISO C does not support '__int128' type [-pedantic]
third_party/fiat/./curve25519_64.h:13:18: error: ISO C does not support '__int128' type [-pedantic]
thread 'main' panicked at 'execution failed', C:\Users\Nicholas\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.11\build.rs:641:9
```

It seems to be related to the following line.

https://github.com/briansmith/ring/blob/ddfa683266e8ce41c06feb9f46503dd4e1d47ab1/third_party/fiat/curve25519.c#L60

When I remove the "W" from `-Wpedantic`, the errors go away and the code compiles correctly.

```c
#if defined(BORINGSSL_CURVE25519_64BIT)
#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-pedantic"
#endif
#include "./curve25519_64.h"
#else
#include "./curve25519_32.h"
#endif  // BORINGSSL_CURVE25519_64BIT
```

**Comment by nes77** [comment]
Rust toolchain version is 1.41.1.

**Comment by briansmith** [comment]
What GCC version are you using (`gcc --version`)?

**Comment by nes77** [comment]
Ran the following build file to check

```rust
fn main() {
    cc::Build::new()
        .file("src/main.rs")
        .flag("--version")
        .compile("test");
}
```

`gcc.exe (rubenvb-4.6.3) 4.6.3`

**Comment by nes77** [comment]
When I run with a more recent version of gcc (9.1), there is no failure.

**Comment by briansmith** [comment]
GCC 4.8 is currently the minimum version supported.

**Comment by josephlr** [comment]
Additional context, `-Wpedantic` was added [here](https://github.com/gcc-mirror/gcc/commit/29438999d161c4ff2ecd4eb6b8c65c7d48557104) and was part of GCC 4.8 (see [4.8 release notes](https://gcc.gnu.org/gcc-4.8/changes.html)), which was released in March 22, 2013.

I requiring your compiler be less than 7 years old is reasonable.
