### ISSUE TITLE
ECDSA verify failure for signature obtained from Intel SGX SDK

### ISSUE THREAD

**Issue by brenzi** [briansmith/ring#967]
I'm trying to verify a signature derived inside an SGX enclave. The signature is obtained from the `ecc_handle` in Intel's SGX SDK [here](https://github.com/intel/linux-sgx/blob/4589daddd58bec7367a6a9de3fe301e6de17671a/sdk/tlibcrypto/sgxssl/sgx_ecc256.cpp#L57)
Or, In [our code](https://github.com/scs/substraTEE-worker/blob/23e77cab0a0687cda04fd8ef59ba3161e223ce66/enclave/src/attestation.rs#L611)

The raw pubkey (0x04 for uncompressed and then X and Y each 32 bytes concatenated) is
```
0497a3729eea3fbe0cfe779590db8b088c55f3a9f8b2c9b860e82443c79d06682e43a4f45d2cabc20896c2e70df66cfcf8c3693ec24c86a8deedb593f08b89e21f
```
The raw signature is 
```
78691aa21698afc1442c611b95d542fb4082f4fd3e5c41404455ad99faeab29255471a993df2a2f7da23e101cf00c28446df903c674bd100c3567366cfc56c19
```

Our verification code with ring
```
// 0x04 stands for uncompressed format
        // ring uses x,y in big-endian order
        // SGX uses NID_X9_62_prime256v1 curve https://github.com/intel/linux-sgx/blob/4589daddd58bec7367a6a9de3fe301e6de17671a/sdk/tlibcrypto/sgxssl/sgx_ecc256.cpp#L57
        // equivalent to NIST P-256 according to https://tools.ietf.org/search/rfc4492#appendix-A
        // SGX report stores X,Y in little endian, so we have to reverse
// problem now: public key point x,y as derived here is not on the curve.
        let mut pubkey = vec!(4u8);
        let mut pub_part = [0u8; 32];
        pub_part.copy_from_slice(&pub_k[..32]);
        pub_part.reverse();
        pubkey.append(&mut pub_part.to_vec());
        pub_part.copy_from_slice(&pub_k[32..]);
        pub_part.reverse();
        pubkey.append(&mut pub_part.to_vec());

        println!("ephemeral ECDSA pubkey {:02x}", pubkey.iter().format(""));
        
        let ecdsa_pubkey = ring::signature::UnparsedPublicKey::new(
            &ring::signature::ECDSA_P256_SHA256_FIXED, 
            pubkey);
        let mut signature = xt_signer_attn.encode();
        signature.remove(0);
        println!("signature {:02x}", signature.iter().format(""));
        
        match ecdsa_pubkey.verify(&xt_signer, &signature) {
            Ok(()) => {
                #[cfg(test)]
                println!("xt_signer ephemeral ECDSA signature is valid");
            },
            Err(e) => {
                #[cfg(test)]
                println!("ECDSA Signature ERROR: {}",e);  
                return Err("bad signature");
            }
        }        
```

I could track down the error to this instruction
https://github.com/briansmith/ring/blob/772fc080898c7b330fff99701c2a534580ebbf8c/src/ec/suite_b/public_key.rs#L55

so our pubkey seems not to be on the curve. But the curves are identical and verifying the signature with Intel's library works [see our code](https://github.com/scs/pallet-substratee-registry/blob/adfbb5da70b235c6dbbaeae07241abcc88169189/host-calls/src/remote_attestation.rs#L306)

Now, I'd guess the signature verification in ring is correct. But why is our pubkey invalid?

**Comment by briansmith** [comment]
Why do you think the given point is on the curve?

Do I understand correctly that these are the inputs?:

Curve = P-256
X = 97a3729eea3fbe0cfe779590db8b088c55f3a9f8b2c9b860e82443c79d06682e
Y = 43a4f45d2cabc20896c2e70df66cfcf8c3693ec24c86a8deedb593f08b89e21f

BoringSSL also rejects this public key because it isn't on the curve.

> But the curves are identical and verifying the signature with Intel's library works see our code
> Now, I'd guess the signature verification in ring is correct. But why is our pubkey invalid?

My guess is you're not parsing the public key out of the certificate correctly, and/or your byteswapping logic is not correct.

**Comment by brenzi** [comment]
The byteswapping is correct because verifying with ecc_handle works. However, I think I need to pass this onto Intel to be sure ecc_handle does what I think it does: 
https://github.com/intel/linux-sgx/issues/532
