### ISSUE TITLE
Support streaming AEAD AES GCM

### ISSUE THREAD

**Issue by timvisee** [briansmith/ring#988]
I'm looking for AES GCM streaming support. The [`seal...`](https://docs.rs/ring/0.16.13/ring/aead/struct.SealingKey.html) (and related) functions to encrypt currently need the full plaintext in a memory buffer.

I'm looking for streaming support, allowing you to feed chunks of plaintext through the crypter, with manual finalization when the stream ends, instead of needing the full plaintext in a memory buffer at once. This is to support encrypting/decrypting large files (2GB+), which I require for [`ffsend`](https://github.com/timvisee/ffsend).

I'm using this with OpenSSL through their [`Crypter`](https://docs.rs/openssl/0.10.29/openssl/symm/struct.Crypter.html) interface, but would like to implement this with `ring` as crypto backend as well.

Here is a snippet of my OpenSSL usage, which feeds chunks of incoming plaintext into the crypter, finalizing when done to obtain/append the tag: https://github.com/timvisee/ffsend-api/blob/9a3fbbba8b6a922029fc383e6875e68012f97afa/src/pipe/crypto/gcm.rs#L113-L140

Although my example focused on encryption, I'd like to see decryption support as well.
Is this something that can be implemented? Or am I missing something and is this already possible?

**Comment by triska** [comment]
I am also interested in streaming support, specifically for `ChaCha20-Poly1305`.

Could you please consider a general streaming interface to AEAD ciphers, involving a context that can be updated with individual segments, and at the end lets us obtain the computed tag?

**Comment by briansmith** [comment]
Do you need only encryption or also decryption?

**Comment by triska** [comment]
I am interested in both encryption and decryption.

**Comment by timvisee** [comment]
For both as well, sorry that wasn't clear. I'll update the first post.

**Comment by DemiMarie-parity** [comment]
Streaming decryption is quite dangerous with typical AEAD cyphers, as it implies storing unauthenticated plaintext somewhere.  If an attacker can obtain this, they can perform chosen-ciphertext attacks and recover secret data.  [libsodium](https://doc.libsodium.org) provides a [high-level API](https://doc.libsodium.org/secret-key_cryptography/secretstream) that avoids all of these problems, as it encrypts and authenticates small chunks of data.  Furthermore, AES-GCM and the IETF version of ChaCha20-Poly1305 are fundamentally limited in the amount of data they can encrypt at once.

**Comment by briansmith** [comment]
Closing in favor of #1238, which is more general about the entire AEAD API.
