### ISSUE TITLE
Any example on how to extract the AAD from the ciphertext before decryption?

### ISSUE THREAD

**Issue by assafmo** [briansmith/ring#989]
Hi :wave:,

We're looking to extract data from AAD before decrypting the ciphertext, as in our protocol the AAD contains the secp256k1 pubkey that is needed in order to derive the AES shared key.

In all the code samples we could find for AEAD we saw that the AAD is extracted inside the decryption function. 

Thanks!

Cc @toml01

**Comment by brycx** [comment]
In terms of AEAD constructions like ChaCha20Poly1305, the AAD is not a part of the ciphertext. It is only authenticated. So when decrypting something using an AEAD, the AAD that is passed during decryption must be the same, as the AAD passed during encryption. The docs for [`Aad` also mention this](https://briansmith.org/rustdoc/ring/aead/struct.Aad.html):

> The additionally authenticated data (AAD) for an opening or sealing operation. This data is authenticated but is not encrypted.

**Comment by assafmo** [comment]
Thanks
